var Telligent_Common={};Telligent_Common._state=[];Telligent_Common.ConvertHsvColorToRgbColor=function(a){var b=a[0],c=a[1];a=a[2];var d,e,f;if(c==0)return[a,a,a];var g;g=b==360?0:b;g/=60;b=Math.floor(g);var h=g-b;g=a*(1-c);var i=a*(1-c*h);c=a*(1-c*(1-h));if(b==0){d=a;e=c;f=g}if(b==1){d=i;e=a;f=g}if(b==2){d=g;e=a;f=c}if(b==3){d=g;e=i;f=a}if(b==4){d=c;e=g;f=a}if(b==5){d=a;e=g;f=i}d=Math.round(d);e=Math.round(e);f=Math.round(f);return[d,e,f]};
Telligent_Common.ConvertRgbColorToHsvColor=function(a){var b=a[0],c=a[1];a=a[2];var d,e,f=Math.max(Math.max(b,c),a),g=f-Math.min(Math.min(b,c),a);e=f==0?0:g/f;if(e==0)d=0;else if(b==f)d=60*(c-a)/g;else if(c==f)d=120+60*(a-b)/g;else if(a==f)d=240+60*(b-c)/g;if(d<0)d+=360;return[d,e,f]};Telligent_Common.ConvertDecimalToHexadecimal=function(a,b){for(var c="",d;a>0;){d=a%16;c="0123456789abcdef".substr(d,1)+c;a-=d;a/=16}if(b)for(;c.length<b;)c="0"+c;return c};
Telligent_Common.ConvertHtmlColorToRgbColor=function(a){a=a.replace(/[^0-9a-f]/ig,"");return a.length==3?[parseInt(a.substr(0,1)+a.substr(0,1),16),parseInt(a.substr(1,1)+a.substr(1,1),16),parseInt(a.substr(2,1)+a.substr(2,1),16)]:a.length==6?[parseInt(a.substr(0,2),16),parseInt(a.substr(2,2),16),parseInt(a.substr(4,2),16)]:[255,255,255]};
Telligent_Common.ConvertRgbColorToHtmlColor=function(a){return"#"+Telligent_Common.ConvertDecimalToHexadecimal(a[0],2)+Telligent_Common.ConvertDecimalToHexadecimal(a[1],2)+Telligent_Common.ConvertDecimalToHexadecimal(a[2],2)};Telligent_Common.GetContrastingHtmlColorForRgbColor=function(a){return a[0]*2+a[1]*5+a[2]>1024?"#000000":"#ffffff"};
Telligent_Common.GetElementInfo=function(a){var b={};if(a.getBoundingClientRect){a=a.getBoundingClientRect();var c=0,d=0;if(typeof window.pageXOffset=="number"){c=window.pageXOffset;d=window.pageYOffset}else if(document.body&&(document.body.scrollLeft||document.body.scrollTop)){c=document.body.scrollLeft;d=document.body.scrollTop}else if(document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)){c=document.documentElement.scrollLeft;d=document.documentElement.scrollTop}b.Left=
a.left+c;b.Top=a.top+d;b.Right=a.right+c;b.Bottom=a.bottom+d;if(this.IsIE()&&b.Left>=2&&!this.IsIE8()){b.Left-=2;b.Top-=2;b.Right-=2;b.Bottom-=2}b.Width=a.right-a.left;b.Height=a.bottom-a.top}else{d=c=0;for(var e=a,f=false,g=false,h=Telligent_Common.IsIE();e;){f||(c+=e.offsetLeft);g||(d+=e.offsetTop);if(h&&e.offsetParent&&e.offsetParent.style.position=="relative")if(!e.offsetParent.style.width){f=true;if(e.offsetParent.style.top||e.offsetParent.style.bottom){d+=e.offsetHeight;g=true}}e=e.offsetParent}b.Left=
c;b.Top=d;b.Right=c+a.offsetWidth;b.Bottom=c+a.offsetHeight;b.Width=a.offsetWidth;b.Height=a.offsetHeight}return b};
Telligent_Common.GetWindowInfo=function(){var a=0,b=0,c=0,d=0;if(typeof window.pageXOffset=="number"){a=window.pageXOffset;b=window.pageYOffset}else if(document.body&&(document.body.scrollLeft||document.body.scrollTop)){a=document.body.scrollLeft;b=document.body.scrollTop}else if(document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)){a=document.documentElement.scrollLeft;b=document.documentElement.scrollTop}if(typeof window.innerWidth=="number"){c=window.innerWidth;
d=window.innerHeight}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){c=document.documentElement.clientWidth;d=document.documentElement.clientHeight}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)){c=document.body.clientWidth;d=document.body.clientHeight}if(document.documentElement&&(document.documentElement.scrollHeight||document.documentElement.offsetHeight))if(document.documentElement.scrollHeight>document.documentElement.offsetHeight){contentWidth=
document.documentElement.scrollWidth;contentHeight=document.documentElement.scrollHeight}else{contentWidth=document.documentElement.offsetWidth;contentHeight=document.documentElement.offsetHeight}else if(document.body&&(document.body.scrollHeight||document.body.offsetHeight))if(document.body.scrollHeight>document.body.offsetHeight){contentWidth=document.body.scrollWidth;contentHeight=document.body.scrollHeight}else{contentWidth=document.body.offsetWidth;contentHeight=document.body.offsetHeight}else{contentWidth=
c;contentHeight=d}if(this.IsSafari()){if(d>contentHeight)contentHeight=d}else if(d>contentHeight)d=contentHeight;if(this.IsSafari()){if(c>contentWidth)contentWidth=c}else if(c>contentWidth)c=contentWidth;var e={};e.ScrollX=a;e.ScrollY=b;e.Width=c;e.Height=d;e.ContentWidth=contentWidth;e.ContentHeight=contentHeight;return e};
Telligent_Common.GetCurrentStyleValue=function(a,b,c,d){var e="";try{if(document.defaultView&&document.defaultView.getComputedStyle)e=document.defaultView.getComputedStyle(a,"").getPropertyValue(b);else if(a.currentStyle)e=a.currentStyle[c]}catch(f){}return(e=="inherit"||e=="transparent")&&a.parentNode!=null?Telligent_Common.GetCurrentStyleValue(a.parentNode,b,c,d):e!=""&&e!=undefined&&e!="rgba(0, 0, 0, 0)"?e:d};
Telligent_Common.GetStyleOffset=function(a){var b={};b.Height=Telligent_Common.IsNanDefault(parseInt(Telligent_Common.GetCurrentStyleValue(a,"border-top-width","borderTopWidth","0")),0)+Telligent_Common.IsNanDefault(parseInt(Telligent_Common.GetCurrentStyleValue(a,"border-bottom-width","borderBottomWidth","0")),0)+Telligent_Common.IsNanDefault(parseInt(Telligent_Common.GetCurrentStyleValue(a,"padding-top","paddingTop","0")),0)+Telligent_Common.IsNanDefault(parseInt(Telligent_Common.GetCurrentStyleValue(a,
"padding-bottom","paddingBottom","0")),0);b.Width=Telligent_Common.IsNanDefault(parseInt(Telligent_Common.GetCurrentStyleValue(a,"border-left-width","borderLeftWidth","0")),0)+Telligent_Common.IsNanDefault(parseInt(Telligent_Common.GetCurrentStyleValue(a,"border-right-width","borderRightWidth","0")),0)+Telligent_Common.IsNanDefault(parseInt(Telligent_Common.GetCurrentStyleValue(a,"padding-left","paddingLeft","0")),0)+Telligent_Common.IsNanDefault(parseInt(Telligent_Common.GetCurrentStyleValue(a,"padding-right",
"paddingRight","0")),0);return b};Telligent_Common.IsNanDefault=function(a,b){return isNaN(a)?b:a};Telligent_Common.EscapeForRegExp=function(a){return a.replace(/([\\\(\^\$\*\+\?\{\}\.\)\|\-])/g,"\\$1")};
Telligent_Common.GetSelectedHtmlInElement=function(a,b,c,d){var e=true,f=null;if(window.getSelection){var g=window.getSelection();if(g&&g.rangeCount>0&&g.toString().length>0){e=false;g=g.getRangeAt(0);var h=document.createRange();h.selectNode(a);if(h.compareBoundaryPoints(Range.START_TO_START,g)<=0&&h.compareBoundaryPoints(Range.END_TO_END,g)>=0){d=document.createElement("div");d.appendChild(g.cloneContents());f=d.innerHTML}else d&&alert(d)}}else if(document.selection)if((g=document.selection.createRange())&&
g.text){e=false;h=g.parentElement();if(h!=null&&Telligent_Common.ElementContainsElement(a,h))f=g.htmlText;else d&&alert(d)}if(f==null&&(e&&b||c))f=a.innerHTML;return f};Telligent_Common.ElementContainsElement=function(a,b){if(!a||!b)return false;if(a==b)return true;if(a&&a.childNodes)for(var c=0;c<a.childNodes.length;c++)if(a.childNodes[c]==b||Telligent_Common.ElementContainsElement(a.childNodes[c],b))return true;return false};
Telligent_Common.GetCurrentCursorIndex=function(a){var b=0;if(a.selectionStart||a.selectionStart=="0")b=a.selectionStart;else if(document.selection){var c=a.value;b=document.selection.createRange();var d=String.fromCharCode(1);b.text=d;b=a.value.indexOf(d);a.value=c}return b};
Telligent_Common._delayedSetCurrentCursorSelection=function(a){var b=Telligent_Common.GetStateByStateId(a,"Telligent_Common_SetCurrentCursorSelection");if(b){Telligent_Common.SetCurrentCursorSelection(b.InputElement,b.StartIndex,b.EndIndex,false,b.PersistedValue);Telligent_Common.ClearStateByStateId(a,"Telligent_Common_SetCurrentCursorSelection")}};Telligent_Common.IsSafari=function(){return navigator.userAgent.indexOf("Safari")!=-1};Telligent_Common.IsOpera=function(){return window.opera!=null};
Telligent_Common.IsIE=function(){return navigator&&navigator.userAgent&&navigator.userAgent.indexOf("MSIE")!=-1};Telligent_Common.IsIE8=function(){if(this.IsIE())return parseInt(/MSIE ([0-9]*)\./.exec(navigator.userAgent)[1],9)>=8;return false};Telligent_Common.CreateSafeFunction=function(a,b){return function(){return b.apply(a,arguments)}};Telligent_Common.DisposeContent=function(a){if(a&&a.childNodes&&a.childNodes.length>0)for(var b=0;b<a.childNodes.length;b++){if(a.childNodes[b].dispose)try{a.childNodes[b].dispose()}catch(c){}Telligent_Common.DisposeContent(a.childNodes[b])}};
Telligent_Common.SetCurrentCursorSelection=function(a,b,c,d,e){if(Telligent_Common.IsSafari()||Telligent_Common.IsOpera())if(d){(d=Telligent_Common.GetStateByKey(a,"Telligent_Common_SetCurrentCursorSelection"))&&d.CursorTimeout&&window.clearTimeout(d.CursorTimeout);d={};d.InputElement=a;d.StartIndex=b;d.EndIndex=c;d.PersistedValue=e;b=Telligent_Common.SaveStateByKey(a,"Telligent_Common_SetCurrentCursorSelection",d);d.CursorTimeout=window.setTimeout(new Function("Telligent_Common._delayedSetCurrentCursorSelection("+
b+");"),9);Telligent_Common.SaveStateByKey(a,"Telligent_Common_SetCurrentCursorSelection",d);return}else{a.focus();if(e)a.value=e}try{if(document.selection){var f=a.createTextRange();f.move("character",b);f.moveEnd("character",c-b);f.select()}else if(a.setSelectionRange){a.setSelectionRange(b,c);a.focus()}else if(a.selectionStart||a.selectionStart=="0"){a.selectionStart=b;a.selectionEnd=c}}catch(g){}};
Telligent_Common.GetStateByStateId=function(a,b){return Telligent_Common._state.length>a&&a>=0&&Telligent_Common._state[a]&&Telligent_Common._state[a]._stateProcessId==b?Telligent_Common._state[a]._state:null};Telligent_Common.GetStateByKey=function(a,b){for(var c=0;c<Telligent_Common._state.length;c++)if(Telligent_Common._state[c]&&Telligent_Common._state[c]._stateKey==a&&Telligent_Common._state[c]._stateProcessId==b)return Telligent_Common._state[c]._state;return null};
Telligent_Common.SaveStateByStateId=function(a,b,c){if(Telligent_Common._state.length>a&&a>=0&&Telligent_Common._state[a]&&Telligent_Common._state[a]._stateProcessId==b)Telligent_Common._state[a]._state=c};
Telligent_Common.SaveStateByKey=function(a,b,c){for(var d=-1,e=0;e<Telligent_Common._state.length;e++)if(Telligent_Common._state[e]){if(Telligent_Common._state[e]._stateKey==a&&Telligent_Common._state[e]._stateProcessId==b){Telligent_Common._state[e]._state=c;return e}}else d=e;e={};e._stateKey=a;e._stateProcessId=b;e._state=c;if(d!=-1){Telligent_Common._state[d]=e;return d}else{Telligent_Common._state[Telligent_Common._state.length]=e;return Telligent_Common._state.length-1}};
Telligent_Common.ClearStateByStateId=function(a,b){if(Telligent_Common._state.length>a&&a>=0&&Telligent_Common._state[a]&&Telligent_Common._state[a]._stateProcessId==b)Telligent_Common._state[a]=null};Telligent_Common._hiddenSelects=[];Telligent_Common._elementsHidingSelects=[];
Telligent_Common._addHiddenSelect=function(a,b){for(var c=null,d=-1,e=0;e<Telligent_Common._hiddenSelects.length&&c==null;e++)if(Telligent_Common._hiddenSelects[e]){if(Telligent_Common._hiddenSelects[e].SelectElement==b)c=Telligent_Common._hiddenSelects[e]}else d=e;if(c==null){c={};c.SelectElement=b;c.ElementsHidingSelectsIndeces=[];c.OriginalVisibility=b.style.visibility;c.SelectElement.style.visibility="hidden";if(d==-1){Telligent_Common._hiddenSelects[Telligent_Common._hiddenSelects.length]=c;
c.Index=Telligent_Common._hiddenSelects.length-1}else{Telligent_Common._hiddenSelects[d]=c;c.Index=d}}d=false;for(e=0;e<c.ElementsHidingSelectsIndeces.length&&!d;e++)if(c.ElementsHidingSelectsIndeces[e]==a.Index)d=true;if(!d){a.HiddenSelectsIndeces[a.HiddenSelectsIndeces.length]=c.Index;c.ElementsHidingSelectsIndeces[c.ElementsHidingSelectsIndeces.length]=a.Index}};
Telligent_Common._addElementHidingSelect=function(a){for(var b=null,c=-1,d=0;d<Telligent_Common._elementsHidingSelects.length&&b==null;d++)if(Telligent_Common._elementsHidingSelects[d]){if(Telligent_Common._elementsHidingSelects[d].Element==a)b=Telligent_Common._elementsHidingSelects[d]}else c=d;if(b==null){b={};b.Element=a;b.HiddenSelectsIndeces=[];if(c==-1){Telligent_Common._elementsHidingSelects[Telligent_Common._elementsHidingSelects.length]=b;b.Index=Telligent_Common._elementsHidingSelects.length-
1}else{Telligent_Common._elementsHidingSelects[c]=b;b.Index=c}}return b};
Telligent_Common.HideElementsInWindow=function(a,b,c){var d=null,e=this.GetElementInfo(a),f=b.document.getElementsByTagName("iframe");for(b=0;b<f.length;b++)if(!Telligent_Common.ElementContainsElement(a,f[b]))try{Telligent_Common.HideElementsInWindow(a,f[b].contentWindow,c)}catch(g){var h=this.GetElementInfo(f[b]);if(c||h.Top<e.Bottom&&e.Top<h.Bottom&&h.Left<e.Right&&e.Left<h.Right){if(d==null)d=Telligent_Common._addElementHidingSelect(a);Telligent_Common._addHiddenSelect(d,f[b]);f[b].style.visibility=
"hidden"}}f=["object","embed","applet"];if(this.IsIE())f[f.length]="select";for(b=0;b<f.length;b++)for(var i=document.getElementsByTagName(f[b]),j=0;j<i.length;j++)if(!Telligent_Common.ElementContainsElement(a,i[j])){h=this.GetElementInfo(i[j]);if(c||h.Top<e.Bottom&&e.Top<h.Bottom&&h.Left<e.Right&&e.Left<h.Right){if(d==null)d=Telligent_Common._addElementHidingSelect(a);Telligent_Common._addHiddenSelect(d,i[j]);i[j].style.visibility="hidden"}}};
Telligent_Common.HideSelectBoxes=function(a,b){Telligent_Common.HideElementsInWindow(a,window.window,b)};
Telligent_Common.ShowSelectBoxes=function(a){for(var b=null,c=0;c<Telligent_Common._elementsHidingSelects.length&&b==null;c++)if(Telligent_Common._elementsHidingSelects[c])if(Telligent_Common._elementsHidingSelects[c].Element==a)b=Telligent_Common._elementsHidingSelects[c];if(b!=null){for(c=0;c<b.HiddenSelectsIndeces.length;c++)if(a=Telligent_Common._hiddenSelects[b.HiddenSelectsIndeces[c]])if(a.ElementsHidingSelectsIndeces.length==1){try{if(a.SelectElement.style.visibility=="hidden")a.SelectElement.style.visibility=
a.OriginalVisibility}catch(d){}Telligent_Common._hiddenSelects[a.Index]=null}else{for(var e=[],f=0;f<a.ElementsHidingSelectsIndeces.length;f++)if(a.ElementsHidingSelectsIndeces[f]!=b.Index)e[e.length]=a.ElementsHidingSelectsIndeces[c];a.ElementsHidingSelectsIndeces=e}Telligent_Common._elementsHidingSelects[b.Index]=null}};Telligent_Common._disposableControls=[];
Telligent_Common.RegisterDisposableControl=function(a){if(a)Telligent_Common._disposableControls[Telligent_Common._disposableControls.length]=a};Telligent_Common._windowOnUnload=function(){for(var a=0;a<Telligent_Common._disposableControls.length;a++)try{eval(Telligent_Common._disposableControls[a]).Dispose()}catch(b){}Telligent_Common._disposableControls=[];this._originalWindowOnUnload&&this._originalWindowOnUnload()};this._originalWindowOnUnload=null;
if(window.onunload)this._originalWindowOnUnload=window.onunload;window.onunload=new Function("Telligent_Common._windowOnUnload();");
