if (self === top || document.referrer.match(/^https?:\/\/[a-z0-9]+\.(?:oprah\.com|stumbleupon.com)\//)) document.write(decodeURIComponent('%3Cstyle%3Ehtml%7Bvisibility%3Avisible%7D%3C%2Fstyle%3E')); else top.location = self.location;

window.Global||(Global={});
window.Maui||(Maui={});
Global.LOCATION_CODE='US' || (document.cookie.match(/\bcheck_loc=([A-Z]+)/)||[]).pop();
var _sf_startpt=(new Date()).getTime();
