var adsa_tempdt=new Date,adsa_temptm=adsa_tempdt.getTime();if(!window.adsg_adids)var adsg_adids=[];adsg_adids[adsg_adids.length]=["0000000","0000000","000000000","00000000",adsa_temptm,"AdScript START","log"];function ads_gettag(a,b,c,e,d){d||(d="js");window.adsg_rconf&&adsg_rconf[b+"x"+c]&&(d=adsg_rconf[b+"x"+c]);return ads_maketag(a,b,c,e,d)}
function ads_maketag(a,b,c,e,d){var f,g=adsf_getdispsz(b+"x"+c),h="ad"+adsc_tile+Math.floor(99999*Math.random()),i=parseInt(1E8*Math.random());debout("AdRequest-URL mit den folgenden Parametern wurde angefordert: "+a+" (type) - "+b+" (width) - "+c+" (height) - "+e+" (percent) - "+d+" (responsetype).");adsc_tile++;adso_tagvars.set("tile",adsc_tile);a=adsf_gtAdTyp(a);if(11==a||13==a)d="pfjs";adsg_size_slot[a]++;adso_tagvars.set("ss",adsg_size_slot[a]);""!=adsc_keyword&&(adso_tagvars.addcsv("kw",adsc_keyword),
adsc_keyword="");adso_tagvars.set("tagid",h);adso_tagvars.set("oba",i);adso_tagvars.set("sz",b+"x"+c);if("string"==typeof adsg_tagsizeoverride[a]){c=adsg_tagsizeoverride[a].split(";");for(e=0;e<c.length;e++)b=c[e].split("="),adso_tagvars.set(b[0],b[1])}if("string"==typeof adsg_exclusionval[a]){c=adsg_exclusionval[a].split(";");for(e=0;e<c.length;e++)b=c[e].split("="),adso_tagvars.add(b[0],b[1])}b=adso_response.conf[d];adso_tagvars.add("!c",b[1]);dcoptSession&&1===a&&adso_tagvars.add("dcopt","ist");
d=adsg_inf.config.site+"_"+adsc_dartsite+"/"+adsc_zone+";"+adso_tagvars.getallstr()+adsc_mozSegs+adsc_apSegs+adsc_nuggSegs+adsc_segQS;darturl="http://ad.de.doubleclick.net/N3673/"+b[0]+"/"+d+"?";switch(b[1]){case "iframe":f='<iframe id="'+h+'"  src="'+darturl+'" width="'+g.w+'" height="'+g.h+'" marginheight="0" marginwidth="0" hspace="0" vspace="0" frameBorder="0" noresize scrolling="no"></iframe>';break;case "lzfif":id="lad"+Math.floor(55445454545*Math.random());f="<div style='position:relative; background-color:#FFFFFF; width:"+
g.w+"px; height:0px;overflow:hidden;' id='"+id+"'></div>";adso_lzf.add(id,darturl,g.w,g.h,'<iframe id="'+h+'"  src="'+darturl+'" width="'+g.w+'" height="'+g.h+'" marginheight="0" marginwidth="0" hspace="0" vspace="0" frameBorder="0" noresize scrolling="no"></iframe>');break;case "dfif":id="lad"+Math.floor(55445454545*Math.random());f="<div style='position:relative; background-color:#FFFFFF; width:"+g.w+"px;height:0px;overflow:hidden;'   id='"+id+"'></div>";adsf_dfif_add(id,darturl,g.w,g.h);break;
case "url":f=darturl;break;case "virtual":adsg_vslots[a]?f="<script language='javascript' id='v_ad' >"+adsg_vslots[a]+"<\/script>":adsc_tagout="";break;case "fif":f='<iframe id="'+h+'"  src="'+adsg_inf.config.fifurl+"?"+darturl+'" width="'+g.w+'" height="0" marginheight="0" marginwidth="0" hspace="0" vspace="0" frameBorder="0" noresize scrolling="no"></iframe>';break;case "none":f="";break;default:f="<script language='javascript' id='"+h+"' src='"+darturl+"'><\/script>"}adso_tagvars.del("!c",b[1]);
dcoptSession&&1===a&&adso_tagvars.del("dcopt","ist");if("string"==typeof adsg_exclusionval[a]){c=adsg_exclusionval[a].split(";");for(e=0;e<c.length;e++)b=c[e].split("="),adso_tagvars.del(b[0],b[1])}adso_tagvars.set("dcmt","");debout(darturl);return f}
function adsf_import(a){for(var b,c=a.length,e=a[0],d=2;d<c;d++)b=a[d].split(","),vt=a[1]+"_"+b[0],e[vt]?"string"==typeof e[vt]&&(e[vt]=adsf_ssan(e[vt])):e[vt]=b[1]?b[1]:"";window.adsg_getvars={};a=" "+document.referrer+"?";a=a.split("?")[1].split("&");for(d=0;d<a.length;d++)ttemp=a[d].split("="),adsg_getvars["ref_"+adsf_ssan(ttemp[0])]=adsf_ssan(ttemp[1]);a=" "+window.location.search+"?";a=a.split("?")[1].split("&");for(d=0;d<a.length;d++)ttemp=a[d].split("="),adsg_getvars[adsf_ssan(ttemp[0])]=adsf_ssan(ttemp[1]);
debout("Variables have been imported from the website.")}function adsf_getdispsz(a){var b={"1x2":"160x600","300x251":"300x250","300x252":"300x250","300x253":"300x250","300x254":"300x250","460x200":"640x250","640x480":"640x480","728x91":"728x90"};b[a]&&(a=b[a]);a=a.split("x");return{w:a[0],h:a[1]}}function adsf_ssan(a){return void 0==a?"":a.replace(/[^a-zA-Z0-9/|,-_]/g,"").toLowerCase()}
function adso_mapread(a){var b=window,c,e=[0,0],d=adso_map.sonstiges;b.adsc_dartsite=d[0];b.adsc_zone=d[1];e=d[2];if(adso_map[a[0]]){d=adso_map[a[0]];b.adsc_dartsite=d[0];b.adsc_zone=d[1];d[2]&&(0!=d[2][0]&&(e[0]=d[2][0]),0!=d[2][1]&&(e[1]=d[2][1]));for(var f=1;f<a.length;f++)if(d[3]&&d[3][a[f]]&&(d=d[3][a[f]],""!=d[0]&&(b.adsc_dartsite=d[0]),b.adsc_zone=1==f?d[1]:b.adsc_zone+("_"+d[1]),d[2]))0!=d[2][0]&&(e[0]=d[2][0]),0!=d[2][1]&&(e[1]=d[2][1])}if(0!=e[1])try{c=e[1].split(","),b[c[0]]&&("object"==
typeof b[c[0]]?"number"==typeof b[c[0]].length&&(b[c[0]][b[c[0]].length]=c[1]):b[c[0]]=c[1])}catch(g){}0!=e[0]&&(adsc_wunderloop=adsg_inf.config.site+"/"+e[0])}function adsf_gtAdTyp(a){if(a&&""+a==""+parseInt(""+a))return parseInt(""+a);for(var b=0;b<adsg_katval.length;b++)if(adsg_katval[b]==a.toUpperCase())return b;return"0"}function adsf_setpix(a){var b;window.adsa_pixArr||(window.adsa_pixArr=[]);a&&0==a.indexOf("http://")&&(b=adsa_pixArr.length,adsa_pixArr[b]=new Image,adsa_pixArr[b].src=a)}
function adsf_cookie(a,b,c,e){var d,f;if(4==arguments.length)c&&0<=parseInt(c,10)&&(debout("cookie write:"+[a,b,c,e]),d=new Date,f=d.getTime()+Math.floor(864E5*c),d.setTime(f),d=d.toGMTString(),document.cookie=a+"="+escape(b)+"; expires="+d+"; path="+e+";");else{d="";if(a&&3<a.length)for(var b=document.cookie.split(";"),g=0;g<b.length;g++)-1!=b[g].indexOf(a+"=")&&(debout("cookie read: match"+b[g]),f=b[g].split("="),d=unescape(f[1]));return d}}
function adsf_sessionreset(){adsf_cookie("tfs_usr",0,0.02,"/");eraseCookie(sessionCookieName)}function adsf_ckwtemp(a){adsf_cookie("adcc_ckw",a.replace(/\W/g,""),1,"/")}function adsf_getSetCookieKeyword(){var a=adsf_cookie("adcc_ckw");"string"==typeof a&&3<a.length&&(adso_tagvars.add("kw",a),debout('The keyword "'+a+'" has been added to the tag parameters.'))}
function adsf_dfif_add(a,b,c,e){window.tfs_dfobs||(window.tfs_dfobs=[]);tfs_dfobs[tfs_dfobs.length]=[!0,a,b,c,e];setTimeout(adsf_dfif_ladd,100)}
function adsf_dfif_show(a,b,c,e){var c={id:"dfif_"+a,name:a+"_name",src:"about:blank",width:c,height:e,scrolling:"no",frameBorder:0,style_border:0,allowtransparency:"true",hspace:0,vspace:0,marginHeight:0,marginWidth:0},b=adsc_fiftemplate.replace("##myid##",a).replace("##tag##",b),e=document.createElement("iframe"),d;for(d in c)typeof("function"!=c[d])&&(-1==d.indexOf("_")?e[d]=c[d]:e.style[d.split("_")[1]]=c[d]);document.getElementById(a).appendChild(e);a=document.getElementById(c.id).contentWindow.document;
a.open();a.write(b);window.setTimeout("document.getElementById('"+c.id+"').contentWindow.document.close()",3E3)}function adsf_dfif_ladd(){if(window.tfs_dfobs)for(var a=0;a<tfs_dfobs.length;a++)tfs_dfobs[a]&&!0==tfs_dfobs[a][0]&&(tfs_dfobs[a][0]=!1,adsf_dfif_show(tfs_dfobs[a][1],tfs_dfobs[a][2],tfs_dfobs[a][3],tfs_dfobs[a][4]))}
function adsf_getSetVideoProps(){adsg_inf.client.swfv=function(){var a,b,c,e=/^Shockwave Flash (\d+)/;if((b=navigator.plugins)&&(c=b["Shockwave Flash"]||b["Shockwave Flash 2.0"])&&(a=c.description.match(e)))return a[1];if(window.ActiveXObject)for(a=10;0<a;a--)try{if(new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+a))return a}catch(d){}return 0}();adsg_inf.client.swfv>=adsg_inf.client.swfminv&&adsg_inf.client.swfv<=adsg_inf.client.swfmaxv?(adsg_inf.client.swf="1",adso_tagvars.add("kw","vc_flv"),
debout("Client: Valid Flash version detected.")):debout("Client: No working Flash version detected.");adso_tagvars.set("tfswf",adsg_inf.client.swf);adso_tagvars.set("tfswfv",adsg_inf.client.swfv)}function adsf_getSetMobileProps(){if(m=navigator.userAgent.toLowerCase().match(/(iphone|ipod|ipad|android|mobile)/))adsg_inf.client.ismoblile=!0,adso_tagvars.add("!c","mobile"),adso_tagvars.set("mob","1"),debout("Client: This is a mobile device.")}
function adsf_getSetAdExclConfig(){if(window.adsc_adExclConfig)for(var a=0;a<adsc_adExclConfig.length;a++)adsc_adExclConfig[a]&&0==adsc_adExclConfig[a].indexOf("-")&&adso_tagsvars.add("!c","c_"+adsc_adExclConfig[a].split("-")[1])}
var tfsbase={obpos:function(a){for(var b=a.offsetLeft,c=a.offsetTop,a=a.offsetParent;null!=a;)b+=a.offsetLeft,c+=a.offsetTop,a=a.offsetParent;return{x:b,y:c}},winprop:function(){var a=-1,b=-1,c=-1,e=-1,d=!1,f;if(self.innerWidth)d=!0,f=self,e=f.pageXOffset,c=f.pageYOffset,b=f.innerWidth,a=f.innerHeight;else{document.documentElement&&document.documentElement.clientWidth?(d=!0,f=document.documentElement):document.body&&(f=document.body);try{e=f.scrollLeft,c=f.scrollTop,b=f.clientWidth,a=f.clientHeight}catch(g){}}return{cw:b,
ch:a,sl:e,st:c,pf:d}},mediasupport:function(){var a=!!document.createElement("canvas").getContext;try{var b=!!window.WebGLRenderingContext&&!!document.createElement("canvas").getContext("experimental-webgl")}catch(c){b=!1}return{canvas2d:a,webgl:b}}},adso_tagvars={val:[],add:function(a,b){this.val[a]?this.val[a][this.val[a].length]=b:this.val[a]=[b]},addcsv:function(a,b){var c,e;if("string"==typeof b){b=b.split(",");c=b.length;for(e=0;e<c;e++)""!=b[e]&&this.add(a,b[e])}},set:function(a,b){this.val[a]=
[b]},getallstr:function(a,b){var c="",e,d,f,g;a||(a=";");for(e in this.val)if("function"!=typeof this.val[e]){g=this.val[e].length;if(b){f=e+"=";for(d=0;d<g;d++)this.val[e][d]&&""!=this.val[e][d]&&(""==f&&(c+=b),c+=f+this.val[e][d],f="")}else for(d=0;d<g;d++)this.val[e][d]&&""!=this.val[e][d]&&(c+=e+"="+this.val[e][d]+a);b&&(c+=a)}return c},del:function(a,b){var c,e;if(void 0!=this.val[a]){c=this.val[a].length;for(e=0;e<c;e++)this.val[a][e]==b&&(this.val[a][e]="")}},chk:function(a,b){var c,e=!1,d;
if(this.val[a]){d=this.val[a].length;for(c=0;c<d;c++)this.val[a][c]==b&&(e=!0)}return e},get:function(a){var b="";this.val[a]&&(b=this.val[a]);return b}},adso_lzf={timer:10,viewporty:-11,state:0,ids:[],load:function(a,b){debout("load"+a+":"+b);document.getElementById(a).innerHTML=b},add:function(a,b,c,e,d){adso_lzf.ids[adso_lzf.ids.length]=[1,a,0,0,{w:c,h:e},d,b];0==adso_lzf.state&&(adso_lzf.state++,adso_lzf.loop())},loop:function(){var a=tfsbase.winprop();if(a.st!=adso_lzf.viewporty||0!=adso_lzf.timer){adso_lzf.viewporty=
a.st;0<adso_lzf.timer&&adso_lzf.timer--;for(var b=0;b<adso_lzf.ids.length;b++)1==adso_lzf.ids[b][0]&&(0==adso_lzf.ids[b][2]&&document.getElementById(adso_lzf.ids[b][1])?(adso_lzf.ids[b][2]=document.getElementById(adso_lzf.ids[b][1]),adso_lzf.ids[b][3]=tfsbase.obpos(adso_lzf.ids[b][2])):adso_lzf.ids[b][3].y<a.st+a.ch&&adso_lzf.ids[b][3].y>a.st&&(adsf_dfif_add(adso_lzf.ids[b][1],adso_lzf.ids[b][6],adso_lzf.ids[b][4].w,adso_lzf.ids[b][4].h),adso_lzf.ids[b][0]="visible;"))}setTimeout(adso_lzf.loop,200)}};
function adsf_addscriptnode(a,b,c){var e=document.getElementsByTagName("script")[0],d=document.createElement("script");b||(b=function(){});d.id="tfs_scrcidsf_"+Math.floor(9999999*Math.random());d.type="text/javascript";d.tfsCallback=b;d.tfsParams=c;d.onload=function(){try{this.tfsCallback(this.tfsParams)}catch(c){debout(c,a,b)}};d.onreadystatechange=function(){if("complete"==this.readyState||"loaded"==this.readyState)this.onload()};e.parentNode.appendChild(d);d.src=a;debout('A script node with source "'+
d.src+'" has been inserted into the page.')}
function adProbeCallback(a){for(var b="",c=0;c<a.length;c++)if(window["wl"+a[c]+"camp"]&&""!=window["wl"+a[c]+"camp"]&&(b=b+a[c]+"_"+window["wl"+a[c]+"camp"]+",",debout('AdProbe callback function added content unit id "'+a[c]+'" and campaign id "'+window["wl"+a[c]+"camp"]+'" to be used in the AdProbe cookie for the next impression.')),window["wl"+a[c]+"tempcamp"]&&""!=window["wl"+a[c]+"tempcamp"])debout('AdProbe script has overwritten existing variable "window.wl'+a[c]+'camp" with "'+window["wl"+
a[c]+"camp"]+'".'),window["wl"+a[c]+"camp"]=window["wl"+a[c]+"tempcamp"],debout('AdProbe callback function set variable "window.wl'+a[c]+'camp" back to "'+window["wl"+a[c]+"tempcamp"]+'" because it already had a value for this impression.');createCookie("apSegs",b,10)}
function createAdProbeParamURLSection(){var a=readCookie("apSegs");if(null!=a&&""!=a){for(var a=a.split(","),b=0;b<a.length;b++)if(""!=a[b]){var c=a[b].split("_");adsc_apSegs=adsc_apSegs+"wlcuid="+c[0]+";";debout('AdProbe parameters function found an AdProbe cookie and added "wlcuid='+c[0]+';" to adsc_apSegs.');window["wl"+c[0]+"camp"]=c[1];window["wl"+c[0]+"tempcamp"]=c[1];debout('AdProbe parameters function found an AdProbe cookie and set "window.wl'+c[0]+'camp" and "window.wl'+c[0]+'tempcamp" to '+
c[1]+".")}eraseCookie("apSegs");debout("AdProbe parameters function erased the AdProbe cookie for the next impression.")}}
function addAdProbeScriptNode(){if(!0==adsg_inf.config.adprobe.ap.state&&!0==adsg_inf.config.adprobe.as.state)if(!otpSession&&currentSession<=otpSetup[otpSetup.length-1]){var a="http://req.connect.wunderloop.net/AP/"+adsg_inf.config.adprobe.as.pubid+"/"+adsg_inf.config.adprobe.as.siteid+"/"+adsg_inf.config.adprobe.as.firstunit+"/js?cus="+adsg_inf.config.adprobe.as.otp_unitsarray+"&ord="+Math.floor(9999999*Math.random());adsf_addscriptnode(a,adProbeCallback,adsg_inf.config.adprobe.as.otp_unitsarray);
debout("Added AdProbe OTP Script Node to the page.")}else otpSession&&currentSession<otpSetup[otpSetup.length-1]?(a="http://req.connect.wunderloop.net/AP/"+adsg_inf.config.adprobe.as.pubid+"/"+adsg_inf.config.adprobe.as.siteid+"/"+adsg_inf.config.adprobe.as.firstunit+"/js?cus="+adsg_inf.config.adprobe.as.itp_unitsarray+"&ord="+Math.floor(9999999*Math.random()),adsf_addscriptnode(a,adProbeCallback,adsg_inf.config.adprobe.as.itp_unitsarray),debout("Added AdProbe ITP Script Node to the page.")):currentSession>=
otpSetup[otpSetup.length-1]&&(a="http://req.connect.wunderloop.net/AP/"+adsg_inf.config.adprobe.as.pubid+"/"+adsg_inf.config.adprobe.as.siteid+"/"+adsg_inf.config.adprobe.as.firstunit+"/js?cus="+adsg_inf.config.adprobe.as.itp_unitsarray+"&ord="+Math.floor(9999999*Math.random()),adsf_addscriptnode(a,adProbeCallback,adsg_inf.config.adprobe.as.itp_unitsarray),debout("Added AdProbe ITP Script Node to the page."))}
function mergeAdProbeUnitArrays(){!0==adsg_inf.config.adprobe.ap.state&&!0==adsg_inf.config.adprobe.pg.state&&(adsg_inf.config.adprobe.as.otp_unitsarray=adsg_inf.config.adprobe.as.otp_unitsarray.concat(adsg_inf.config.adprobe.pg.unitsarray),adsg_inf.config.adprobe.as.itp_unitsarray=adsg_inf.config.adprobe.as.itp_unitsarray.concat(adsg_inf.config.adprobe.pg.unitsarray),debout("P&G content unit ids have been merged with AdProbe."))}
function addNuggAdScriptNode(){if(("undefined"!=adsg_inf.config.nuggadid||""!=adsg_inf.config.nuggadid)&&!0===adsg_inf.config.nuggad)nuggtg=encodeURIComponent(n_default),nuggrid=top.location.href||0,adsf_addscriptnode("http://tofo.nuggad.net/rc?nuggn=575796532&nuggsid="+adsg_inf.config.nuggadid+"&nuggrid="+nuggrid+"&nuggtg="+nuggtg,function(){if(window.n_pbt&&""!=n_pbt){var a=readCookie("nuggSegs");null!=a&&""!=a?(eraseCookie("nuggSegs"),debout("Nugg.ad Cookie erased for next impression.")):createCookie("nuggSegs",
n_pbt.replace(";",","),30,"/")}})}function createNuggAdParamURLSection(){var a=readCookie("nuggSegs");if(null==a)debout("Could not find a Nugg.ad Cookie.");else if(""==a)debout("Nugg.ad Cookie found, but it did not contain any values.");else for(var a=a.split(","),b=0;b<a.length;b++)if(val=a[b].split("="),107==val[0].charCodeAt(0)||114==val[0].charCodeAt(0))adsc_nuggSegs=adsc_nuggSegs+val[0]+"="+val[1]+";",debout('Nugg.ad Cookie found. Added "'+val[0]+"="+val[1]+';" to adsc_nuggSegs.')}
function addASGatewayScriptNode(){!0==adsg_inf.config.adprobe.ap.state&&!0==adsg_inf.config.adprobe.as.state&&adsf_addscriptnode("http://js.revsci.net/gateway/gw.js?csid=L11279&auto=t")}
function createASParamURLSection(){asdfp=adsf_cookie("rsi_segs").split("|");for(var a=0;a<asdfp.length;a++)if(-1!=asdfp[a].indexOf("L11278_")&&(ada_adaval=asdfp[a].split("L11278_"),adsc_segQS=adsc_segQS+"kw=b"+ada_adaval[1]+";"),-1!=asdfp[a].indexOf("L11279_"))ada_adaval=asdfp[a].split("L11279_"),adsc_segQS=adsc_segQS+"kw=a"+ada_adaval[1]+";"}
function handleAdMessages(a){if(a.origin===adServerDomain||a.origin===sameDomain){var b=a.data.toString(),a=b.split(",")[0],c=b.split(",")[1],e=b.split(",")[2],d=b.split(",")[3],b=b.split(",")[4];debout('The postMessage event handler received information from the "'+a+'" slot that it contains a "'+c+'".');tfsads.site.adStates[a]=[c,e,d,b];try{window.tfsads[c].init()}catch(f){}}}
function addPostMessageEventListener(){window.addEventListener?window.addEventListener("message",handleAdMessages,!1):window.attachEvent("onmessage",handleAdMessages)}
var enableService={init:function(){window.addEventListener?window.addEventListener("load",enableService.debug,!1):window.attachEvent("onload",enableService.debug);for(var a=" "+window.location.search+"?",a=a.split("?")[1].split("&"),b=0;b<a.length;b++)if("tfm_console"===a[b]&&(adsg_inf.config.konsoledebug=!0),"tfm_debug"===a[b])adsg_inf.config.debuglayer=!0},debug:function(){!0===adsg_inf.config.debuglayer&&adDebug.start()}};
function debout(a){var b=(new Date).getTime(),b="0000"+(b-adsa_temptm),b=b.substr(b.length-4);if(adsg_inf.config.konsoledebug)try{console.log("["+b+"ms] TFM "+a)}catch(c){}0===a.indexOf("http://")&&adsg_reqarray.push([b,a]);adsg_dbgmsg=adsg_dbgmsg+a+"\n"}
function createCookie(a,b,c){if(c){var e=new Date;e.setTime(e.getTime()+6E4*c);c="; expires="+e.toGMTString()}else c="";document.cookie=a+"="+b+c+"; path=/";debout('Created a cookie named "'+a+'" with value "'+b+'" that expires on '+e.toLocaleString()+".")}
function readCookie(a){for(var b=a+"=",c=document.cookie.split(";"),e=0;e<c.length;e++)for(var d=c[e];" "==d.charAt(0);)if(d=d.substring(1,d.length),0==d.indexOf(b))return debout('Read a cookie named "'+a+'" with value "'+d.substring(b.length,d.length)+'".'),d.substring(b.length,d.length);return null}function eraseCookie(a){var b=new Date;b.setTime(b.getTime()+-6E4);b="; expires="+b.toGMTString();document.cookie=a+"="+b+"; path=/";debout('Erased a cookie named "'+a+'".')}
function determineSessionStates(){var a=readCookie(sessionCookieName);a?(userSession=parseInt(a),debout('User session count set to "'+userSession+'" from cookie.')):debout('No user session count cookie found. User session count set to "'+userSession+'".');for(a=0;a<=otpSetup.length;a++)otpSetup[a]==userSession&&(otpSession=!0);debout('The value of "otpSession" is set to "'+otpSession+'".');for(a=0;a<=dcoptSetup.length;a++)dcoptSetup[a]==userSession&&(dcoptSession=!0);debout('The value of "dcoptSession" is set to "'+
dcoptSession+'".');currentSession=userSession;otpException?otpSession&&debout("Session: No Over-the-page request allowed on this page. Delayed until the next page impression that allows it."):userSession+=1;createCookie(adsg_inf.config.site+"_session",userSession,30);otpSession&&!otpException?(adsc_cat="otp",c_otp="itp"):(adsc_cat="itp",c_otp="otp")}function writeOtpRequest(){otpSession&&!otpException&&document.write(ads_maketag("OTP","1","1","100","js"))}
function writeMeetricsBenchmarkRequest(){1==Math.floor(Math.random()*adsg_inf.config.meetricstrack+1)&&document.write(ads_gettag("BENCHMARK","12","12"))}function mozTargeting(){navigator.profile&&navigator.profile.getRules(function(a){for(var b=Object.keys(a).filter(function(b){return 0<a[b]}),c=0;c<b.length;c++)adsc_mozSegs+="kw=moz_"+b[c]+";"})}
var adDebug={adStatesArray:[],adInfoArray:[],adRequestArray:[],siteParamsArray:[],newSiteParamsArray:[],sessionInfoArray:[],infoFrame:null,createFrame:function(){var a=adDebug.infoFrame,a=document.createElement("div");a.id="tfm_infoframe";a.style.position="absolute";a.style.top="10px";a.style.left="10px";a.style.zIndex="1234567890";a.style.display="none";a.style.width="auto";a.style.height="auto";a.style.padding="10px 20px 20px 10px";a.style.backgroundColor="#eee";a.style.border="1px solid black";
a.style.fontSize="1em";a.style.overflow="hidden";a.style.resize="vertical";adDebug.infoFrame=a},addRow:function(a,b){for(var c="<tr ",c=-1!=b[1].indexOf("Request")?c+'style="background-color: #ccc;" ':c+'style="background-color: #ddd;" ',c=c+('id="tr_'+a+'">'),e=0;e<b.length;e++)c+="<td>"+b[e]+"</td>";return c+"</tr>"},collectSiteParams:function(){adDebug.siteParamsArray=[["tap",""],["site",window.adsc_dartsite],["ressort",window.adsc_ressort],["rubrik",window.adsc_rubrik],["layout",window.adsc_layout],
["keyword",window.adsc_keyword]]},collectNewSiteParams:function(){var a=window.adso_tagvars.get("tap").toString();-1!=a.indexOf("tfm_debug")&&(a=a.replace(/tfm_debug/,""));-1!=a.indexOf("tfm_console")&&(a=a.replace(/tfm_console/,""));adDebug.newSiteParamsArray=[["tap","<input type='text' size='50' maxlength='1000' value='"+a+"' readonly/>"],["adsc_site",window.adsc_dartsite],["adsc_ressort",window.adsc_ressort],["adsc_rubrik",window.adsc_rubrik],["adsc_layout",window.adsc_layout],["adsc_keyword",
window.adsc_keyword]];adDebug.sessionInfoArray=[["Session count",window.currentSession],["OTP session",window.otpSession],["OTP exception",window.otpException],["PopUp session",window.dcoptSession]]},collectAdStates:function(){var a=window.tfsads.site.adStates,b=Object.keys(a);adDebug.adStatesArray=[];for(var c=0;c<b.length;c++)adDebug.adStatesArray.push(["","PostMessage",b[c],"",a[b[c]][0],"","<a target='_blank' href='https://www.google.com/dfp/3673#delivery/OrderDetail/orderId="+a[b[c]][1]+"' title='Open this order in DFP'>"+
a[b[c]][1]+"</a>","<a target='_blank' href='https://www.google.com/dfp/3673#delivery/LineItemDetail/orderId="+a[b[c]][1]+"&lineItemId="+a[b[c]][2]+"' title='Open this line item in DFP'>"+a[b[c]][2]+"</a>","<a target='_blank' href='https://www.google.com/dfp/3673#delivery/PreviewCreative/orderId="+a[b[c]][1]+"&lineItemId="+a[b[c]][2]+"&creativeId="+a[b[c]][3]+"' title='Open this creative in DFP'>"+a[b[c]][3]+"</a>"])},collectAdInfo:function(){var a=window.adsg_adids;adDebug.adInfoArray=[];for(var b=
0;b<a.length;b++)adDebug.adInfoArray.push(["","AdInfo",a[b][0],"",a[b][5],a[b][1],"",a[b][2],a[b][3]])},collectAdRequests:function(){adDebug.adRequestArray=[];for(var a=0;a<adsg_reqarray.length;a++){for(var b=adsg_reqarray[a][0],c=adsg_reqarray[a][1],e=adsg_reqarray[a][1].split(";"),d="",f="",g="js url iframe lzfif dfif fif virtual".split(" "),h=0;h<e.length;h++)-1!=e[h].indexOf("sz=")&&(d=e[h].slice(3));for(h=0;h<e.length;h++)if(-1!=e[h].indexOf("!c="))for(var i=0;i<g.length;i++)-1!=e[h].indexOf(g[i])&&
(f=g[i]);e=encodeURIComponent(c.slice(0,c.indexOf(";")));e=e.replace(/de./,"");c=c.slice(c.indexOf(";"));adDebug.adRequestArray.push([b+"ms","Request",d,f,"<a href='javascript:adDebug.showUrl("+a+")' title='Show ad request URL'>Request URL </a>/<a target='_blank' href='https://www.google.com/dfp/3673#inventory/diagnostics/base_url="+e+c+"' title='Troubleshoot this ad in DFP'> TagShooter</a>","","","",""])}},buildInfo:function(){adDebug.collectAdStates();adDebug.collectAdRequests();adDebug.collectAdInfo();
var a=0,b=[],c=[],e=!1,d=0,f;f="<span style='font-size: 1.1em; font-weight: bold; float: left;'>TFM AdEngine Debug Layer</span><span style='cursor: pointer; margin-left: 10px; float: right;' onclick='adDebug.hide()'>[Close]</span><span style='cursor: pointer; margin-left: 10px; float: right;' onclick='adDebug.minMax()'>[Minimize]</span><span style='cursor: pointer; margin-left: 10px; float: right;' onclick='adDebug.buildInfo()'>[Update]</span><span style='cursor: pointer; margin-left: 10px; float: right;' onclick='adsf_sessionreset()'>[Reset Session]</span><span style='cursor: pointer; margin-left: 10px; float: right;' onclick='window.location.reload(true)'>[Reload]</span><div style='margin: 25px 0 5px; font-size: 1.1em; font-weight: bold;'>Alerts</div><table id='tfmdebug_alerts'>";
for(c=0;c<adDebug.adRequestArray.length;c++)"728x90"===adDebug.adRequestArray[c][2]&&(e=!0,d=c);if(!0===e){if(0!=d)for(c=0;c<=d;c++)"1x1"!=adDebug.adRequestArray[c][2]&&("12x12"!=adDebug.adRequestArray[c][2]&&"728x90"!=adDebug.adRequestArray[c][2])&&(f+="<tr style='color: red; font-weight: bold;'><td>728x90 is not the first ad request on this page!</td></tr>",a+=1)}else f+="<tr style='color: orange; font-weight: bold;'><td>There is no request for 728x90 on this page.</td></tr>",a+=1;for(c=0;c<adDebug.adRequestArray.length;c++)b.push(adDebug.adRequestArray[c][2]);
c=b.sort();for(b=0;b<c.length-1;b++)c[b+1]===c[b]&&(f+="<tr style='color: red; font-weight: bold;'><td>Duplicate AdSize "+c[b]+" found in ad requests!</td></tr>",a+=1);!0==adsg_inf.config.adprobe.ap.state&&!0==adsg_inf.config.adprobe.as.state&&-1===adDebug.adRequestArray[0][4].indexOf("kw=b10")&&(f+="<tr style='color: red; font-weight: bold;'><td>AudienceScience script found, but first request does not contain targeting parameters!</td></tr>",a+=1);0===a&&(f+="<tr style='color: gray; font-weight: bold;'><td>No Alerts.</td></tr>");
f+="</table><div style='margin: 10px 0 5px; font-size: 1.1em; font-weight: bold;'>Ad Information</div><table id='tfmdebug_adinfo' style='border-spacing: 2px;'><thead><tr><th>Time</th><th>Source</th><th>Size</th><th>Type</th><th>Description</th><th>Advertiser</th><th>Order</th><th>Ad</th><th>Creative</th></tr></thead>";for(c=0;c<adDebug.adRequestArray.length;c++){f+=adDebug.addRow(c,adDebug.adRequestArray[c]);f+="<tr style='padding: 0px;'><td colspan='9' style='padding: 0px;'><textarea id='tfmreq_"+
c+"' style='width: 100%; resize: vertical; display: none;'>"+adsg_reqarray[c][1].toString()+"</textarea></td></tr>";for(b=0;b<adDebug.adStatesArray.length;b++)-1!=adDebug.adRequestArray[c][2].indexOf(adDebug.adStatesArray[b][2])&&(f+=adDebug.addRow(c,adDebug.adStatesArray[b]));for(a=0;a<adDebug.adInfoArray.length;a++)-1!=adDebug.adRequestArray[c][2].indexOf(adDebug.adInfoArray[a][2])&&""!=adDebug.adInfoArray[a][2]&&(f+=adDebug.addRow(c,adDebug.adInfoArray[a]))}f+="</table><div style='margin: 10px 0 5px; font-size: 1.1em; font-weight: bold;'>Site Parameters</div><table id='tfmdebug_siteparams' ><thead><tr><th>Parameter</th><th>Original</th><th>Modified</th></thead>";
for(c=0;c<adDebug.siteParamsArray.length;c++)f+="<tr><td>"+adDebug.siteParamsArray[c][0]+"</td><td>"+adDebug.siteParamsArray[c][1]+"</td><td>"+adDebug.newSiteParamsArray[c][1]+"</td></tr>";f+="</table><div style='margin: 10px 0 5px; font-size: 1.1em; font-weight: bold;'>Session Parameters</div><table id='tfmdebug_sessionparams' ><thead><tr><th>Parameter</th><th>Value</th></thead>";for(c=0;c<adDebug.sessionInfoArray.length;c++)f+="<tr><td>"+adDebug.sessionInfoArray[c][0]+"</td><td>"+adDebug.sessionInfoArray[c][1]+
"</td></tr>";document.getElementById("tfm_infoframe").innerHTML=f+"</table>";document.getElementById("tfm_infoframe").style.display="block"},start:function(){var a=document.getElementById("tfm_infoframe");a?a.style.display="block":(adDebug.createFrame(),document.getElementsByTagName("body")[0].insertBefore(adDebug.infoFrame,document.getElementsByTagName("body")[0].firstChild));adDebug.buildInfo()},minMax:function(){var a=document.getElementById("tfm_infoframe");a.style.height="5px"<a.style.height?
"5px":"auto"},hide:function(){document.getElementById("tfm_infoframe").style.display="none"},showUrl:function(a){"none"===document.getElementById("tfmreq_"+a).style.display?document.getElementById("tfmreq_"+a).style.display="block":document.getElementById("tfmreq_"+a).style.display="none"}};
function startEngine(){enableService.init();debout("Initialisierung der AdEngine "+adsg_inf.major+"."+adsg_inf.minor+"."+adsg_inf.git_commit+" beginnt.");addPostMessageEventListener();mergeAdProbeUnitArrays();adDebug.collectSiteParams();adsf_import([window,"adsc","ressort,sonstiges","rubrik,sonstiges","topchannel","channel","subchannel","tile,0","click_adrenew,5","keyword,none","layout,none","sadpercent","cadpercent","skyscraperpercent","contentwidth,"+adsg_inf.config.contentwidth,"banerleistewidth,"+
adsg_inf.config.contentwidth,"skyscraperposx,"+adsg_inf.config.contentwidth,"bannerposx,0","bannerposy,0","bannerheight,90","bgc_typ,color_hex","node_name,0","plz,none","age,none","gender,none"]);tfsads.specialConfig.init();determineSessionStates();mozTargeting();addAdProbeScriptNode();createAdProbeParamURLSection();addNuggAdScriptNode();createNuggAdParamURLSection();addASGatewayScriptNode();createASParamURLSection();TFM.Mapping.Configuration&&void 0!=TFM.Mapping.Configuration[0]&&(adso_map=TFM.Mapping.Configuration);
adso_mapread([adsc_ressort,adsc_rubrik,adsc_subchannel]);var a=adso_tagvars;a.set("site",adsg_inf.config.site);a.set("sz","1x1");a.set("!c","bl_"+adsg_inf.config.site);a.add("!c",c_otp);a.set("cat",adsc_cat);a.set("tfs_usr",currentSession);a.set("tile","0");a.set("lay",adsc_layout);a.set("res",adsc_ressort);a.set("topchannel",adsc_topchannel);a.set("channel",adsc_channel);a.set("subchannel",adsc_subchannel);a.set("rub",adsc_rubrik);a.set("c2d",tfsbase.mediasupport().canvas2d);a.set("wgl",tfsbase.mediasupport().webgl);
a.set("tfww",function(){var a,c=tfsbase.winprop().cw,e="";for(a=7;a<=19;a++)c>=a*100&&(e=e+a);return e}());a.addcsv("kw",adsg_getvars.adkeyword);a.addcsv("kw",adsg_getvars.showroom);a.addcsv("kw",adsg_getvars.ref_adkeyword);a.set("tap",adsf_ssan(("  "+document.location).replace(/[#?=\-,.]/g,"/").replace(/\/\//g,"").replace(adsc_location.split("/")[0],"")));a.set("ord",Math.round(89462581*Math.random()));tfsads.specialTagvars.init();adsf_getSetVideoProps();adsf_getSetMobileProps();adsf_getSetAdExclConfig();
adsf_getSetCookieKeyword();debout("Tag variables have been computed for this page impression.");adDebug.collectNewSiteParams();writeMeetricsBenchmarkRequest();writeOtpRequest();debout("Initialisierung der AdEngine "+adsg_inf.major+"."+adsg_inf.minor+"."+adsg_inf.git_commit+" abgeschlossen.")}
var TFM={Mapping:{Configuration:{}}},adsg_inf={major:4,minor:1,git_commit:0,file:"js_ng_chip_0420.js",path:"http://a.tfag.de/js_ng/",modified:{year:2013,month:1,day:11},client:{ismobile:!1,swf:0,swfminv:4,swfmaxv:12,cw:833},config:{site:"chip",contentwidth:833,adsenseid:0,adsensefvid:0,adplayer:!1,istslot:1,fifurl:"fif.html",wunderloop:!1,nuggad:!0,nuggadid:"718543823",adprobe:{ap:{state:!0,maxseg:50},pg:{state:!1,pubid:1539,siteid:6159,firstunit:10638,unitsarray:[10638,10639,10640,12711]},as:{state:!0,
pubid:1615,siteid:6504,firstunit:12508,itp_unitsarray:[12508,12509,12510,12511,12515],otp_unitsarray:[12508,12509,12510,12511,12512,12513,12514,12515,12516,12554,15555,12556,12974,12975,12976]}},fif:!0,pap:!1,debuglayer:!1,konsoledebug:!1,video:!1,companiondelay:1,meetricstrack:6,video:{flowplayer:!0,ima_sdkver:1,use_gpt:!1}}},adsc_cat="itp",adsc_tile=0,adsc_dartsite="sonstiges",adsc_segQS="",adsc_nuggSegs="",adsc_apSegs="",adsc_mozSegs="",adsg_reqarray=[],sameDomain=location.protocol+"//"+document.domain,
adServerDomain="http://ad.de.doubleclick.net",otpSetup=[1,3,5],dcoptSetup=[2],otpException=!1,otpSession=!1,dcoptSession=!1,userSession=1,currentSession=1,sessionCookieName=adsg_inf.config.site+"_session",adsg_dbgmsg,adsg_site=adsg_inf.config.site,n_pbt="",n_default="test",adsg_istsession=[0,1,0,1,0,1,0,0,0,0],adsc_adid1,adsc_adid2,adsc_adid4,adsc_adid6,category="",adsg_locusr=1,otp_typ=0,c_otp_typ=0,dcopt_ist,adsg_katprozent=[0,100,100,100,0,100,100,100,100,100,0,100,100,100,100,100,100,100],adsg_vslots=
{19:"tfsads.billboardadWrite();"},adsg_size=["",dcopt_ist,"","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","","",""],adsg_size_slot=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],adsg_katval=["00","BANNER","CONTENTAD","CONTENTBOX","4","OTP","SKYSCRAPER","CONTENTAD2","PROMOBOX","CONTENTAD3","TEXTLINK","11","COUNT","ITP","PREROLL","MIDROLL","POSTROLL","VIDEOLAYER","HALFRECTANGLE","BILLBOARDAD","BANNER2","BANNER3","FOOTERAD","23","24",
"CONTENTAD4","CONTENTAD5","CONTENTAD6","CONTENTAD7","MAXIAD",30,"BENCHMARK"],adsg_tagsizeoverride=[0,1,2,3,4,5,"sz=1x2,160x600",7,8,9,10,11,12,13,"sz=4x5;dcmt=text/xml","sz=4x6;dcmt=text/xml","sz=4x7;dcmt=text/xml","sz=4x8;dcmt=text/xml",18,19,"sz=728x91,770x90","sz=728x92",22,23,24,25,26,27,28,29,30,"sz=12x12"],adsg_exclusionval=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,"kw=meetrics_benchmark"],adsc_isegm="",adsa_isegm="",adsc_location=adsf_ssan(" "+document.location),
adsg_params=window.location.search,adsc_transid=Math.round(9999999*Math.random()),adsg_google_adskip=0,adsc_fiftemplate='<html><head></head><body style="margin-left:0px; background-color:#FFFFFF;">\r\n<div id="fifdiv" style="position:absolute; top:0px;left:0px;">\r\n<script>\r\nvar myid="##myid##",countoff=0;\r\nvar adsg_adids=[];\r\nadsg_adids[adsg_adids.length]=["0000000","0000000","000000000","00000000",new Date().getTime() ,"dfif_"+myid,"dbg","dbg"]; \r\ndocument.write(\'<scr\'+\'ipt src="##tag##"></scr\'+\'ipt>\');\r\nsetTimeout(function checkdivsz(){\r\nframeElement.style.height=0;if(document.body && document.body.scrollHeight && typeof(frameElement) != \'undefined\'){frameElement.style.height =(document.body.scrollHeight)+\'px\';frameElement.style.margin=\'0 auto\';top.document.getElementById(myid).style.height=frameElement.style.height;\nif(frameElement.style.height){\n try{top.document.getElementById(myid).style.height=frameElement.style.height+"px";top.document.getElementById(myid).height=frameElement.style.height;}catch(er){}try{window.parent.document.getElementById(myid).style.height=frameElement.style.height+"px";}catch(er){}}};\r\nif(countoff<=30){countoff++;try{window.parent.debout(\'ctf:\'+countoff);}catch(w){};setTimeout(checkdivsz,200);}\r\n},200);\r\nsetTimeout(top.tfsads.mediumrectangle.init,4000);\r\nsetTimeout(function(){ /*adinfo syncen*/\r\nif(top.adsg_adids && top.adsg_adids!==adsg_adids){\r\nif(adsg_adids&&typeof adsg_adids=="object"){\r\nfor(var i=0;i<adsg_adids.length;i++){\r\ntop.adsg_adids[top.adsg_adids.length]=adsg_adids[i];\r\n}}}},2000);\r\n<\/script>\r\n</div>\r\n</body>\r\n</html>',
adso_response={conf:{"default":["adj","js"],pfxml:["pfadx","url"],xml:["adx","url"],pfjs:["pfadj","js"],html:["adi","iframe"],lzhtml:["adj","lzfif"],dihtml:["adj","dfif"],htmlurl:["adi","url"],js:["adj","js"],jsurl:["adj","url"],fif:["adj","fif"],pffif:["pfadj","fif"],jsurl:["adj","url"],vjs:["none","virtual"],none:["none","none"]}},adsg_rconf={"770x250":"lzhtml"},tfsads={site:{supressContentAdTop:!1,supressContentAdSidebar:!0,wallpaper:!1,adStates:{},adMessageHandlingEnabled:!0},api:{getAdSlotAdType:function(a){return tfsads.site.adStates[a][0]},
getAdSlotOrderId:function(a){return tfsads.site.adStates[a][1]},getAdSlotLineItemId:function(a){return tfsads.site.adStates[a][2]},getAdSlotCreativeId:function(a){return tfsads.site.adStates[a][3]}},specialConfig:{init:function(){adsf_import([window,"adsc","sw","abtest","brand","product","filler_1x1,false","filler_728x90,false","filler_300x250,false","filler_160x600,false"]);adsc_document_uri+="///";var a=adsc_document_uri.split("/");"1"==adsc_ressort?(adsc_topchannel="homepage",adsc_channel="frontpage",
adsc_subchannel=""):(adsc_topchannel=""!=a[1]?a[1]:"",adsc_channel=""!=a[2]?a[2]:"",adsc_subchannel=""!=a[3]?a[3]:"");adsc_ressort=adsc_topchannel;adsc_rubrik=adsc_channel;adsc_ressort=adsc_ressort.replace("-","_");adsc_ressort=adsc_ressort.replace("-","_");a=window.location.search;a=a.substring(1,a.length);dc_querry_string_array=a.split("&");for(adsc_i=0;adsc_i<dc_querry_string_array.length;adsc_i++)switch(dc_url_var=dc_querry_string_array[adsc_i].split("="),dc_url_var[0]){case "jahr":adsc_channel=
dc_url_var[1]}"test_kaufberatung"==adsc_topchannel&&""==adsc_channel&&(adsc_rubrik=adsc_channel="frontpage");"handy"==adsc_topchannel&&""==adsc_channel&&(adsc_rubrik=adsc_channel="frontpage");"news"==adsc_topchannel&&""==adsc_channel&&(adsc_rubrik=adsc_channel="frontpage");"bestenlisten"==adsc_topchannel&&""==adsc_channel&&(adsc_rubrik=adsc_channel="frontpage");"business"==adsc_topchannel&&""==adsc_channel&&(adsc_rubrik=adsc_channel="frontpage");"tipps_tools"==adsc_topchannel&&""==adsc_channel&&(adsc_rubrik=
adsc_channel="frontpage");"downloads"==adsc_topchannel&&""==adsc_channel&&(adsc_rubrik=adsc_channel="frontpage");"chip_forum"==adsc_topchannel&&"0_none"==adsc_channel&&(adsc_rubrik=adsc_channel="frontpage");adsc_contentwidth&&(tfsads.wallpaper.positionX=parseInt(adsc_contentwidth))}},specialTagvars:{init:function(){adso_tagvars.set("uri",adsc_document_uri);adso_tagvars.set("abtest",adsc_abtest);adso_tagvars.set("brand",adsc_brand);adso_tagvars.set("sw",adsc_sw);adso_tagvars.set("product",adsc_product)}},
universal:{setBackgroundColor:function(a){var b=document.getElementsByTagName("body")[0];"#"!=a.substring(0,1)&&(a="#"+a);!1===/^(#)?([0-9a-fA-F]{3})([0-9a-fA-F]{3})?$/.test(a)?debout("HexCode for Background Color is invalid: "+a):(b.style.backgroundImage="url()",b.style.backgroundColor=a)},setBackgroundImage:function(a,b,c,e){b=document.getElementsByTagName("body")[0];b.style.backgroundImage="url("+a+")";b.style.backgroundRepeat="repeat";b.style.backgroundPosition=c+"px "+e+"px"},stickyLooper:function(){if(document.getElementById("stickyAnchor")){var a=
document.getElementById("stickyAnchor").parentNode,b=tfsbase.winprop(),c=document.getElementById("stickySkyAd");if(!window.stickyskyload){window.stickyskyload=!0;window.stickyAnchor=document.getElementById("stickyAnchor").parentNode;for(var e=a.getElementsByTagName("script"),d=0;d<e.length;d++)if(e[d])try{e[d].parentNode.removeChild(e[d])}catch(f){debout("Fehlol: 0x00332f4")}for(;a.firstChild;)c.appendChild(a.firstChild);a.appendChild(c)}a=tfsbase.obpos(window.stickyAnchor);!0==b.pf?(c.style.position=
"fixed",c.style.top=a.y>=b.st?a.y-b.st+"px":"0px"):(c.style.position="absolute",c.style.top=b.st+"px")}setTimeout(tfsads.universal.stickyLooper,10)},stickySkyscraper:function(){var a=1;window.tfsads&&(tfsads.skyscraper&&0==tfsads.skyscraper.sticky)&&(a=0);1===a&&(window.adsg_site&&"meinestadt"!=adsg_site)&&(document.write('<div id="stickyAnchor"></div>'),a=document.createElement("div"),a.style.position="absolute",a.id="stickySkyAd",document.getElementsByTagName("body")[0].insertBefore(a,document.getElementsByTagName("body")[0].firstChild),
-1!=navigator.userAgent.indexOf("MSIE")?document.onreadystatechange=function(){var a=document.getElementById("stickyAnchor").parentNode;if("complete"==a.readyState||"loaded"==a.readyState)(!window.stickyskyload||!0!=window.stickyskyload)&&setTimeout(tfsads.universal.stickyLooper,950)}:setTimeout(tfsads.universal.stickyLooper,900))}},banderole:{init:function(){}},billboard:{placementMode:"banner",init:function(){}},billboardad:"",billboardadWrite:function(){if(tfsads.billboardad&&"function"==typeof tfsads.billboardad){var a=
window.tfsads.billboardad();a[0]&&""!=a[0]&&(document.getElementById("adsd_billboard_div").style.display="block",document.write(a[0]))}},billboardadInit:function(a,b,c,e,d){a=document.getElementById("adsd_billboard_div");d?document.getElementById("adsd_billboard_div").style.backgroundColor=d:document.getElementById("adsd_billboard_div").style.backgroundColor="#D5E3F0";a.style.height="";e&&(a.style.marginLeft=!0===e?Math.floor((adsg_inf.config.contentwidth-b)/2)+"px":e+"px");a.style.marginBottom="0px"},
blocker:{init:function(){}},bracketad:{init:function(){}},centerfold:{init:function(){}},countdownad:{init:function(){}},filler:{init:function(){}},flashlayer:{init:function(){}},floorad:{init:function(){}},footerad:{init:function(){}},footeradyield:{init:function(){}},framead:{positionX:833,positionY:0,platzhalterH:90,init:function(){}},frameadplus:{positionX:833,positionY:0,platzhalterH:90,init:function(){}},fullscreenlayer:{positionX:0,positionY:0,platzhalterH:90,init:function(){}},fullscreenspot:{positionX:0,
positionY:0,platzhalterH:90,init:function(){}},galerie:{maxwidth:300,maxheight:250,init:function(){}},halfrectangle:{init:function(){}},halfpagead:{init:function(){}},interstitial:{init:function(){}},layer:{adtype:"undefined",init:function(){}},mafolayer:{init:function(){}},mediumrectangle:{adtype:"undefined",init:function(){debout("tfsads.mediumrectangle.init has run.")}},motionwallpaper:{positionX:833,positionY:0,platzhalterH:90,init:function(){}},panoramaad:{positionX:0,positionY:0,platzhalterH:90,
yoffset:0,init:function(a,b){tfsads.site.wallpaper=!0;tfsads.site.supressContentAdTop=!0;a!=b&&(tfsads.panoramaad.yoffset=a+2);try{document.getElementById("adsc_sidebar").style.paddingTop=tfsads.panoramaad.yoffset+"px"}catch(c){setTimeout("tfsads.panoramaad.init("+a+")",1E3)}}},panoramaadxl:{positionX:494,positionY:0,platzhalterH:90,init:function(){tfss_swp(600)}},peeldownad:{init:function(){}},pinad:{init:function(){}},popup:{init:function(){}},pushdownad:{init:function(){}},shortclip:{init:function(){}},
sidekick:{init:function(){}},sitebar:{params:function(){return site={left:"",center:adsg_inf.config.contentwidth-160+"",top:"90"}},init:function(){}},skyscraper:{adtype:"undefined",sticky:1,init:function(){}},superbanner:{adtype:"undefined",init:function(){}},textlink:{init:function(){}},wallpaper:{positionX:833,positionY:0,platzhalterH:90,init:function(a,b){void 0!=typeof b&&(document.getElementsByTagName("body")[0].style.backgroundColor=b)},setColor:function(a){document.getElementsByTagName("body")[0].style.backgroundColor=
a},setBgImg:function(a){document.getElementsByTagName("body")[0].style.backgroundImage=a}}},adso_map={sonstiges:["sonstiges","sonstiges",[0,0],{}],homepage:["1","homepage_frontpage",[0,0],{}],archiv:["33105","archiv_sonstiges",[0,0],{"":["","archiv_frontpage",[0,0],{}]}],bestenlisten:["bestenlisten","sonstiges",[0,0],{frontpage:["","frontpage",[0,0],{}],sonstiges:["","sonstiges",[0,0],{}]}],bildergalerien:["27633","bildergalerie_sonstiges",[0,0],{frontpage:["","bildergalerie_frontpage",[0,0],{}],
business:["","bildergalerie_business",[0,0],{}],gadgets:["","bildergalerie_gadgets",[0,0],{}],handy:["","bildergalerie_handy",[0,0],{}],hardware:["","bildergalerie_hardware",[0,0],{}],hersteller:["","bildergalerie_hersteller_videos",[0,0],{}],home_entertainment:["","bildergalerie_home_entertainment",[0,0],{}],kameras:["","bildergalerie_kameras",[0,0],{}],praxistipps:["","bildergalerie_praxistipps",[0,0],{}],serien:["","bildergalerie_serien",[0,0],{}],spiele:["","bildergalerie_spiele",[0,0],{}],tablets:["",
"bildergalerie_tablets",[0,0],{}],tests:["","bildergalerie_tests",[0,0],{}],toys_for_boys:["","bildergalerie_toys_for_boys",[0,0],{}],videos_trailer:["","bildergalerie_videos_trailer",[0,0],{}],exitpages:["27634","bildergalerie_exitpage",[0,0],{}],sonstiges:["","bildergalerie_sonstiges",[0,0],{}]}],business:["business","business_sonstiges",[0,0],{frontpage:["","business_frontpage",[0,0],{}],admin:["","business_admin",[0,0],{}],blog:["","business_blog",[0,0],{}],hardware:["","business_hardware",[0,
0],{}],mittelstand:["","business_mittelstand",[0,0],{}],news:["","business_news",[0,0],{}],rest:["","business_rest",[0,0],{}]}],dsl_internet:["19506","dsl_internet_sonstiges",[0,0],{frontpage:["","dsl_internet_",[0,0],{}],dsl_anwendungen:["","dsl_internet_dsl_anwendungen",[0,0],{}],dsl_tarife_provider:["","dsl_internet_dsl_tarife_provider",[0,0],{}],netzwerke_wlan:["","dsl_internet_netzwerke_wlan",[0,0],{}],wlan_drahtlos_surfen:["","dsl_internet_wlan_drahtlos_surfen",[0,0],{}],sonstiges:["","dsl_internet_sonstiges",
[0,0],{}]}],downloads:["9232","downloads_sonstiges",[0,0],{frontpage:["","downloads_frontpage",[0,0],{}],sonstiges:["","downloads_sonstiges",[0,0],{}]}],chip_forum:["9231","community_forum",[0,0],{frontpage:["","community_frontpage",[0,0],{}],dsl_anwendungen:["","dsl_internet_dsl_anwendungen",[0,0],{}],dsl_tarife_provider:["","dsl_internet_dsl_tarife_provider",[0,0],{}],netzwerke_wlan:["","dsl_internet_netzwerke_wlan",[0,0],{}],wlan_drahtlos_surfen:["","dsl_internet_wlan_drahtlos_surfen",[0,0],{}],
sonstiges:["","dsl_internet_sonstiges",[0,0],{}]}],news:["9226","news_sonstiges",[0,0],{frontpage:["","news_frontpage",[0,0],{}],aktuelle_schnaeppchen:["","news_aktuelle_schnaeppchen",[0,0],{}],hardware:["","news_hardware_software",[0,0],{}],hardware_software:["","news_hardware_software",[0,0],{}],internet_dsl:["","news_internet_dsl",[0,0],{}],panorama:["","news_panorama",[0,0],{}],software:["","news_software",[0,0],{}],rest:["","news_rest",[0,0],{}]}],preisvergleich:["26784","preisvergleich_sonstiges",
[0,0],{frontpage:["","downloads_frontpage",[0,0],{}],sonstiges:["","downloads_sonstiges",[0,0],{}]}],tipps_tools:["9229","tipps_tools_sonstiges",[0,0],{frontpage:["","tipps_tools_frontpage",[0,0],{}],brennen_dvd:["","tipps_tools_brennen_dvd",[0,0],{}],foto_video:["","tipps_tools_foto_video",[0,0],{}],hardware_tuning_treiber:["","tipps_tools_hardware_tuning_treiber",[0,0],{}],mp3_sound:["","tipps_tools_mp3_sound",[0,0],{}],office_geld:["","tipps_tools_office_geld",[0,0],{}],web_filesharing:["","tipps_tools_web_filesharing",
[0,0],{}],windows_tools:["","tipps_tools_windows_tools",[0,0],{}],sicherheit_viren:["26113","tipps_tools_sicherheit_viren",[0,0],{}],sicherheit_viren:["26113","tipps_tools",[0,0],{"0_security_blog":["","0_security_blog",[0,0],{}],datensicherheit:["","datensicherheit",[0,0],{}],news_virenalarm:["news_virenalarm","",[0,0],{}],security_downloads:["","security_downloads",[0,0],{}],sicherheit_im_test:["","sicherheit_im_test",[0,0],{}],sicherheit_viren:["","sicherheit_viren",[0,0],{}],tipps_tricks_sicher_surfen:["",
"tipps_tricks_sicher_surfen",[0,0],{}]}],sonstiges:["","tipps_tools_sonstiges",[0,0],{}]}],test_kaufberatung:["9227","test_kaufberatung_sonstiges",[0,0],{frontpage:["","test_kaufberatung_frontpage",[0,0],{}],aktuelle_hardware_tests:["","test_kaufberatung_aktuelle_hardware_tests",[0,0],{}],bestenlisten:["","test_kaufberatung_bestenlisten",[0,0],{}],brenner_festplatte:["43741","test_kaufberatung_brenner_festplatte",[0,0],{}],camcorder:["43748","test_kaufberatung_camcorder",[0,0],{}],digitalkamera:["43744",
"test_kaufberatung_digitalkamera",[0,0],{}],drucker_scanner:["43736","test_kaufberatung_drucker_scanner",[0,0],{}],handy_smartphone:["43746","test_kaufberatung_smartphone",[0,0],{}],home_entertainment:["39535","test_kaufberatung_home_entertainment",[0,0],{}],meinungen:["","test_kaufberatung_meinungen",[0,0],{}],mp3_player:["39535","test_kaufberatung_mp3_player",[0,0],{}],navigation:["20827","test_kaufberatung_navigation",[0,0],{}],notebook:["14933","test_kaufberatung_notebook",[0,0],{}],pc_hardware:["39536",
"test_kaufberatung_pc_hardware",[0,0],{}],schnaeppchen_tipps_der_redaktion:["","test_kaufberatung_schnaeppchen_tipps_der_redaktion",[0,0],{}],software:["21013","test_kaufberatung_software",[0,0],{}],spiele:["9228","test_kaufberatung_spiele",[0,0],{}],tft_displays:["14945","test_kaufberatung_tft_monitor",[0,0],{}],tft_monitor:["14945","test_kaufberatung_tft_monitor",[0,0],{}],tablet_pc:["64445","test_kaufberatung_tablet_pc",[0,0],{}],sonstiges:["","test_kaufberatung_sonstiges",[0,0],{}]}],handy:["handy_news",
"sonstiges",[0,0],{frontpage:["handy_index","frontpage",[0,0],{}],aktuelle_hardware_tests:["","test_kaufberatung_aktuelle_hardware_tests",[0,0],{}],bestenlisten:["","test_kaufberatung_bestenlisten",[0,0],{}],camcorder:["","test_kaufberatung_camcorder",[0,0],{}],digitalkamera:["","test_kaufberatung_digitalkamera",[0,0],{}],meinungen:["","test_kaufberatung_meinungen",[0,0],{}],notebook:["","test_kaufberatung_notebook",[0,0],{}],schnaeppchen_tipps_der_redaktion:["","test_kaufberatung_schnaeppchen_tipps_der_redaktion",
[0,0],{}],tft_displays:["","test_kaufberatung_tft_displays",[0,0],{}],rest:["","test_kaufberatung_rest",[0,0],{}]}],video:["30593","videos_sonstiges",[0,0],{frontpage:["","videos_frontpage",[0,0],{}],business:["","videos_business",[0,0],{}],gadgets:["","videos_gadgets",[0,0],{}],handy:["","videos_handy",[0,0],{}],hardware:["","videos_hardware",[0,0],{}],hersteller_videos:["","videos_hersteller_videos",[0,0],{}],home_entertainment:["","videos_home_entertainment",[0,0],{}],kameras:["","videos_kameras",
[0,0],{}],praxistipps:["","videos_praxistipps",[0,0],{}],serien:["","videos_serien",[0,0],{}],spiele:["","videos_spiele",[0,0],{}],tablets:["","videos_tablets",[0,0],{}],tests:["","videos_tests",[0,0],{}],toys_for_boys:["","videos_toys_for_boys",[0,0],{}],videos_trailer:["","videos_videos_trailer",[0,0],{}],sonstiges:["","videos_sonstiges",[0,0],{}]}],20385:["20385","suchergebnisse",[0,0],{}],sonstiges:["sonstiges","sonstiges",[0,0],{}]};startEngine();
adsg_adids[adsg_adids.length]=["0000000","0000000","000000000","00000000",adsa_temptm,"AdScript END"];