var m=null;
(function(){function K(){w=f.mr_isIncomplete||false;s={};s.lead=f.mr_trackUnreferredLeadConversions!=0;s.order=f.mr_trackUnreferredOrderConversions!=0;s.shopper=f.mr_trackUnreferredShopperConversions!=0;if(!L||n!==f.location){n=f.location;var a=n.protocol,c=(a=="http:"?"http:":"https:")+"//link.mercent.com/";C=f.mr_cookieDomain;D=f.mr_cookiePath||"/";var b=void 0;if(b==m)b=x.cookie;if(b){b=b.split(/\s*;\s*/);for(var d={},e=0;e<b.length;e++){var g=b[e].split("=",2);d[g[0]]=g.length>
1?g[1]:m}t=d}else t={};o=new Date;o.setFullYear(o.getFullYear()+3);E=Boolean(a=="http:"||a=="https:");F=f.mr_merchantID||"";a=void 0;if(a==m)a=n.search.substring(1);a=a.split("&");b={};if(d=f.mr_GetQuerystringValue){b["mr:ad"]=d("mr:ad");b["mr:referralID"]=d("mr:referralID");b["mr:trackingCode"]=d("mr:trackingCode")}else for(d=0;d<a.length;d++){e=a[d].split("=",2);b[G(e[0])]=e.length>1?G(e[1]):m}y=b;p=f.mr_SetCookieValue||p;M=H();z=c+"image.ashx";N=c+"redirect.ashx";L=true}}function A(a){var c="",
b=a.hasOwnProperty;if(a)for(var d in a)if(!b||b.call(a,d)){var e=a[d];if(e!=m&&String(e)!=""){if(c!="")c+="&";c=c+d+"="+escape(e)}}return c}function B(a){var c=new Image(1,1);W.push(c);c.src=a;c.onload=function(){}}function h(a){var c;if(typeof a=="number")c=a;else{a=O(a);c=P(a);if(isNaN(c))return a}a=Math.round(c*1E4);c=a/1E4;return a%100==0&&c.toFixed?c.toFixed(2):c.toString()}function Q(){var a=new Date;return A({"br:referer":x.referrer,"br:pageUrl":n.pathname,"br:dateTime":a.getFullYear()+"-"+
u(a.getMonth())+"-"+u(a.getDate())+"T"+u(a.getHours())+":"+u(a.getMinutes())+":"+u(a.getSeconds())})}function I(){if(q==m){q=t[R];if(q==m)q=H();p(R,q,o)}return A({"mr:merchantID":F,"mr:referralID":v,"mr:ticketID":q,"mr:batchID":M})}function H(){var a,c="",b="",d="",e=history,g=f.screen,j=n.href;a=j.slice(-32);var k=j.length-32;j="";for(var l=0;l<k;l++)a+="F";for(l=0;l<a.length;l++){k=a.charAt(l).toUpperCase();j+=k>="A"&&k<="F"?k:a.charCodeAt(l).toString().slice(-1)}a=j;if(g&&g.colorDepth)c=g.colorDepth.toString();
if(e&&e.length)b=e.length.toString();for(e=0;e<32;e++){g=Math.floor(Math.random()*15);j=J(a.charAt(e),16);if(b.length>e)g^=J(b.charAt(e),16);if(c.length>e)g^=J(c.charAt(e),16);d+=(g^j).toString(16);if(e==7||e==11||e==15||e==19)d+="-"}return d}function u(a){return(a<0||a>9?"":"0")+a}function O(a){if(typeof a!="string")return a;return a.replace(/(\,|\s|\$)+/g,"")}function S(a){if(typeof a!="string")return a;for(var c=0,b=a.length;a.charAt(c)==" "&&c<b;)c++;for(;a.charAt(b-1)==" "&&b>c;)b--;return a.substring(c,
b)}var q,W=[],L=false,R="mr_domainUserTicketID",r=[],v="",p,T=false,U="",C,D,t,o,w,E,F,y,M,z,N,s,x=document,f=window,n=f.location,P=parseFloat,J=parseInt,V=encodeURIComponent,G=decodeURIComponent;f.mr_conv=[];f.mr_convOrderItem=[];f.mr_Track=function(){try{K();if(!(!E||T)){U=y["mr:trackingCode"];var a=Boolean(U||y["mr:ad"]),c=a,b;if(a){v=H();var d=n.href;a={};a[0]=d.substring(0,d.indexOf("?"));a[1]=d.substring(d.indexOf("?")+1);var e=a[0],g=a[1].split("#",2),j=g.length>1?g[1]:"",k=g[0].split("&");
d="?";g="";for(a=0;a<k.length;a++)switch(G(k[a].split("=")[0]).toLowerCase()){case "mr:trackingcode":case "gantrackingid":case "mr:adgroup":case "mr:ad":case "mr:keyword":case "mr:placement":case "mr:match":g+="&"+k[a];break;default:e+=d+k[a];if(d=="?")d="&"}if(j)e+="#"+j;var l=V(e),X=V(x.referrer);B(N+"?mr:referralID="+v+"&mr:merchantID="+F+g+"&mr:targetUrl="+l+"&br:referer="+X)}else{v=y["mr:referralID"];c=Boolean(v)}if(c){b=1;p("mr_referredVisitor",b,o);var Y=z+"?"+I()+"&"+Q();B(Y)}else{b=t.mr_referredVisitor;
if(b!=1){b=0;p("mr_referredVisitor",b,o)}}T=true}}catch(Z){}};f.mr_addConvOrderItem=function(){var a=f.mr_convOrderItem;f.mr_convOrderItem=[];if(a){var c=S(a.sku),b=S(a.qty),d=h(a.extPrice);if(!(!(c&&b&&d)||isNaN(b)||isNaN(d))){a.sku=c;a.qty=b;a.extPrice=d;r.push(a)}}};f.mr_sendConversion=function(){K();if(E){var a=f.mr_conv,c=a.type,b={};if(!(c!="shopper"&&c!="lead"&&c!="order"))if(!((t.mr_referredVisitor||0)!=1&&!s[c])){var d="";if(c=="lead")b["c:amount"]=h(a.amount);else if(c=="order"){var e=P(O(a.discount));
if(isNaN(e))e=0;else if(e>0)e*=-1;b["c:amount"]=h(a.amount);b["c:shipping"]=h(a.shipping);b["c:tax"]=h(a.tax);b["c:discount"]=h(e);b["c:postalCode"]=a.postalCode;b["c:countryCode"]=a.countryCode;b["c:itemCount"]=r.length;b["c:isIncomplete"]=w}b["c:type"]=c;b["c:id"]=a.id;b["c:customerId"]=a.customerId;d=A(b);b=z+"?"+I()+"&"+Q()+"&"+d;B(b);if(r)for(i=0;i<r.length;i++){d=r[i];b={};b["c:type"]=c;b["c:id"]=a.id||"";b["ci:sku"]=d.sku;b["ci:title"]=d.title||"";b["ci:url"]=d.url||"";b["ci:qty"]=d.qty;b["ci:extPrice"]=
d.extPrice;b["ci:seqNumber"]=i;b["c:amount"]=h(a.amount);b["c:shipping"]=h(a.shipping);b["c:tax"]=h(a.tax);b["c:discount"]=h(e);b["c:itemCount"]=r.length;if(w)b["c:isIncomplete"]=w;b=z+"?"+I()+"&"+A(b);B(b)}}}};p=function(a,c,b){a=a+"="+c+"; expires="+(b.toUTCString||b.toGMTString).call(b);if(D)a=a+"; path="+D;if(C)a=a+"; domain="+C;x.cookie=a}})();