
var searchProfile;var selectedPath;var recordsPerPage;var currentPageNumber;var searchWords;var sortBy;var facetList;var errQuantity;var requiresSubscription;var IsUSBillingOnly;var availableLocation="";var kitPE=[];var originalBaseProductId=[];var currentProductId;var currentSelectedKitId;var browsePageFor="";var programID="";var tab="";function InitRecommendationsBrowse(){$('.browseHelpTab').slidifier({duration:800,startState:'closed',triggerClosed:'accSlideUp',triggerOpen:'accSlideDown'});LoadNeedHelpDiv();InitBrowseHelpDiv();$('#cancelBtn').bind('click',function(){$('.browseHelpTab').trigger('click');});$('.purchasePref').find('.mrt-1').removeClass('strong');if($('#tab').val().toLowerCase()=='all'){$('.purchasePref').find('.tabAll').addClass('strong');$('.purchasePref').find('.tabSeeAll').addClass('strong');}
else if($('#tab').val().toLowerCase()=='notin')
$('.purchasePref').find('.tabNotIn').addClass('strong');else if($('#tab').val().toLowerCase()=='in')
$('.purchasePref').find('.tabIn').addClass('strong');else if($('#tab').val().toLowerCase()=='tabOnline')
$('.purchasePref').find('.tabOnline').addClass('strong');else if($('#tab').val().toLowerCase()=='tabInStore')
$('.purchasePref').find('.tabInStore').addClass('strong');}
function InitBrowseHelpDiv(){if(browsePageFor.toLowerCase()=="c"){$('.JQNormalEvent').addClass('hide');$('.JQCardShower').removeClass('hide');}
else{$('.JQCardShower').addClass('hide');$('.JQNormalEvent').removeClass('hide');}}
function getdataMoreRecommendedProducts(){if($('#browseHelpProductype').attr('selectedIndex')==0&&$('#browseHelpOccasion').attr('selectedIndex')==0&&$('#browseHelpRecipient').attr('selectedIndex')==0&&$('#browseHelpTone').attr('selectedIndex')==0&&$('#browseHelpPhotoQty').attr('selectedIndex')==0){$('.JQBrowseHelpError').removeClass('hide');return;}
var params="";var ptyp="";var rcpnt="";var tone="";var ph="";var path="";var occasion="";if($('#browseHelpProductype').attr('selectedIndex')!=0){ptyp=encodeURIComponent($('#browseHelpProductype option:selected').text());}
if($('#browseHelpOccasion').attr('selectedIndex')!=0){occasion=encodeURIComponent($('#browseHelpOccasion option:selected').text());}
if($('#browseHelpRecipient').attr('selectedIndex')!=0){rcpnt=encodeURIComponent($('#browseHelpRecipient option:selected').text());}
if($('#browseHelpTone').attr('selectedIndex')!=0){tone=encodeURIComponent($('#browseHelpTone option:selected').text());}
if($('#browseHelpPhotoQty').attr('selectedIndex')!=0){ph=$('#browseHelpPhotoQty option:selected').text();}
if($('#browseHelpOccasion').attr('selectedIndex')!=0){path=encodeURIComponent($('#browseHelpOccasion option:selected').val());}
if($('#browseHelpRecipient').attr('selectedIndex')!=0){path=encodeURIComponent($('#browseHelpRecipient option:selected').val());}
if($('#browseHelpTone').attr('selectedIndex')!=0){path=encodeURIComponent($('#browseHelpTone option:selected').val());}
if($('#browseHelpPhotoQty').attr('selectedIndex')!=0){path=encodeURIComponent($('#browseHelpPhotoQty option:selected').val());}
params="?n="+path+"&tab="+encodeURI($('#tab').val())+"&evtid=&fn="+encodeURI($('#fn').val())+"&ln="+encodeURI($('#ln').val())+"&ettl="+encodeURI($('#ettl').val())+"&ptyp="+ptyp+"&occ="+occasion+"&rcpnt="+rcpnt+"&tone="+tone+"&ph="+ph+"&etyp="+encodeURI(browsePageFor);window.location.href="/Recommendations/ProductRecommendation"+params;}
function ResetBrowseHelpOverlay(){$('div.browseHelpInnerContain div.remainder select').each(function(){$(this).find('option:gt(0)').remove();}).attr('disabled',true);$('.JQBrowseHelpError').addClass('hide');}
function getdataForBrowseHelpPopup(Path,currentObj){if($(currentObj).hasClass('accSlideDown')){ResetBrowseHelpOverlay();return;}
if($(currentObj).find('option:selected').index()!=0){$('.JQBrowseHelpError').addClass('hide');var targetObj=$('.browseHelpInnerContain').find('div > select').not($('.browseHelpInnerContain').find('div > select.hide'));if(targetObj.first().children().length==1||Path!=''){targetObj.not(currentObj).attr('disabled',true);$.ajax({type:"POST",contentType:"application/x-www-form-urlencoded",url:"/Recommendations/QuickSearch",dataType:"json",data:{n:Path},success:function(data){if(data!=''){if(Path==''){populateBrowseHelpDropdowns(targetObj.first(),data);InitBrowseHelpDropdown(targetObj.first());}
else if($(currentObj).attr('id')==$(targetObj[0]).attr('id')){populateBrowseHelpDropdowns(targetObj[1],data);InitBrowseHelpDropdown(targetObj[1]);}
else{targetObj.not(targetObj[1]).not(targetObj[0]).each(function(){populateBrowseHelpDropdowns(this,data);$(targetObj[0]).attr('disabled',false);});}}}});}}
PopulateOmnitureForOverlay("browse help overlay");}
function PopulateOmnitureForOverlay(pageName){var eventType='';var occ=$("#occ").val();if($("#etyp").val()=='I')
eventType='Inv';else if($("#etyp").val()=='C')
eventType='CS';s.prop1="My Hallmark";s.pageName="My Hallmark > Events>"+pageName+"> "+eventType+'_'+occ;s.prop32="My Hallmark > Events>"+pageName+" > "+eventType+'_'+occ;s.prop2="My Hallmark > Events";s.prop3="My Hallmark > Events>"+pageName+" > "+eventType+'_'+occ;s.prop30="My Hallmark > Events>"+pageName;s.prop45=eventType+'_'+occ;s.eVar48=eventType+'_'+occ;s.eVar32="My Hallmark > Events>"+pageName+" > "+eventType+'_'+occ;evalOmniture();}
function InitBrowseHelpDropdown(targetObj){$(targetObj).unbind('change.getOtherDrpdwnValues').bind('change.getOtherDrpdwnValues',function(){getdataForBrowseHelpPopup($(targetObj).find('option:selected').val(),targetObj);});}
function populateBrowseHelpDropdowns(targetObj,data){var j=0;var firstValue=$(targetObj).children().first()
$(targetObj).children().not($(targetObj).children().first()).remove();for(var i=0;i<data.length;i++){if(data[i].Name==$(targetObj).children().first().val()){for(j=0;j<data[i].NavigatorValues.length;j++){$(targetObj).append('<option value='+data[i].NavigatorValues[j].Path+'>'+data[i].NavigatorValues[j].Name+'</option>');}
break;}}
$(targetObj).attr('disabled',false);}
function changeAllImageInSolidTableware(Color){var Value;$.ajax({type:"POST",contentType:"application/x-www-form-urlencoded",url:"/Browse/BrowseSolidColorTableware",data:{Color:Color},dataType:"html",success:function(data){$('#solidColorTableware').html(data);}});}
function changeImageInSolidTableware(ProductType,Color,divID,ProductLine,SearchProfile,RecordsPerPage){var Value;$.ajax({type:"POST",contentType:"application/x-www-form-urlencoded",url:"/Browse/GetSingleProductDetails",data:{Productype:ProductType,Color:Color,ProductLine:ProductLine,SearchProfile:SearchProfile,RecordsPerPage:RecordsPerPage},dataType:"json",success:function(data){if(data!=null&&data.Productype!=0){document.getElementById('Image'+data.Productype).src=data.ImageURL;document.getElementById('Description'+data.Productype).innerHTML="<h2>"+data.ProductName+"</h2><ul><li>"+data.ShortDescription+"</li><li>Package of "+data.PackageQuantity+"</li><li>"+data.FormattedUnitSalePrice+"</li>";$('#packageDesc'+data.Productype).text("packages of "+data.PackageQuantity+" "+data.ProductName);$('#color'+ProductType+" :li").each(function(){$(this).removeClass('selected');});$('#'+ProductType+Color).addClass('selected');var selectedProductID=data.KitID;var selectedBaseProductID=data.BaseProductID;$('#selectedKitID'+(parseInt(divID)-1)).val(selectedProductID);$('#baseProductID'+(parseInt(divID)-1)).val(selectedBaseProductID);$('#selectedProdID').val(selectedProductID);$('#color'+(parseInt(divID)-1)).val(Color);$('#ImageUrl'+(parseInt(divID)-1)).val(data.ImageURL);}}});}
function CallAddAllItemsToBag(SolidTablewareCount,MaxQuantityAllowed){$('#errDiv').text("");var totitems=0;var flag=true;var shoppingBagCount=$('#shoppingBagCount').find('strong').text().replace(/\D/g,'');for(iCount=0;iCount<SolidTablewareCount;iCount++){if($('#purchaseQty'+iCount).val()==""){$('#purchaseQty'+iCount).val(0);}
if($('#purchaseQty'+iCount).val()>0)
totitems=parseInt(totitems)+1;if($('#purchaseQty'+iCount).val()>MaxQuantityAllowed){flag=false;$('#errorDiv'+iCount).text(errQuantity);}
else{$('#errorDiv'+iCount).text("");}}
if(flag){if((parseInt(totitems)+parseInt(shoppingBagCount))>10){$('#errDiv').text('Your shopping bag is full. Orders can be placed for up to 10 items at a time. Please remove some of your items before you place your order. Don\'t forget, you can add items from your shopping bag to your Saved Items and find them later.');}
else if(totitems==0){$('#errDiv').text(errQuantity);}
else{document.forms["frmSolidColorTableware"].action="/Product/AddSolidTablewareToShoppingBag";document.forms["frmSolidColorTableware"].submit();}}}
function SetSelectPathForBreadcrumb(pathName){selectedPath=document.getElementById(pathName+'SelectedPath').value;currentPageNumber=1;recordsPerPage='';sortBy='';DoFormPost();}
function SetProfileForBreadcrumb(){if(searchProfile!='CrawlerSearchProfile')
searchProfile='ContentSearchProfile';selectedPath='';currentPageNumber=1;recordsPerPage='';sortBy='';DoFormPost();}
function SetSelectedPath(id){selectedPath=id;currentPageNumber=1;recordsPerPage='';sortBy='';DoFormPost();}
function SetSelectedPathForCrawler(id){selectedPath=id;currentPageNumber=1;recordsPerPage='';sortBy='';actionName='/Browse/ArticleList';window.location.href=actionName+"?n="+escape(selectedPath)+"&ctx="+escape(searchProfile)+"&pg="+escape(currentPageNumber)+"&rpp="+escape(recordsPerPage)+"&sort="+escape(sortBy)+"&k="+escape(searchWords)+"&npath="+escape(facetList);}
function PostForm(pageNumber){currentPageNumber=pageNumber;DoFormPost();}
function ChangeItemsPerPage(dropDownID){recordsPerPage=document.getElementById(dropDownID).value;currentPageNumber=1;sortBy='';document.getElementById("ItemsPerPage1").value=recordsPerPage;document.getElementById("ItemsPerPage2").value=recordsPerPage;DoFormPost();}
function SortItems(sortType){currentPageNumber=1;sortBy=document.getElementById(sortType).value;DoFormPost();}
function ChangeRefineBy(id){selectedPath=document.getElementById(id).value;if(selectedPath!=''){currentPageNumber=1;recordsPerPage='';sortBy='';DoFormPost();}}
function ShowProductsAvailableAt(location){availableLocation=location;DoFormPost();}
function ShowRecommendations(newtab){if($('#sortBy').val()=="undefined"||$('#sortBy').val()==""){if(newtab=='all'||newtab=='in')
$('#sortBy').val('Purchased');else if(newtab=='notin')
$('#sortBy').val('');}
$('#tab').val(newtab);DoFormPost();}
function DoFormPost(){sortBy=sortBy==""?$('#SortBy').val():sortBy;if($("#etyp").val()!=""&&$("#etyp").val()!="undefined"&&$("#etyp").val()!=undefined){if($("#hmkServerURL").length>0){actionName=$("#hmkServerURL").val()+'/Recommendations/ProductRecommendation';}
else{actionName='/Recommendations/ProductRecommendation';}
facetList=(!facetList||facetList=='undefined')?'':facetList;sortBy=(!sortBy||sortBy=='undefined')?'':sortBy;window.location.href=actionName+"?n="+escape(selectedPath)+"&ctx="+escape(searchProfile)+"&page="+escape(currentPageNumber)+"&rpp="+escape(recordsPerPage)+"&sort="+escape(sortBy)+"&k="+escape(searchWords)+"&npath="+escape(facetList)+"&availableLocation="+escape(availableLocation)+"&tab="+escape($('#tab').val())+"&evtid="+escape(programID)+"&fn="+escape($('#fn').val())+"&ln="+escape($('#ln').val())+"&ettl="+encodeURI($('#ettl').val())+"&ptyp="+escape($('#ptyp').val())+"&occ="+escape($('#occ').val())+"&etyp="+escape($('#etyp').val());}
else{if(searchProfile=="StationerySearchProfile"||searchProfile=="PaperCardsSearchProfile"||searchProfile=="ECardsSearchProfile"||searchProfile=="PartySearchProfile"||searchProfile=="PersonalizedPlateSearchProfile"||searchProfile=="BooksSearchProfile"||searchProfile=="GiftsSearchProfile"||searchProfile=="MemoryKeepingSearchProfile"||searchProfile=="GreetingAndPhotoCardSearchProfile"||searchProfile=="GreetingCardSearchProfile"||searchProfile=="InvitationSearchProfile"||searchProfile=="AnnouncementSearchProfile"||searchProfile=='ContentSearchProfile'||searchProfile=='OccasionSearchProfile'||searchProfile=='HolidaySearchProfile'||searchProfile=='JustBecauseSearchProfile'||searchProfile=="CrawlerSearchProfile"||searchProfile=="KOSearchProfile"){if($("#hmkServerURL").length>0){actionName=$("#hmkServerURL").val()+'/Browse/Index';}
else{actionName='/Browse/Index';}}
sortBy=(!sortBy||sortBy=='undefined')?'':sortBy;window.location.href=actionName+"?n="+escape(selectedPath)+"&ctx="+escape(searchProfile)+"&pg="+escape(currentPageNumber)+"&rpp="+escape(recordsPerPage)+"&sort="+escape(sortBy)+"&k="+escape(searchWords)+"&npath="+escape(facetList)+"&availableLocation="+escape(availableLocation);}}
$(document).ready(function(){$('.searchFormSubmit').click(function(){if($('.searchFormText').attr('value')==""||$('.searchFormText').attr('value')=="Search"){$('#searchEmptyWarning').show();return(false);}
else{selectedPath='';searchProfile='ContentSearchProfile';if($('#searchFormText').val()!='Search'&&$('#searchFormText').val()!=''){searchWords=$('#searchFormText').val();}
SearchFormPost();return false;}});$('.searchFormText').focus(function(){if($('#searchEmptyWarning:visible')){$('#searchEmptyWarning').hide();}});$('.searchFormText').blur(function(){if($('#searchEmptyWarning:visible')){$('#searchEmptyWarning').hide();}});$('form.searchForm :text').bind("keypress",function(e){if(e.keyCode==13){if($('.searchFormText').attr('value')==""||$('.searchFormText').attr('value')=="Search"){$('#searchEmptyWarning').show();return(false);}
else{selectedPath='';searchProfile='ContentSearchProfile';if($('#searchFormText').val()!='Search'&&$('#searchFormText').val()!=''){searchWords=$('#searchFormText').val();}
SearchFormPost();return false;}}
else{if($('#searchEmptyWarning:visible')){$('#searchEmptyWarning').hide();}}});if(searchWords=='Search'||searchWords==''||(typeof searchWords=="undefined")){if(searchProfile=="PaperCardsSearchProfile"||searchProfile=="GreetingAndPhotoCardSearchProfile"||searchProfile=="InvitationSearchProfile"||searchProfile=="AnnouncementSearchProfile"||searchProfile=="StationerySearchProfile"){adSpot.GetAdHTML($('#needHelp'),'NeedHelp','NeedHelp','Checkout');}}
if(searchProfile=="PaperCardsSearchProfile"||searchProfile=="GreetingAndPhotoCardSearchProfile"||searchProfile=="InvitationSearchProfile"||searchProfile=="AnnouncementSearchProfile"||searchProfile=="StationerySearchProfile"||searchProfile=="ECardsSearchProfile"){$('.allowInstore').each(function(){$(this).closest('li').addClass('disabled');hallmarkBehaviors.hmkDisableButton($(this));});}});function SearchHeader(){if($('.searchFormText').attr('value')==""||$('.searchFormText').attr('value')=="Search"){$('#searchEmptyWarning').show();return(false);}
else{selectedPath='';searchProfile='ContentSearchProfile';$("#etyp").val("");SearchFormPost();}}
function SetSearchProfile(id){switch(id){case"E-Cards":searchProfile="ECardsSearchProfile";break;case"Paper Cards":searchProfile="PaperCardsSearchProfile";break;case"Occasion":searchProfile="OccasionSearchProfile";break;case"Greeting & Photo Cards":searchProfile="GreetingAndPhotoCardSearchProfile";break;case"Books":searchProfile="BooksSearchProfile";break;case"Gifts":searchProfile="GiftsSearchProfile";break;case"Memory Keeping":searchProfile="MemoryKeepingSearchProfile";break;case"Stationery":searchProfile="StationerySearchProfile";break;case"Invitations":searchProfile="InvitationSearchProfile";break;case"Announcements":searchProfile="AnnouncementSearchProfile";break;case"Personalized Plates":searchProfile="PersonalizedPlateSearchProfile";break;case"Holiday":searchProfile="HolidaySearchProfile";break;case"Just Because":searchProfile="JustBecauseSearchProfile";break;case"Keepsake Ornaments":searchProfile="KOSearchProfile";break;case"Other Results":searchProfile="CrawlerSearchProfile";break;default:searchProfile="ContentSearchProfile";break;}
SearchFormPost();}
function SearchFormPost(){currentPageNumber=1;recordsPerPage='';selectedPath='';sortBy='';facetList='';if(searchWords!='Search'&&searchWords!=''&&(typeof searchWords!="undefined")){s.eVar2=searchWords;s.eVar43=window.location.pathname+'>>'+searchWords;s.prop11=searchWords;evalOmniture();DoFormPost();}
else if($("#etyp").val()!=""&&$("#etyp").val()!="undefined"&&$("#etyp").val()!=undefined){DoFormPost();}}
function ShowQuickLookPopup(baseProductID,productType,productLine){$('#saving').attr('style','display:none');$('#saved').attr('style','display:none');$('#DiscountsDiv').remove();$.ajax({type:"POST",url:"/Browse/QuickLook",contentType:"application/x-www-form-urlencoded",dataType:"html",data:{BaseProductID:baseProductID,SearchProfile:searchProfile,FacetList:facetList},error:function(e){},success:function(data){if(data!=""){$('#divQuickLook').html(data);displayQuickLookOverlay();if(productLine=="ECARD"){if(productType==47){$('#hallEcards').attr('style','display:none');$('#SmileBoxCards').attr('style','display:block');}
else{$('#hallEcards').attr('style','display:block');$('#SmileBoxCards').attr('style','display:none');}
ShowReleventButtons(baseProductID,productType,productLine);}
if(isRegisteredUser){$('#addToSaved,.addToSaved').attr('style','display:block');}
else{$('#addToSaved,.addToSaved').attr('style','display:none');}
$(".itemSaving").css('display','none');$(".itemSaved").css('display','none');}}});}
function ShowReleventButtons(baseProductID,productType,productLine){if((!isRegisteredUser)||isAjaxCompleted=="1"){requiresSubscription=$('#RequiresSubscription').val();IsUSBillingOnly=$('#IsUSBillingOnly').val();if(canadianSubscriptionMessage!=''&&IsUSBillingOnly=='True')
$('.facebook').hide();if((requiresSubscription=='True')&&productType!=47){if(isSubscribed=="1"){$('.eProdPers').attr('style','display:block');$('#PurchaseSubscriptionContent1').addClass('hide');$('#PurchaseSubscriptionContent2').addClass('hide');$('#SubscribeAndSendButton').addClass('hide');$('#AddToSavedItems1').addClass('hide');$('#HaveASubscriptionContent').addClass('hide');$("#P"+baseProductID+"_DK").attr("href","/EPersonalization/ECardPersonalize/"+baseProductID+"_DK"+"/0/0");$('#PersonalizeContent').removeClass('hide');}
else if(isSubscribed=="0"&&isRegisteredUser){$('.eProdPers').attr('style','display:none');$('#PurchaseSubscriptionContent1').addClass('hide');$('#PurchaseSubscriptionContent2').removeClass('hide');$('#SubscribeAndSendLink').attr("href","/Browse/Subscribe?URL="+"/EPersonalization/ECardPersonalize/"+baseProductID+"_DK"+"/0/0");$('#SubscribeAndSendButton').removeClass('hide');$('#HaveASubscriptionContent').addClass('hide');$('#PersonalizeContent').addClass('hide');}
else if(isSubscribed=="0"&&(!isRegisteredUser)){$('.eProdPers').attr('style','display:none');$('#PurchaseSubscriptionContent1').removeClass('hide');$('#PurchaseSubscriptionContent2').addClass('hide');$('#SubscribeAndSendLink').attr("href","/Browse/Subscribe?URL="+"/EPersonalization/ECardPersonalize/"+baseProductID+"_DK"+"/0/0");$('#SubscribeAndSendButton').removeClass('hide');$('#HaveASubscriptionLink').attr("href","/Browse/Subscribe?URL="+"/EPersonalization/ECardPersonalize/"+baseProductID+"_DK"+"/0/0");$('#HaveASubscriptionContent').removeClass('hide');$('#PersonalizeContent').addClass('hide');}}
else{$('#PurchaseSubscriptionContent1').addClass('hide');$('#PurchaseSubscriptionContent2').addClass('hide');$('#SubscribeAndSendButton').addClass('hide');$('#HaveASubscriptionContent').addClass('hide');$('#AddToSavedItems1').addClass('hide');$("#P"+baseProductID+"_DK").attr("href","/EPersonalization/ECardPersonalize/"+baseProductID+"_DK"+"/0/0");$('#PersonalizeContent').removeClass('hide');}}
else{$.ajax({type:"POST",contentType:"application/x-www-form-urlencoded",url:"/EPersonalization/CheckUserTypeAndSubscriptionDetails",dataType:"json",success:function(data){canadianSubscriptionMessage=data.substr(1);isSubscribed=data.substr(0,1);isAjaxCompleted="1";if(isSubscribed=="1")
$('.subscribePlanNowPopUp').attr("href","/SubscriptionPlans/Load");else
$('.subscribePlanNowPopUp').attr("href","/SubscriptionPlans/Subscribe");ShowReleventButtons(baseProductID,productType,productLine);}});}}
function displayQuickLookOverlay(){$("#divQuickLook").overlay({api:true,speed:200,expose:{maskId:'overlyMask',loadSpeed:800,opacity:0.9},onBeforeLoad:function(){var wrap=this.getContent().find("div.wrap");if(wrap.is(":empty")){wrap.load(this.getTrigger().attr("href"));}},onClose:function(){if(document.getElementById("quicklookoverDiv"))
document.getElementById("quicklookoverDiv").innerHTML="";},closeOnClick:false}).load();$(".close").click(function(){if(document.getElementById("quicklookoverDiv"))
document.getElementById("quicklookoverDiv").innerHTML="";$("#divQuickLook").overlay().close();});}
function changeQuickLookProductImage(productImage,displayType){$("#ProductImage").attr("src",productImage);}
function saveFavoritesByAjax(obj,productLine,baseProductID,kitID,projectName){if(productLine!='FINISHEDGOODS'){projectName=(projectName)?projectName:"";$('#SaveItemsErrorMessageDiv').hide();$('#SaveItemsErrorMessage').hide();$('#SaveItemsErrorMessage').html('');$('#saving').show();$('#saved').hide();if(projectName!=null){projectName=$.trim(projectName);}
if(projectName==null||projectName==""){$('#SaveItemsErrorMessageDiv').show();$('#SaveItemsErrorMessage').show();$('#SaveItemsErrorMessage').html('Please name your item.');$('#saving').hide();return;}}
$('#ErrorMessage').html('');$('#ErrorDiv').hide();$('#saving').show();$('#saved').hide();$('#addToSaved,.addToSaved').addClass('disabled');hallmarkBehaviors.hmkDisableButton($(obj));$.ajax({type:"POST",contentType:"application/x-www-form-urlencoded",url:"/Product/SaveToFavorites",data:{'ProductInView.ProductLine':productLine,'ProductInView.ProductID':baseProductID,'SelectedKitID':kitID,'projectName':projectName},dataType:"json",error:function(e){hallmarkBehaviors.hmkEnableButton($(obj));},success:function(data){if(null!=data.ValidationResult&&data.ValidationResult.length>0){$('#SaveItemsErrorMessageDiv').show();$('#SaveItemsErrorMessage').show();$('#SaveItemsErrorMessage').html(data.ValidationResult[0].Message);$('#saving').hide();}
else{if(productLine!='FINISHEDGOODS'){$("#ProjectName").val('');$("#ConfirmAddToSavedItems").addClass('hide');}
if(data.JsonError==true||data.JsonError=='true'){$('#ErrorMessage').html(data.JsonErrorMessage);$('#ErrorDiv').show();$('#saving').hide()}
else{$('#saving').hide();$('#saved').show();LoadSecondaryHeaderControl();}}
hallmarkBehaviors.hmkEnableButton($(obj));hallmarkBehaviors.hmkDisableButton($('#addToSaved,.addToSaved'));}});}
function changeSkuColorInBrowse(kitAssociation,selectedSKU){$("#BrowseThumbnail_"+selectedSKU).attr("src",kitAssociation.ImageURL);$("#BrowseTitle1_"+selectedSKU).html(kitAssociation.ProductName);$("#BrowseColorSwatch_"+kitAssociation.KitID).closest('ul').find('img').removeClass('selected');$("#BrowseColorSwatch_"+kitAssociation.KitID).find('img').addClass('selected');}
function setOmnitureForQuickLookColorSwatchClick(kitAssociation){s.prop3=s.prop3.substring(0,s.prop3.lastIndexOf(">")+1)+kitAssociation.PartNumber;s.prop7=kitAssociation.KitID;s.prop9=kitAssociation.Name;s.products=";"+kitAssociation.KitID;}
function quickAddToBag(obj,productLine,baseProductID,kitID,projectID,projectViewStatus,projectName){if($('#previewFinishedGoods').overlay().close)$('#previewFinishedGoods').overlay().close();projectViewStatus=(projectViewStatus)?projectViewStatus:'F';projectID=(projectID)?projectID:0;projectName=(projectName)?projectName:"";$('#ErrorMessage').html('');$('#ErrorDiv').hide();$('#saving').show();$('#saved').hide();$('#addToSaved,.addToSaved').addClass('disabled');hallmarkBehaviors.hmkDisableButton($(obj));$.ajax({type:"POST",contentType:"application/x-www-form-urlencoded",url:"/Product/QuickAddToBag",data:{'ProductInView.ProductLine':productLine,'ProductInView.ProductID':baseProductID,'SelectedKitID':kitID,'ProductInView.ProjectID':projectID,'ProjectViewStatusCode':projectViewStatus,'projectName':projectName},dataType:"json",error:function(e){hallmarkBehaviors.hmkEnableButton($(obj));},success:function(data){if(data.JsonError==true||data.JsonError=='true'){$('#ErrorMessage').html(data.JsonErrorMessage);$('#ErrorDiv').show();$('#saving').hide()
$('#addToSaved,.addToSaved').removeClass('disabled');}
else{window.location="/ShoppingBag/ShoppingBag";}
hallmarkBehaviors.hmkEnableButton($(obj));}});}
function changeSkuColorInQuicklook(kitAssociation,selectedSKU){$("#ProductImage").attr("src",kitAssociation.ProductPreviewThumbnailImagePath);$("#D"+selectedSKU).html(kitAssociation.ProductName);$("#PersonalizationLink").attr("href","/Personalization/CardPersonalization/"+kitAssociation.KitID+"/0");$('#variableSelectLG').find('img').removeClass('selected');$("#QuicklookColorSwatch_"+kitAssociation.KitID).find('img').addClass('selected');setOmnitureForQuickLookColorSwatchClick(kitAssociation);currentProductId=kitAssociation.PartNumber;currentSelectedKitId=kitAssociation.KitID;evalOmniture();}
function showSaveItemsToFavoritesPopUp(){if(!($("#addToSaved,.addToSaved").hasClass('disabled'))){$('#ConfirmAddToSavedItems').removeClass('hide');$('#ConfirmAddToSavedItems').addClass('show');$('#addToSaved,.addToSaved').addClass('disabled');$('#saved').hide();}}