
CalendarDropDowns=function(containerDivID,inputBox,date,dayCombo,monthCombo,yearCombo,defaultToTodayDay,defaultToTodayMonth,defaultToTodayYear,day,month,year,yearVisibility,maxYears){this.dayComboVar=this.createElement('input','hidden',inputBox+'Day');this.monthComboVar=this.createElement('input','hidden',inputBox+'Month');this.yearComboVar=this.createElement('input','hidden',inputBox+'Year');this.dayComboVar.value=(day=='undefined'||day=='null'||day==null||typeof day=='undefined')?'':day;this.monthComboVar.value=(month=='undefined'||month=='null'||month==null||typeof month=='undefined')?'':month;this.yearComboVar.value=(year=='undefined'||year=='null'||year==null||typeof year=='undefined')?'':year;this.defaultToTodayYear=defaultToTodayYear;this.defaultToTodayDay=defaultToTodayDay;this.defaultToTodayMonth=defaultToTodayMonth;this.today=new Date();this.inputBox=document.getElementById(inputBox);this.date=date;if(this.date!=null)this.inputBox.value=date.toDateString();this.containerDiv=document.getElementById(containerDivID)
this.dayCb=document.getElementById(dayCombo);this.monthCb=document.getElementById(monthCombo);this.yearCb=document.getElementById(yearCombo);this.minNumYears=1900;this.maxNumYears=(maxYears==undefined||maxYears==null)?1:maxYears;this.buildOptions();if(!yearVisibility){this.yearCb.style.visibility="hidden";}
this.containerDiv.appendChild(this.monthComboVar);this.containerDiv.appendChild(this.dayComboVar);this.containerDiv.appendChild(this.yearComboVar);this._inst=this;this.addEvents(this._inst);}
Date.prototype.toDateString=function(){return[this.getMonth()<9?'0'+(this.getMonth()+1):this.getMonth()+1,this.getDate()<10?'0'+this.getDate():this.getDate(),this.getFullYear()].join('/')}
CalendarDropDowns.prototype.isWrongDate=true;CalendarDropDowns.prototype.addEvents=function(obj){CalendarDropDowns.addEvent(this.dayCb,"change",function(){obj.dateChange(obj)});CalendarDropDowns.addEvent(this.monthCb,"change",function(){obj.dateChange(obj)});CalendarDropDowns.addEvent(this.yearCb,"change",function(){obj.dateChange(obj)});}
CalendarDropDowns.prototype.dateChange=function(target){target.dayComboVar.value=target.dayCb.options[target.dayCb.selectedIndex].value;target.monthComboVar.value=target.monthCb.options[target.monthCb.selectedIndex].value;target.yearComboVar.value=target.yearCb.options[target.yearCb.selectedIndex].value;if(target.updateOptions()){target.inputBox.value=target.date.toDateString();}
else{target.date=null;target.inputBox.value='';}
target.changeComboSelection();}
CalendarDropDowns.prototype.changeComboSelection=function(){var dayValue=this.dayComboVar.value;var monthValue=this.monthComboVar.value;var yearValue=this.yearComboVar.value;for(var i=0;i<this.dayCb.options.length;i++){if(this.dayCb.options[i].value==dayValue)
this.dayCb.options[i].selected=true;}
for(var i=0;i<this.monthCb.options.length;i++){if(this.monthCb.options[i].value==monthValue)
this.monthCb.options[i].selected=true;}
for(var i=0;i<this.yearCb.options.length;i++){if(this.yearCb.options[i].value==yearValue)
this.yearCb.options[i].selected=true;}
var dayCheck=(this.dayCb.selectedIndex==0&&!this.defaultToTodayDay);var monthCheck=(this.monthCb.selectedIndex==0&&!this.defaultToTodayMonth);var yearCheck=((this.yearCb.selectedIndex==0||this.yearCb.selectedIndex==1)&&!this.defaultToTodayYear);if(this.dayCb.selectedIndex==0&&this.monthCb.selectedIndex==0&&this.yearCb.selectedIndex==0){this.isWrongDate=false;}else if(dayCheck||monthCheck||yearCheck){this.isWrongDate=true;}else{this.isWrongDate=false;}}
CalendarDropDowns.prototype.updateOptions=function(){var tempDate=this.date;var dayValue=this.dayCb.value;var monthValue=this.monthCb.value;var yearValue=this.yearCb.value;this.updateDayOptions(dayValue,monthValue,yearValue);var validDays=this.getNumDays(monthValue,yearValue);if(dayValue>validDays){dayValue=validDays;this.dayComboVar.value=validDays;}
var dayCheck=(dayValue==''&&!this.defaultToTodayDay);var monthCheck=(monthValue==''&&!this.defaultToTodayMonth);var yearCheck=((yearValue==''||yearValue==' ')&&!this.defaultToTodayYear);if(dayValue==''&&monthValue==''&&(yearValue==''||yearValue==' ')){this.isWrongDate=false;return false;}
else if(dayCheck||monthCheck||yearCheck){this.isWrongDate=true;return false;}
if(this.defaultToTodayYear&&(this.yearCb.selectedIndex==0||this.yearCb.selectedIndex==1)){this.yearCb.value=this.updateYearBlankValue(dayValue,monthValue);yearValue=this.yearCb.value;}
this.date=new Date(yearValue,monthValue,dayValue);tempDate=this.date;this.isWrongDate=false;this.updateDayOptions(dayValue,monthValue,yearValue);return true;}
CalendarDropDowns.prototype.updateYearBlankValue=function(day,month){var today=this.today;var tempDate=new Date(today.getFullYear(),month,day);if(tempDate.getMonth()<today.getMonth()||(tempDate.getMonth()==today.getMonth()&&tempDate.getDate()<=today.getDate()))
return today.getFullYear()+1;else
return today.getFullYear();}
CalendarDropDowns.prototype.updateDayOptions=function(day,month,year){if(year==''||year==' ')year=this.today.getFullYear();var numDays=this.getNumDays(month,year);while(this.dayCb.options.length>1){this.dayCb.remove(1);}
this.dayCb.selectedIndex=0;$(this.dayCb).change();for(var i=0;i<numDays;i++){this.dayCb.options[i+1]=new Option((i+1),(i+1));if(this.dayCb.options[i+1].value==day)this.dayCb.options[i+1].selected=true;}
$(this.dayCb).change();}
CalendarDropDowns.prototype.updateYearOptions=function(minNumYears,maxNumYears){var tempDate=this.date;if(this.minNumYears!=minNumYears||this.maxNumYears!=maxNumYears){this.minNumYears=minNumYears;this.maxNumYears=maxNumYears;while(this.yearCb.options.length>2){this.yearCb.remove(2);}
var year=this.yearComboVar.value;if((year==''||year==' ')&&tempDate!=null)year=tempDate.getFullYear();for(var i=(this.today.getFullYear()+this.maxNumYears);i>=this.minNumYears;i--){var looper=(this.today.getFullYear()+this.maxNumYears)-i;if(this.defaultToTodayYear)looper++;this.yearCb.options[looper+1]=new Option(i,i);if(i==year)this.yearCb.options[looper+1].selected=true;}
this.dateChange(this);}}
CalendarDropDowns.prototype.buildOptions=function(){var tempDate=this.date;var strMonths=['Jan','Feb','Mar','Apr','May','June','Jul','Aug','Sep','Oct','Nov','Dec'];this.dayCb.options[0]=new Option('Day','');this.monthCb.options[0]=new Option('Month','');this.yearCb.options[0]=new Option('Year','');if(this.defaultToTodayDay){this.dayCb.options[0].value=this.today.getDate();this.dayCb.options[1]=new Option('Leave Blank',this.today.getDate());}
if(this.defaultToTodayMonth){this.monthCb.options[0].value=this.today.getMonth();this.monthCb.options[1]=new Option('Leave Blank',this.today.getMonth());}
if(this.defaultToTodayYear){this.yearCb.options[1]=new Option('Leave Blank'," ");}
for(var i=(this.today.getFullYear()+this.maxNumYears);i>=this.minNumYears;i--){var looper=(this.today.getFullYear()+this.maxNumYears)-i;if(this.defaultToTodayYear)looper++;this.yearCb.options[looper+1]=new Option(i,i);if(tempDate!=null&&i==tempDate.getFullYear())this.yearCb.options[looper+1].selected=true;}
for(var i=0;i<strMonths.length;i++){var looper=i+1;if(this.defaultToTodayMonth)looper++;this.monthCb.options[looper]=new Option(strMonths[i],(i+1));if(tempDate!=null&&i==tempDate.getMonth())this.monthCb.options[looper].selected=true;}
var numDays=31;if(tempDate!=null)numDays=this.getNumDays(tempDate.getMonth(),tempDate.getFullYear());if((this.yearComboVar.value==''||this.yearComboVar.value==' ')&&this.monthComboVar.value==2)
numDays=29;for(var i=0;i<numDays;i++){var looper=i+1;if(this.defaultToTodayDay)looper++;this.dayCb.options[looper]=new Option((i+1),(i+1));if(tempDate!=null&&(i+1)==tempDate.getDate())this.dayCb.options[looper].selected=true;}
this.changeComboSelection();}
CalendarDropDowns.prototype.getNumDays=function(month,year){var days=31;if(year==''||year==' ')year=this.today.getFullYear();if(month==2)days=(!(year%4)&&(year%100)||!(year%400))?29:28;else if(month==4||month==6||month==9||month==11)days=30;if((this.yearComboVar.value==''||this.yearComboVar.value==' ')&&month==2&&!this.defaultToTodayYear)
days=29;return days;}
CalendarDropDowns.addEvent=function(el,evname,func){if(navigator.userAgent.indexOf('MSIE')!=-1){el.attachEvent("on"+evname,func);}else{el.addEventListener(evname,func,true);}};CalendarDropDowns.prototype.createElement=function(element,type,name){if(navigator.userAgent.indexOf('MSIE')!=-1){var dynamicElement=document.createElement(element);dynamicElement.setAttribute("type",type);dynamicElement.setAttribute("name",name);return dynamicElement;}else{var ele=document.createElementNS("http://www.w3.org/1999/xhtml",element);if(element=='input')
ele.type=type;if(name!='')
ele.name=name;return ele;}}
function showCalendarDropDowns(containerDiv,inputBox,date,dayCombo,monthCombo,yearCombo,defaultToTodayDay,defaultToTodayMonth,defaultToTodayYear,day,month,year,yearVisibility){return(new CalendarDropDowns(containerDiv,inputBox,date,dayCombo,monthCombo,yearCombo,defaultToTodayDay,defaultToTodayMonth,defaultToTodayYear,day,month,year,yearVisibility,1));}
function showCalendarDropDownsWithMaxYears(containerDiv,inputBox,date,dayCombo,monthCombo,yearCombo,defaultToTodayDay,defaultToTodayMonth,defaultToTodayYear,day,month,year,yearVisibility,maxYears){return(new CalendarDropDowns(containerDiv,inputBox,date,dayCombo,monthCombo,yearCombo,defaultToTodayDay,defaultToTodayMonth,defaultToTodayYear,day,month,year,yearVisibility,maxYears));}