var h=!0,i=null,m=!1;
(function(b,r,v,s){function e(a){return"object"==typeof $t_data?a in $t_data?$t_data[a]:a:a}function y(){q("FFhide",1,365,"/");$("#addFFExtension").css("display","none")}function z(a){cookie=w(a);return cookie==i?m:h}function w(a){var c=r.cookie.indexOf(a+"="),d=c+a.length+1;if(!c&&a!=r.cookie.substring(0,a.length)||-1==c)return i;a=r.cookie.indexOf(";",d);-1==a&&(a=r.cookie.length);return unescape(r.cookie.substring(d,a))}function q(a,c,d,b){var f=new Date,k=new Date;d==i&&(d=1);k.setTime(f.getTime()+
864E5*d);cookieStr="";cookieStr=a+"="+escape(c);0<d&&(cookieStr+=";expires="+k.toGMTString());cookieStr+=";path="+b+";domain="+cookie_domain;r.cookie=cookieStr}function A(a){a!=s&&""!=a&&$.ajax({url:global_path+"ajax_add_to_downloads_history.html",timeout:1E4,type:"post",dataType:"json",data:{file_id:a},success:function(a){a.match(/not logged/)&&(b.location=global_path+"account/login.html?continue="+b.location);(a.match(/empty fid/)||a.match(/incorect fid/))&&alert(e("Something went terribly wrong ..."));
a.match(/file not exist/)&&alert(e("Unfortunately this file doesn't exist in our database anymore ..."));a.match(/file already in history/)&&alert(e("This file is already in your history ..."));a.match(/ok/)&&$("#add_to_history_span").empty().append($("<a></a>").attr("href",global_path+"account/history.html").css("cursor","pointer").text(e("Go to your downloads history")))}})}function n(a,c){this.f=a;this.R=c;this.timeout=3E3;this.i={};this.p={};this.L=35;this.replaceWith="..."}function j(a,c){this.f=
a;this.timeout=c;this.a=[]}v.prototype.indexOf||(v.prototype.indexOf=function(a,c){c==i?c=0:0>c&&(c=Math.max(0,this.length+c));for(var d=c,b=this.length;d<b;d++)if(this[d]===a)return d;return-1});var B=function(a){function c(a,c){var k=$("#ac_results").empty().width(o.width());t=a.length;l=-1;if(t===0)f();else if(t>0){c=$.trim(o.val());c=c.toLowerCase();if(c.length>0){var p=o.position();k.css({top:p.top+24,left:p.left});for(p=0;p<t;++p)k.append($("<p></p>").attr("id","ac_opt_"+p).attr("class","ac_inactive").html(unescape(a[p].replace(c,
"<b>"+c+"</b>"))).bind("mouseover",function(){$(".ac_active").attr("class","ac_inactive");$(this).attr("class","ac_active")}).bind("mouseout",function(){$(this).attr("class","ac_inactive")}).bind("click",function(){b($(this),2)}));k.append($("<a></a>").attr({href:"#","class":"ac_close"}).text(e("Close")).bind("click",function(){d();return m}));k.css("display","block")}else f()}}function d(){p=m;f();o.attr("autocomplete","on");return this}function b(a,c){if(a.html()!=i){var d=a.html().replace(/<B>|<\/B>/gi,
"");(c==s||c==2)&&o.val(d);if(c!=s){f();d=$("#ac_form");d.length&&(d=o.parent());d.length&&d.submit()}}}function f(){l=-1;$("#ac_results").css("display","none")}function k(a,d){$.trim(o.val().toLowerCase())===a.toLowerCase()&&$.ajax({dataType:"jsonp",url:ac_server+"/"+encodeURIComponent(a)+"?callback=?&t="+d,success:function(d){var b=parseInt(d.t);if(b>=j){j=b;n[a]=d.r;++q;c(d.r,a)}}})}var l=-1,t=0,p=h,j=0,n=[],q=0,o;return{bind:function(){o=$(a);if(typeof ac_server==="undefined")return d();o.attr("autocomplete",
"off");o.bind("keyup",function(a){var d=(new Date).getTime(),b=$.trim($(this).val()),b=b.toLowerCase();[40,38,13,27].indexOf(a.keyCode)==-1&&p&&(b.length>0?n[b]!==s?c(n[b],b):setTimeout(function(){k(b,d)},0):f())});$(r).bind("keyup",function(a){if(a.keyCode===27)f();else if(a.keyCode!=s){$(".ac_active").attr("class","ac_inactive");switch(a.keyCode){case 40:l==-1?l=0:++l>=t&&(l=0);$("#ac_opt_"+l).attr("class","ac_active");b($("#ac_opt_"+l));break;case 38:l==-1?l=t-1:--l<0&&(l=t-1);$("#ac_opt_"+l).attr("class",
"ac_active");b($("#ac_opt_"+l));break;case 13:if(l!=-1){a=$("#ac_opt_"+l);a.length&&b(a,1)}else f();break;case 37:case 39:case 8:l=-1}}});$("body").bind("click.autocompleter",function(){$(this).attr("id").indexOf("ac_")===-1&&f()});return this},disable:d}}("#ac_q");(function(a){a.fn.ba=function(){var c,d=this;c=a.extend({B:"tactive",q:"tnactive",ha:".toptions",C:0,A:"href"},c||{});a(this).each(function(){var b=a(this).find(c.ha).children(),f;b.each(function(k){a(this).addClass(c.q);a(this).click(function(b){b.preventDefault();
a(this).addClass(c.q);b=d.find(a(this).attr(c.A));if(b.length===0)throw"Could not find matching tab content for id: "+a(this).attr(c.A);f.removeClass(c.B).addClass(c.q);a(f.attr(c.A)).hide();a(this).removeClass(c.q).addClass(c.B);b.show();f=a(this)});if(k===c.C||k===0&&b.length-1<c.C){f=a(this);a(this).trigger("click")}})})}})(jQuery);var D=function(){function a(a){$(a).bind("mousemove.stars",function(a){for(var a=a.pageX-$(this).offset().left,c=b.length-1;c>=0;c--)if(b[c]<a){d=c+1;break}$(this).attr("class",
"star"+d)});$(a).bind("mouseout.stars",function(){d=c;$(this).attr("class","star"+d)});$(a).bind("click.stars",function(){var c=$(a).parent();c.empty().append($("<img>").attr("src",static_path+"images/ajax-loader.gif"));$.ajax({url:global_path+"ajax_link_rate.html?link_id="+$(this).attr("id")+"&rate="+d,success:function(a){var a=a.split("-"),d=parseFloat(a[0]);c.empty().append($("<div>").css({margin:"0px 10px 0 0","float":"left","line-height":"22px"}).text(e("Thanks for your rate"))).append($("<div>").attr("class",
"star"+Math.round(d)).css({"float":"left","line-height":"22px"})).append($("<div>").addClass("votes_info").text("("+a[1]+" "+e("votes")+", "+e("average")+": "+d+" "+e("out of")+" 5)"))}})})}var c,d,b=[0,17,33,49,66];return{bind:function(b,g){c=d=parseInt(g.replace("star",""));a(b)}}}();n.prototype.Y=function(a){if(a.length==0)return m;for(var c=m,d="",b=0;b<a.length;b++)d=d+(a[b].key+",");var d=d.substring(0,d.length-1),f=setTimeout(function(){c=h},this.timeout);$.ajax({dataType:"jsonp",url:this.f+
"/check/"+d,success:function(a){clearTimeout(f);if(!c)for(var b in a.result)parseInt(a.result[b],10)>0&&$("#"+b).show()}})};n.prototype.ca=function(a,c){var b=m,g=this,f=$("#alternatives_"+a);if(!(a in g.p))if(a in g.i){f[g.i[a]===m?"show":"hide"]();$("#"+a).html(g.i[a]===m?'<img src="'+global_path+'images/alt_minus.gif" /> '+e("Hide other source links"):'<img src="'+global_path+'images/alt_plus.gif" /> '+e("Show other source links"));g.i[a]=!g.i[a]}else{g.p[a]=h;f.empty().show().attr("class","alt_div_list2 check-spinner");
var k=function(){b=h;f.attr("class","alt_div_list2").text(e("An error occured. Please try again later"));setTimeout(function(){f.fadeOut(100)},3E3)},l=setTimeout(function(){k();delete g.p[a]},g.timeout);$.ajax({dataType:"jsonp",url:g.f+"/get/"+a+"/"+c,success:function(c){clearTimeout(l);if(!b){var f='<div class="alt_div_list">',k;for(k in c.result){current=c.result[k];f=f+('<a href="'+global_path+current.t+'/go.html" title="'+current.n+'" target="_blank">'+(current.n.length>g.L?current.n.substring(0,
g.L-g.replaceWith.length)+g.replaceWith:current.n)+"</a> <span>"+current.h+"</span><br />")}container=$("#alternatives_"+a).html(f+"</div>").attr("class","alt_div_list2");$("#"+a).html('<img src="'+global_path+'images/alt_minus.gif" />'+e("Hide other source links"));g.i[a]=h;delete g.p[a]}},error:function(){k();delete g.p[a]}})}};n.prototype.da=function(){function a(){$("#broken_alternatives .spinner").hide();$("#broken_alternatives .notfound").fadeIn("slow");g=h;setTimeout(function(){$("#broken_alternatives").slideUp("slow")},
3E3)}var c=alternate_files[0].key,b=alternate_files[0].token;$("#broken_alternatives").show();$("#broken_alternatives .spinner").show();var g=m,f=setTimeout(a,1E4);$.ajax({url:this.f+"/getb/"+c+"/"+b,type:"GET",dataType:"jsonp",timeout:1E4,success:function(c){clearTimeout(f);if(!g){$("#broken_alternatives .spinner").hide();if(c.success&&c.result.length>0)for(var b in c.result){var d=$("#broken_alternatives div tr:eq(0)").clone().appendTo("#broken_alternatives div").show(),d=$(d).find("td"),e=c.result[b],
j="",j=e.k==2?global_path+e.t+",g/"+e.n.replace(/ /g,"_")+".html":global_path+e.t+"/"+e.n.replace(/ /g,"_")+".html";$(d[0]).html('<a href="'+j+'">'+e.n+"</a>");$(d[1]).html(e.h);$(d[2]).html(e.s);$(d[3]).find("a").attr("href",j)}else a()}},error:function(){clearTimeout(f);a()}})};j.prototype.Q=function(a){this.a.push(a)};j.prototype.V=function(){for(x in this.a)this.X(this.a[x].t,this.a[x].ct)};j.prototype.X=function(a,c){this.I(a);var b=b||this;$.ajax({url:"http://"+this.f,dataType:"jsonp",data:{cta:c,
"_=_":Math.random().toString()},success:function(c){c.error!="0"?b.error(a):c.broken.length>0?b.G(a):b.N(a)},error:function(){b.error(a)}});setTimeout(function(){$("#checkstatus_"+a).attr("class")==="check-spinner"&&b.error(a,c)},this.timeout)};j.prototype.W=function(a){for(var c in this.a)this.I(this.a[c].t);var b=b||this,g=b.a,f=this;$.ajax({url:"http://"+f.f,dataType:"jsonp",data:{cta:a},success:function(a){if(a.error!="0")for(var c in g)f.error(g[c].t);if("broken"in a&&a.broken instanceof v)for(var e in g){broken=
m;for(c in a.brokens)if(a.broken[c]===g[e].t){broken=h;break}broken?b.G(g[e].t):b.N(g[e].t)}},error:function(){for(var a in f.a)b.error(f.a[a].t)}});for(c in f.a)(function(a){setTimeout(function(){$("#checkstatus_"+a).attr("class")==="check-spinner"&&b.error(a)},f.timeout)})(f.a[c].t)};j.prototype.I=function(a){$("#checkstatus_"+a).css("display","block").attr("class","check-spinner")};j.prototype.N=function(a){$("#checkstatus_"+a).attr({"class":"check-ok",title:e("Link is OK")})};j.prototype.G=function(a){$("#checkstatus_"+
a).attr({"class":"check-broken",title:e("Link is broken")})};j.prototype.error=function(a){$("#checkstatus_"+a).attr({"class":"check-error",title:e("Error checking file. Please try again later.")})};var C=function(){var a={url:global_path+"getwatchherecontent.html"};return function(c,b){function e(){for(var a in f){var c=parseInt(a);$(f[a]).hide();$("a[id='quick_embed_button_%d']".replace("%d",c)).show();$("a[id='hide_embed_button_%d']".replace("%d",c)).hide()}}$.extend({},a,b||{});var f=[],k=[];
return{bind:function(){$(c).find(".videoresult").each(function(a){var c=this,b="#quick_embed_%d".replace("%d",a);f.push(b);$(this).find("a[id='quick_embed_button_%d']".replace("%d",a)).bind("click.embed",function(d){d.preventDefault();var f=$(this).attr("id");e();$(b).show();$("a[id='quick_embed_button_%d']".replace("%d",a)).hide();$("a[id='hide_embed_button_%d']".replace("%d",a)).show();k.indexOf($(this).attr("id"))===-1&&$.ajax({type:"post",url:global_path+"getwatchherecontent.html",data:{v_t:$(c).attr("id")},
success:function(a){$(b).html(a);k.push(f)}})});$(this).find("a[id='hide_embed_button_%d']".replace("%d",a)).bind("click.embed",function(a){a.preventDefault();e()})})}}}}(),E=function(){return function(){function a(a){$.ajax({url:b+a,dataType:"jsonp",success:function(c){if(c.success){c.count>g&&$("#js_files_list").prepend($("<tr></tr>").append($('<td colspan="4"></td>').addClass("harmWarning").text(e("Warning - These files may harm your computer."))));var b=$("<div>").addClass("harmButton");c.voted===
0&&$("#d_clip_container").prepend(b.text(e("Report harmful files")).click(function(){b.unbind("click");$.ajax({url:f,dataType:"jsonp",data:{token:a},success:function(a){if(a.voted===1){b.removeClass("harmButton");b.addClass("harmButtonOff");b.css("color","green").text(e("Thank you for reporting"))}else{b.removeClass("harmButton");b.addClass("harmButtonOff");b.text(e("An error occured, please try again later"))}}})}))}}})}var c=FT.Options.reportsChecker.enabled,b=FT.Options.reportsChecker.server,g=
FT.Options.reportsChecker.limit,f=FT.Options.reportsChecker.votes_server;return{check:function(b){c&&a(b)}}}}(),u=function(){var a={theme:"white",ka:{la:e("Type the two words")}};return{bind:function(){$("#commentSubmit").bind("click",u.submit);$("#commentRecaptcha").each(function(){u.K(this)});$("#commentsPagination .page").live("click",function(){$("#commentsLoader").show();$("#commentsContainer").load(global_path+"file/comment/get.json",{token:$("#fileCommentForm").children("input[name=token]").val(),
page:this.className.match(/page_(\d+)/)[1]},function(){$("#commentsLoader").hide()});return m})},submit:function(){$.ajax({url:global_path+"file/comment/submit.json",type:"POST",data:$("#fileCommentForm").serialize(),dataType:"json",beforeSend:function(){$("#submitCommentInfo").empty().append($("<span></span>").html("Submitting ...")).append($("<img />").addClass("commentsLoader").attr("src",static_path+"images/ajax-loader.gif")).show()},success:function(a){if(a.success){$("#submitCommentInfo").empty().hide();
$("#commentAuthor,#commentText").val("");var b=$("#commentsCount").html();$("#commentsContainer").load(global_path+"file/comment/get.json",{token:$("#fileCommentForm").children("input[name=token]").val(),page:1},function(){if($("#commentsCount").html()==b){var e=a.date_added,f=a.author,k=a.comment,j=$("<div></div>").addClass("homeCommBox"),e=$("<div></div>").addClass("homeCommBox1").append($("<img />").attr("src",static_path+"images/comm_icon.gif").addClass("commentIcon")).append($("<b></b>").addClass("commentAuthor").html(f)).append($("<span></span>").addClass("commentDate").html(" ("+
e+")"));j.append(e).append($("<div></div>").addClass("homeCommAct").html(k)).append($("<div></div>").addClass("homeCommActend"));$("#commentsField").prepend(j);$("#commentsCount").html(parseInt($("#commentsCount").html())+1);$("#commentsCountInfo").show()}});u.K($("#commentRecaptcha").get(0))}else $("#submitCommentInfo").empty().append($("<span></span>").html("Error : "+a.message))}})},K:function(b){typeof Recaptcha!="undefined"&&Recaptcha.create(recaptcha_public_key,b,a)}}}();$(r).ready(function(){B.bind();
C(".other_adv").bind();$(".trends").ba();$("body").bind("click",function(){$("#languagemenu, #shortcutmenu").hide()});$(".openx_ad").each(function(){var a=this.id.match(/openx_ad_(\d+)/);$(this).attr("src","http://ads.carocean.co.uk/delivery/afr.php?zoneid="+a[1])});typeof alternatives!="undefined"&&alternatives.R=="js"&&alternate_files.length>0&&alternatives.da();u.bind()});b.showShortcutLinks=function(){var a=$("#shortcutmenu");if(a.is(":visible"))a.hide();else{var b=$("#shortcut_link").position(),
d=$("#shortcut_link").outerHeight();a.css({top:b.top+d+10,left:b.left}).show()}};b.showHideRecentSearches=function(){var a=$("#recent");if(a.length!==0){a.toggle();q("DISPLAY_RECENT_SEARCHES",a.is(":visible")===h?1:0,365,"/")}};b.cloakRecentSearches=function(){var a=$("#recent");a.length!==0&&a.hide()};b.display_mini_msg=function(){$.ajax({url:global_path+"messages/getcount",method:"post",dataType:"json",success:function(a){a.status.match(/error/);if(a.status.match(/ok/)){var b="("+a.newmsg+"/"+a.allmsg+
")";parseInt(a.newmsg)>0&&(b=b+(' <img class="imgfix" src="'+static_path+'images/newmsg.gif" title="'+e("New messages")+'" />'));$("#new_messages_count").html(b)}a.status.match(/db_exception/)}})};b.feedbackForm=function(){b.open(global_path+"feedback.html","_blank","width=670,height=490,left="+((b.screenX||b.screenLeft)+50)+",top="+((b.screenY||b.screenTop)+50)+",resizable=falsechannelmode=0,directories=0,fullscreen=0,location=0,menubar=0,scrollbars=0,toolbar=0,titlebar=0")};b.translationForm=function(){b.open(global_path+
"translation/main.html","_blank","width=700,height=650,left="+((b.screenX||b.screenLeft)+50)+",top="+((b.screenY||b.screenTop)+50)+",resizable=falsechannelmode=0,directories=0,fullscreen=0,location=0,menubar=0,scrollbars=1,toolbar=0,titlebar=0")};b.showLanguageMenu=function(){var a=$("#languagemenu");if(a.css("display")=="none"){var b=$("#language_link"),d=b.offset();d.left=d.left-28;d.top=d.top+b.height();a.css({top:d.top,left:d.left})}a.toggle()};b.changeLanguage=function(a){b.location=global_path+
"account/change_language/"+a};b.Autocompleter=B;b.showFFExtension=function(){typeof b.sidebar=="object"&&typeof b.sidebar.D=="function"&&!z("FFhide")&&$("#addFFExtension").css("display","inline")};b.hideFFExtension=y;b.addEngine=function(){if(typeof b.sidebar=="object"&&typeof b.sidebar.D=="function"){b.sidebar.D("http://www.filestube.com/images/filestube.xml","http://www.filestube.com/images/filestube.png","FilesTube.com",e("FilesTube.com - Every search is a direct hit"));y()}else confirm(e("Search extensions are supported with Firefox"))&&
b.open("http://firefox.com")};b.checkFFCookie=z;b.getCookie=w;b.SetCookie=q;b.resultsLeftShowSwitch=function(a){var b=$("#results_left"),d=$("#results"),g=$("#results_box"),f=$("#toggle");if(b.is(":visible")){b.hide();d.css("width","651px");g.css("width","986px");f.text(e("Show filters")).css("background-position","left 1px");q("DISPLAY_RESULTS_LEFT","0",365,"/")}else{if($("#results_left").html().indexOf("hosting_all")==-1)$.ajax({url:global_path+"/getfilters.html"+a,method:"post",success:function(a){$("#results_left").html(a);
b.show();d.css("width","505px");g.css("width","840px");f.text(e("Hide filters")).css("background-position","left -17px")}});else{b.show();d.css("width","505px");g.css("width","840px");f.text(e("Hide filters")).css("background-position","left -17px")}q("DISPLAY_RESULTS_LEFT","1",365,"/")}};b.switchMoreHostingFilters=function(a){$("#moreHostingFilters").css("display",a==0?"none":"inline");$("#moreHostingFiltersLink").html(e(a==0?"more":"less")+"...").attr("href","javascript:switchMoreHostingFilters("+
!a+");")};b.applyHostingFilters=function(){var a=[],c=0;$("input[type='checkbox'][class='hosting_checkbox']").each(function(){var b=$(this);c++;b.attr("checked")&&a.push(b.attr("id").substring(17))});var d=b.location.href.replace(/hosting=[^\/&]+/i,a.length>0&&a.length<c?"hosting="+a.join(","):"");b.location.replace(d)};b.toogleHostingFilter=function(a){checkbox=$("#hosting_checkbox_"+a);checkbox.length>0&&checkbox.attr("checked",!checkbox.attr("checked"))};b.invertHostingFilters=function(){$("input[type='checkbox'][class='hosting_checkbox']").each(function(){$(this).attr("checked",
!$(this).attr("checked"))})};b.clearHostingFilters=function(){$("input[type='checkbox'][class='hosting_checkbox']").each(function(){$(this).attr("checked",m)})};b.showSizeFilter=function(){$("#size_filter_custom").show()};b.applySizeFilter=function(){var a=Math.pow(2,21),c=$("#size_filter_from"),d=$("#size_filter_to"),g=$("#size_filter_from_error").hide(),f=$("#size_filter_to_error").hide();error=m;if(/[^\d]+/.test(c.val())||parseInt(c.val())>a){g.text(e("Enter correct size")).show();error=h}if(/[^\d]+/.test(d.val())||
parseInt(d.val())>a||parseInt(d.val())==0){f.text(e("Enter correct size")).show();error=h}if(!error&&parseInt(c.val())>parseInt(d.val())){f.text(e("Invalid range")).show();error=h}if(!error){a=b.location.href;a=a.replace(/#.+/,"");a=/sizefrom=[^\/&]+/i.test(a)?a.replace(/sizefrom=[^\/&]+/i,"sizefrom="+c.val()):a+("&sizefrom="+c.val());a=/sizeto=[^\/&]+/i.test(a)?a.replace(/sizeto=[^\/&]+/i,"sizeto="+d.val()):a+("&sizeto="+d.val());b.location.replace(a)}};b.checkDYM=function(a){a=sp_server+"/"+encodeURIComponent(a)+
"?callback=?";sp_params!=s&&sp_params!=""&&(a=a+("&"+sp_params));$.ajax({url:a,dataType:"jsonp",success:function(a){if(a.corrected!=""){var b=$("#DYMfield");$("#corrected_addr").empty().append($("<a>").css("font-weight","bold").attr("href",global_path+"search.html?q"+a.corrected.replace(/\s+/g,"+")).text(a.corrected));b.show()}}})};b.add_to_downloads_history=A;b.history_autosave=function(a,b,d){a==1&&!b&&A(d)};b.jumpto_groupfile=function(a){b.location=global_path+a.options[a.selectedIndex].value+
"/go.html"};b.report_broken_link=function(a){var b=$("#broken_div_"+a);b.empty().append($("<img>").attr("src",static_path+"images/ajax-loader.gif"));$.ajax({url:global_path+"ajax_report_broken_link.html?link_id="+a,timeout:1E4,success:function(a){(a.match(/ok/)||a.match(/error/))&&b.empty().append($("<span></span>").css({color:"green","font-weight":"normal","margin-bottom":"5px"}).text(e("Thanks for reporting")))}})};b.report_passworded_file=function(a,b){var d;d=b==s?$("#passworded_div_"+a):$("#fileInfo_password");
d.empty().append($("<img>").attr("src",static_path+"images/ajax-loader.gif"));$.ajax({url:global_path+"ajax_report_passworded_file.html?link_id="+a,timeout:1E4,success:function(a){a.match(/ok/)&&d.empty().append($("<span>").css({color:"green","font-weight":"normal","margin-bottom":"5px"}).text(e("Thanks for reporting")))}})};b.Stars=D;b.initCopyToClipboard=function(){var a=new ZeroClipboard.Client;a.setHandCursor(h);a.setCSSEffects(h);a.addEventListener("mouseDown",function(){a.setText($("#copy_paste_links").html());
$("#d_clip_msg_copied").show();setTimeout(function(){$("#d_clip_msg_copied").hide()},2E3)});a.glue("d_clip_button","d_clip_container")};b.Alternatives=n;n.prototype.checkFilesAternativesExists=n.prototype.Y;n.prototype.getAlternatives=n.prototype.ca;b.clearSearchField=function(a,b){$(a).val()==b&&$(a).val("")};b.Checker=j;j.prototype.addToken=j.prototype.Q;j.prototype.checkApi=j.prototype.W;j.prototype.checkAllFiles=j.prototype.V;b.Embeds=C;b.toggleDescription=function(a,b){$("#desc_short_"+a)[b===
1?"hide":"show"]();$("#desc_full_"+a)[b===1?"show":"hide"]()};b.clear_downloads_history=function(a){$("#ajax_confirmation").hide();$("#timezone_confirmation").hide();if(confirm(e("Do you really want to clear your downloads history?"))){$("#settings_indicator").css("display","inline");$.ajax({url:global_path+"account/ajax_clear_downloads_history.html",type:"post",data:{uid:a},dataType:"json",success:function(a){if(a=="not logged")b.location=global_path+"account/login.html?continue="+b.location;else if(a==
"error")alert(e("Error - your downloads history hasn't been cleared"));else if(a=="db_error")alert(e("Database error - your downloads history hasn't been cleared"));else if(a=="ok"){$("#ajax_confirmation").text(e("Your downloads history has been cleared")).show();$("#settings_indicator").hide()}}})}};b.confirmAvatarRemove=function(a){if(confirm(e("Removing avatar. Are you sure?")))b.location=a;return m};b.showMessageForm=function(){var a=$("#messageform");a.css("display","block").css({left:($(b).width()-
a.width())/2+$(b).scrollLeft(),top:($(b).height()-a.height())/2+$(b).scrollTop(),visibility:"visible"});$("#messageform_content").show();$("#messageform_error").hide();$("#messageform_sendbutton").attr("disabled",m);$("#messageform_title").val("");$("#messageform_body").val("")};b.closeMessageForm=function(){$("#messageform").css({visibility:"hidden",display:"none"})};b.sendUserMessage=function(){var a=$("#messageform_username").val(),b=$("#messageform_error"),d=$("#messageform_sendbutton").attr("disabled",
h),g=$("#messageform_title").val(),f=$("#messageform_body").val();b.css({display:"block",visibility:"visible"}).empty().append($("<img>").attr("src",static_path+"images/ajax-loader.gif"));$.ajax({type:"post",url:global_path+"user/message/"+a+".plain",data:{subject:g,content:f},success:function(a){if(a=="ok")b.css({display:"block",visibility:"visible"}).empty().append($("<span>").css("color","green").text(e("Your message has been sent.")));else{d.attr("disabled",m);b.css({display:"block",visibility:"visible"}).empty().append($("<span>").css("color",
"red").text(e("Do not leave the message subject and/or message body empty. Subject length is limited to 100 characters, body length is limited to 1000 characters.")))}},error:function(){d.attr("disabled",m);b.css({display:"block",visibility:"visible"}).empty().append($("<span>").css("color","red").text(e("There was an error while trying to send the message.")))}})};b.trendsCalendar={elements:i,o:i,g:i,b:i,P:i,J:i,l:10,page:1,z:0,w:1,v:2,c:0,aa:"cal_t",Z:"cal_b",ja:"cal_tn",ia:"cal_bn",type:i,init:function(a,
b){this.type=b;this.o=20;this.elements=parseInt(a);$("#trends_calendar_container").css("height",this.U());this.b=Math.ceil(this.elements/this.l);this.P=$("#buttonup");this.J=$("#buttondown");var d=w("trends_calendar_page_"+this.type);typeof d=="undefined"||d==i?this.b>1&&this.e(h):this.ea(d>this.b?this.b:d)},U:function(){this.g=$("#trends_calendar_content");return this.o*this.l+"px"},buttonUp:function(){if(!this.O()){this.ga();this.e(h);q("trends_calendar_page_"+this.type,this.page,1,"/");this.O()&&
this.j(m)}},buttonDown:function(){if(!this.F()){this.fa();this.j(h);q("trends_calendar_page_"+this.type,this.page,1,"/");this.F()&&this.e(m)}},ga:function(){this.g.css("top",parseInt(this.g.css("top"))+this.o*this.l+"px");--this.page;this.c=this.page==1?this.z:this.w},fa:function(){this.g.css("top",parseInt(this.g.css("top"))-this.o*this.l+"px");++this.page;this.c=this.page==this.b?this.v:this.w},ea:function(a){if(!(a>this.b)){this.g.css("top",-(this.o*this.l*(a-1))+"px");this.page=parseInt(a);if(this.b==
1){this.j(m);this.e(m)}else switch(this.page){case 1:this.c=this.z;this.j(m);this.e(h);break;case this.b:this.c=this.v;this.e(m);this.j(h);break;default:this.c=this.w;this.j(h);this.e(h)}}},O:function(){return this.b==1?h:this.c==this.z?h:m},F:function(){return this.b==1?h:this.c==this.v?h:m},j:function(a){this.P.toggleClass(this.aa,a)},e:function(a){this.J.toggleClass(this.Z,a)}};b.ReportsChecker=E;b.FT=FT;b.toggleSourceTitle=function(a,b){if(b==1){$("#sti_"+a).attr("src",static_path+"images/alt_minus.gif");
$("#sta_"+a).attr("href","javascript:toggleSourceTitle('"+a+"',0)")}else{$("#sti_"+a).attr("src",static_path+"images/alt_plus.gif");$("#sta_"+a).attr("href","javascript:toggleSourceTitle('"+a+"',1)")}$("#st_"+a).slideToggle(200)};b.Comments=u;b.renderGo=function(a){/msie/i.test(navigator.userAgent)&&!/opera/i.test(navigator.userAgent)?b.open(a):b.open('data:text/html,<html><meta http-equiv="refresh"; content="0; url='+a+'"></html>')}})(window,document,Array);
