// Generated by CoffeeScript 1.4.0
(function() {

  (function() {
    var $, active_subnav_home, get_path_from_href, placeholder_fix, populate_spotlights, remove_topnav_shadow, set_active_nav;
    $ = jQuery;
    get_path_from_href = function(href) {
      var path, start_i, start_path;
      start_i = href.indexOf('//') !== -1 ? href.indexOf('//') + 2 : 0;
      start_path = href.indexOf('/', start_i) !== -1 ? href.indexOf('/', start_i) : href.length;
      path = href.substring(start_path);
      return path = path === '' ? '/' : path;
    };
    set_active_nav = function() {
      var $nav_item, $primary_nav_items, idx, link_path, nav_item, path, pathname, _i, _len, _ref;
      $primary_nav_items = $('.primary_nav > li');
      path = window.location.pathname.split("/");
      pathname = "/" + path[1] + "/";
      _ref = $primary_nav_items.not(':first-child');
      for (idx = _i = 0, _len = _ref.length; _i < _len; idx = ++_i) {
        nav_item = _ref[idx];
        idx += 1;
        $nav_item = $(nav_item);
        link_path = get_path_from_href($nav_item.children('a').eq(0).attr('href'));
        if (path.length && pathname !== "//") {
          if (link_path === pathname) {
            $primary_nav_items.removeClass('active');
            return $nav_item.addClass('active');
          }
        }
      }
    };
    set_active_nav();
    active_subnav_home = function() {
      var path, section;
      path = window.location.pathname.split("/");
      section = path[1];
      if (section.length) {
        if (path[2] && path[2].length < 1) {
          return $('.' + section + '.active .secondary_nav > li:first-child a').addClass('active');
        }
      }
    };
    active_subnav_home();
    remove_topnav_shadow = function() {
      var url;
      url = window.location.pathname.split("/");
      if (url[2] !== "" || null) {
        if (url[2] === "national_geographic_channel" || "nat_geo_wild") {
          return $('#navigation_tophat_container').css("box-shadow", "none");
        }
      }
    };
    remove_topnav_shadow();
    populate_spotlights = function() {
      return $(".primary_nav > li > a").each(function(index) {
        var section;
        section = $(this).text().toLowerCase();
        if (section !== "home") {
          return $.ajax({
            url: "http://channel.nationalgeographic.com/include/nav_spotlight/",
            dataType: "jsonp",
            cache: true,
            jsonpCallback: section,
            success: function(data, status, jqXHR) {
              return $("." + section + " > .sub_nav > .spotlight").replaceWith(data.html);
            },
            error: function(jqXHR, textStatus, err) {
              if (window.console && window.console.error) {
                return window.cosole.error(err);
              }
            }
          });
        }
      });
    };
    populate_spotlights();
    placeholder_fix = function() {
      var input;
      input = document.createElement("input");
      if (("placeholder" in input) === false) {
        return $("[placeholder]").focus(function() {
          var i;
          i = $(this);
          if (i.val() === i.attr("placeholder")) {
            i.val("").removeClass("placeholder");
            if (i.hasClass("password")) {
              i.removeClass("password");
              return this.type = "password";
            }
          }
        }).blur(function() {
          var i;
          i = $(this);
          if (i.val() === "" || i.val() === i.attr("placeholder")) {
            if (this.type === "password") {
              i.addClass("password");
              this.type = "text";
            }
            return i.addClass("placeholder").val(i.attr("placeholder"));
          }
        }).blur().parents("form").submit(function() {
          return $(this).find("[placeholder]").each(function() {
            var i;
            i = $(this);
            if (i.val() === i.attr("placeholder")) {
              return i.val("");
            }
          });
        });
      }
    };
    return placeholder_fix();
  })();

}).call(this);
