var ATT_VIDEO=function(){var d=[],e=null,f=null,c={},f=this.set=function(b,a){var g=null;if("string"===typeof b&&"undefined"!==typeof a){c[b]||(c[b]={binders:[]});c[b].value=a;for(g=0;c[b].binders.length>g;g++)if("function"===typeof c[b].binders[g])c[b].binders[g](a);else c[b].binders[g]=a}},e=this.get=function(b,a){if("undefined"!==typeof b){c[b]||(c[b]={binders:[]});if("undefined"!==typeof a&&(c[b].binders.push(a),"undefined"!==typeof c[b].value))if("function"===typeof c[b].binders[c[b].binders.length-
1])c[b].binders[c[b].binders.length-1](c[b].value);else c[b].binders[c[b].binders.length-1]=c[b].value;return c[b].value}};this.clear=function(){var b=null;for(b in c)c[b].value=void 0};mix=this.mix=function(b){var a=null;for(a in b)f(a,b[a])};this.access=function(b,a){var g=null;if("string"===typeof b&&"undefined"!==typeof a)f(b,a);else{if("string"===typeof b)return e(b);if("undefined"===typeof b&&"undefined"===typeof a){var d={};for(g in c)d[g]=c[g].value;return d}}};this.sendSignal=function(b){for(var a=
null,a=0;d.length>a;a++)d[a].name===b&&d[a].handler.apply(this,Array.prototype.slice.call(arguments,1))};this.listenForSignal=function(b,a){for(var g=null,g=d.length-1;0<=g;g--)d[g].name===b&&d[g].handler===a&&d.splice(g,1);d.push({name:b,handler:a})};this.version="3.1.0";this.reusable=!0;this.extension=function(b,a){function g(a){var b=null;if("function"===typeof a)b=new a;else for(h in b={},a)b[h]=a[h];return b}function c(a){var b=null;for(h=0;o.length>h;h++)o[h]===a&&(b=h);null===b&&(o.push(a),
b=o.length-1);return b}var e=this,d=g(this),f=null,o=[],j=[],h=null;if("function"===typeof b)f=function(a){var h=null;j[c(a)]?j[c(a)].reusable||(h=b.apply(d,arguments)):(d=g(e),h=b.apply(d,arguments),j[c(a)]=d);var n=d;d.reusable||(d=g(e),f.prototype=d,f.prototype.constructor=d);if(this.constructor!==f)return h?h:n},f.prototype=d,f.prototype.constructor=d,a&&(f=f());else if("object"===typeof b){for(h in d)b[h]=d[h];f=b[h]}return f}};ATT_VIDEO.extension=(new ATT_VIDEO).extension;
ATT_VIDEO.DEBUG=ATT_VIDEO.extension(function(){var d=null,e=null,f={active:!1,output:function(c){null===d&&(d=ATT_VIDEO.UTILITIES.parseQueryString().gvpDebug);d&&(f.active=!0);f.active&&(e||(e=jQuery('<div id="gvpDebuggerUI" style="position:fixed;z-index:9999999;background:#999999;top:0px;left:0px;"/>'),jQuery("body").append(e)),15<e.children().length&&e.children().eq(0).remove(),e.append('<div style="color:#FFFFFF;font-size:20px;">'+c+"<br/></div>"),"undefined"!==typeof console&&console.log(c))}};
return f},!0);
ATT_VIDEO.METADATA=ATT_VIDEO.extension(function(d){function e(a){var b=null,g=null,h=a.response.numFound,p=null;if(h){b=a.response.docs[0];g={};jQuery.extend(g,b);if(b&&"video"===b.type){var c=null;if(b.videoStartVars){c={};for(p=0;p<b.videoStartVars.length;p++)c[b.videoStartVars[p].split("=")[0]]=b.videoStartVars[p].split("=")[1]}g.id=b.id||"";g.title=b.emd_windowTitle||b.windowTitle_en||"";g.thumbTitle=b.thumbTitle_en||"";g.thumbIcon=b.url_thumbIcon_en?k.prependProtocol(b.url_thumbIcon_en):"";g.duration=
b.lengthInSeconds?ATT_VIDEO.UTILITIES.TIME.timecodeToSeconds(b.lengthInSeconds):"";g.captions=b.captionData_en||"";g.description=b.description_en||b["emd_description-long"]||"";g.availability=b.emd_availability||"";g.date=function(){var a=g.creationDate.split("T")[0].split("-");return a[2]+"-"+a[1]+"-"+a[0]}()||"";g.campaign=b.campaignCode||"";g.legal=b.emd_legal||b.legal||"";var e=g,d;d=c.posterImg?k.prependProtocol(k.URL.POSTER_IMAGES+c.posterImg+"?"+Math.random()):k.html5Mode?k.URL.DEFAULT_POSTER_IMAGE_MOBILE:
"";e.poster=d;g.url=g.source=function(){var a="";if(k.html5Mode){a=k.prependProtocol(k.URL.CDN_MOBILE+(b.url_videoMain_en.indexOf("gvp/")!=-1?b.url_videoMain_en.split("gvp/")[1]:b.url_videoMain_en));a.indexOf(".f4v")&&(a=a.replace(".f4v",".mp4"));if(c){typeof c.url_videoMobile!=="undefined"&&(a=k.prependProtocol(k.URL.CDN+(c.url_videoMobile.indexOf("gvp/")!=-1?c.url_videoMobile.split("gvp/")[1]:c.url_videoMobile)));typeof c.url_videoMobileHLS!=="undefined"&&(a=k.prependProtocol(k.URL.CDN+(c.url_videoMobileHLS.indexOf("gvp/")!=
-1?c.url_videoMobileHLS.split("gvp/")[1]:c.url_videoMobileHLS)));if(g.id=="2000080"){a=k.prependProtocol(k.URL.CDN+(c.url_videoMobile.indexOf("gvp/")!=-1?c.url_videoMobile.split("gvp/")[1]:c.url_videoMobile));a=a.replace(".mp4","/gvp_Samsung-Captivate-Address-Book_512x288.m3u8")}}}else a=k.prependProtocol(k.URL.CDN+(b.url_videoMain_en.indexOf("gvp/")!=-1?b.url_videoMain_en.split("gvp/")[1]:b.url_videoMain_en));return a}();g.related=function(){var b=[];for(p=1;p<h;p++)b.push({id:a.response.docs[p].id||
"",thumb:a.response.docs[p]?k.prependProtocol(a.response.docs[p].url_thumbIcon_en):"",title:a.response.docs[p].thumbTitle_en||"",description:a.response.docs[p].description_en||"",duration:a.response.docs[p].lengthInSeconds||""});return b}();e=g;b.bannerId&&l(b.bannerId,"banner");e.bannerId=b.bannerId||""}else b&&"banner"===b.type&&(g.bannerId=b.bannerId||m.bannerId||"",g.promo=b.bannerLayoutAndContent||"",g.bannerTitle=b.bannerTitle||"");m.mix(g);m.sendSignal(ATT_VIDEO.METADATA.UPDATE)}else m.sendSignal(ATT_VIDEO.METADATA.ERROR)}
function f(){g.length&&"waiting"!==ATT_VIDEO.METADATA.status&&(ATT_VIDEO.METADATA.status="waiting",jQuery.ajax&&jQuery.ajax({url:a+g[0].action,dataType:"jsonp",jsonp:"json.wrf"}))}function c(a){ATT_VIDEO.METADATA.status="";g.shift();e(a);f();g.length||(b&&(gvp.getMetaData_success=b),b=null)}ATT_VIDEO.METADATA.status=null;ATT_VIDEO.METADATA.ERROR="ATT_VIDEO.METADATA.ERROR";ATT_VIDEO.METADATA.UPDATE="ATT_VIDEO.METADATA.UPDATE";ATT_VIDEO.METADATA.REQUEST="ATT_VIDEO.METADATA.REQUEST";var b=null,a=null,
g=[],k=ATT_VIDEO.UTILITIES,m=this;this.queue=[];this.isWaiting=m.isWaiting=function(){return ATT_VIDEO.METADATA.status.length?!0:!1};var l=this.request=function(e,d){ATT_VIDEO.DEBUG.output("ATT_VIDEO.METADATA :: data requested for "+e);m.sendSignal(ATT_VIDEO.METADATA.REQUEST);var k=null;d||(d="video");a=""===ATT_VIDEO.UTILITIES.URL.ENV||-1===ATT_VIDEO.UTILITIES.URL.ENV.indexOf("att.com")||-1===ATT_VIDEO.UTILITIES.URL.DOMAIN.indexOf("att.com")?ATT_VIDEO.UTILITIES.prependProtocol("//www.att.com/navservice/videoservice/"):
-1!==ATT_VIDEO.UTILITIES.URL.DOMAIN.indexOf("ecom.cingular.net")?ATT_VIDEO.UTILITIES.prependProtocol("//www.att.com/navservice/videoservice/"):ATT_VIDEO.UTILITIES.URL.DOMAIN+"/navservice/videoservice/";"undefined"===typeof gvp&&(window.gvp={});!b&&gvp.getMetaData_success&&(b=gvp.getMetaData_success);gvp.getMetaData_success=c;k="xml"!==e.slice(e.length-3,e.length)?"id":"url_configFile_en";"url_configFile_en"===k&&(e="/media/gvp/"+e);g.push({type:d,action:"video"===d?"select?q="+k+":"+e+"%20OR%20_query_:%22{!join%20from=relatedVideoId%20to=id%20v=$qq}%22&qq={!join%20from=relatedVideoGroupingIds%20to=id}"+
k+":"+e:"select?q="+k+":"+e});f()};"string"===typeof d&&l(d)});ATT_VIDEO.MOBILE_VIDEO={};ATT_VIDEO.MOBILE_VIDEO.ajaxLoaderImgPath="http://www.att.com/images/global/ajaxLoader.gif";ATT_VIDEO.MOBILE_VIDEO.noVideoImgPath="http://www.att.com/media/gvp/global_resources/defaultMedia/GVP_iPhone_noVideo.jpg";ATT_VIDEO.MOBILE_VIDEO.posterPath="http://www.att.com/media/gvp/global_resources/defaultMedia/GVP_iPhone.jpg";ATT_VIDEO.MOBILE_VIDEO.videoElementId="currEmbStream";
ATT_VIDEO.MOBILE_VIDEO.VideoPlayer=function(){function d(a,b){ATT_VIDEO.METADATA(a).get("poster",function(a){ATT_VIDEO.MOBILE_VIDEO.posterPath=a});ATT_VIDEO.METADATA(a).get("url",b)}function e(b,c){var e=document.createDocumentFragment(),d=document.createElement("video");d.setAttribute("id",ATT_VIDEO.MOBILE_VIDEO.videoElementId);d.setAttribute("style","display:block; position:absolute;");d.setAttribute("controls","controls");d.setAttribute("width","512");d.setAttribute("height","288");d.setAttribute("poster",
c);var f=document.createElement("source");f.setAttribute("src",b);ATT_VIDEO.UTILITIES.isAndroid||f.setAttribute("type","video/mp4");ATT_VIDEO.UTILITIES.isIOS&&f.setAttribute("onsuspend","gvp.mobile.iosOnSuspend();");var o=document.createElement("img");o.setAttribute("id","gvp_loadImg");o.setAttribute("src",ATT_VIDEO.UTILITIES.URL.LOADER_GRAPHIC);o.setAttribute("style","display:block; position:absolute; margin:122px 0 0 234px;");d.appendChild(f);d.appendChild(o);e.appendChild(d);(ATT_VIDEO.UTILITIES.isAndroid||
ATT_VIDEO.UTILITIES.isMSPhone)&&d.addEventListener("click",function(){d.play()},!0);a.attachMediaEventListeners(d);return e}function f(a){a=e(a,ATT_VIDEO.MOBILE_VIDEO.posterPath);ATT_VIDEO.UTILITIES.DEPTH_MANAGER.enterFullScreen(a)}function c(a){a=e(a,ATT_VIDEO.MOBILE_VIDEO.posterPath);b.modalDialogDiv.appendChild(a)}var b=this,a="";b.insertVideoElemInPage=function(b){a=new ATT_VIDEO.MOBILE_VIDEO.TrendReport(b);d(b,f)};b.insertVideoElemInModal=function(g,e){b.modalDialogDiv=e;a=new ATT_VIDEO.MOBILE_VIDEO.TrendReport(g);
d(g,c)}};ATT_VIDEO.MOBILE_VIDEO.DeviceData=function(){this.isDeviceScreenSmall=function(){var d=window.devicePixelRatio;ATT_VIDEO.UTILITIES.isMicrosoft&&(d=2);var e=window.screen.width,f=window.screen.height;return 900>Math.sqrt(e*e+f*f)/d}};ATT_VIDEO.MOBILE_VIDEO.VideoData=function(){this.submitRequest=function(d,e,f){jQuery.ajax({url:"http://att.com/navservice/videoservice/select?q=id:"+d,success:f})}};
ATT_VIDEO.MOBILE_VIDEO.TrendReport=function(d){function e(a){q=a.timeStamp}function f(a){o=a.timeStamp-q}function c(){}function b(){}function a(){}function g(){}function k(){var a=document.getElementById(ATT_VIDEO.MOBILE_VIDEO.videoElementId);h=Math.floor(a.currentTime);j-h&&ATT_VIDEO.REPORTING(l).set("timeUpdate",h);j=h}function m(){ATT_VIDEO.REPORTING(l).set("loadTime",o);ATT_VIDEO.REPORTING(l).send()}var l=d,q=0,o=0,j=0,h=j;this.attachMediaEventListeners=function(h){h&&(h.addEventListener("loadstart",
e,!0),h.addEventListener("loadeddata",f,!0),h.addEventListener("play",c,!0),h.addEventListener("pause",b,!0),h.addEventListener("seeking",a,!0),h.addEventListener("seeked",g,!0),h.addEventListener("ended",function(){ATT_VIDEO.UTILITIES.DEPTH_MANAGER.exitFullScreen()},!0),h.addEventListener("timeupdate",k,!0),ATT_VIDEO.UTILITIES.isIOS&&h.addEventListener("webkitendfullscreen",function(){ATT_VIDEO.UTILITIES.DEPTH_MANAGER.exitFullScreen()},!0),ATT_VIDEO.UTILITIES.DEPTH_MANAGER.listenForSignal(ATT_VIDEO.UTILITIES.DEPTH_MANAGER.EXIT_FULL_SCREEN,
function(a){m&&m();a&&a.length&&a.remove()}))}};
ATT_VIDEO.REPORTING=ATT_VIDEO.extension(function(d){var e=this;ATT_VIDEO.REPORTING.IMPRESSION="impression";ATT_VIDEO.REPORTING.BAIL="bail";ATT_VIDEO.REPORTING.TRANSCRIPT="transcript";ATT_VIDEO.REPORTING.SEEK="seek";ATT_VIDEO.REPORTING.ACTION="action";ATT_VIDEO.REPORTING.RATING="rating";ATT_VIDEO.REPORTING.UNSUPPORTED="unsupported";ATT_VIDEO.REPORTING.ERROR="ERROR: problem with reporting system.";var f=this.send=function(b){b||(b=ATT_VIDEO.REPORTING.IMPRESSION);if(b===ATT_VIDEO.REPORTING.IMPRESSION)if("undefined"!==
typeof e.get("id")&&("undefined"!==typeof e.get("timeViewed")||"undefined"!==typeof e.get("attemptedPlay")))"undefined"!==typeof e.get("seekIn")&&null!==e.get("seekIn")&&("undefined"!==typeof e.get("seekOut")&&null!==e.get("seekOut"))&&(e.set("sectionViewed",e.get("seekOut")-e.get("seekIn")),f(ATT_VIDEO.REPORTING.SEEK));else{"undefined"!==typeof e.get("id")&&f(ATT_VIDEO.REPORTING.BAIL);return}ATT_VIDEO.DEBUG.output("STARTING REPORT of type= "+b);var a=jQuery.extend({},e.access());"undefined"!==typeof sessionVars&&
(a["DCSext.browserid"]=sessionVars.getCurrSessId());var c;c="";var d=document.getElementsByTagName("meta");if(d)for(var m=0;m<d.length;m++)"DCSext.wtZipCode"==d[m].name&&(c=d[m].content);c=c||jQuery("#globalnav_Zip").html();a["DCSext.wtZipCode"]=c;a["DCS.dcsua"]=window.navigator.userAgent;a["DCS.dcsref"]=window.location.href;a["DCS.dcssip"]=a.dcssip||window.location.hostname;a["DCS.dcsuri"]=a.dcsuri||window.location.pathname;a["DCSext.wtPN"]=a.title;a["DCSext.wtSuccessFlag"]="true";a["DCSext.wtStatusCode"]=
"Success";a["DCSext.wtMediaType"]="Video";a["DCSext.wtMediaFileId"]=a.id;a["DCSext.wtFileName"]=a.url;a["DCSext.wtVideoFriendlyName"]=a.title;a["DCSext.wtNoHit"]=1;a["DCSext.wtAppName"]=a.wtAppName||window.location.pathname.slice(0,window.location.pathname.indexOf("/",1));switch(b){case ATT_VIDEO.REPORTING.IMPRESSION:a["DCSext.wtMediaLoadTime"]=a.loadTime||"0";a["DCSext.wtLinkLoc"]=a.gvpLinkLoc||a.wtLinkLoc||"Body";a["DCSext.wtLinkName"]="Video_Impression";a["DCSext.wtEvent"]="Video_Requested";a["DCSext.wtStatusCode"]=
a.error||a["DCSext.wtStatusCode"];a["DCSext.wtMediaTimeMax"]=a.duration;a["DCSext.wtMediaTimeViewed"]="undefined"!==typeof a.timeViewed&&0<a.timeViewed?a.timeViewed:"0";a.features||(a.features={});a.features.TranscriptTab||(a.features.TranscriptTab="N");a.features.TranscriptPrint||(a.features.TranscriptPrint="N");a.features.TranscriptSearch||(a.features.TranscriptSearch="N");a.features.InfoTab||(a.features.InfoTab="N");a.features.ClosedCaption||(a.features.ClosedCaption="N");a.features.FacebookLike||
(a.features.FacebookLike="N");a.features.PauseClicks||(a.features.PauseClicks="0");a.features.Language=window.navigator.userLanguage||window.navigator.language;a["DCSext.wtMediaOptions"]="";for(var l in a.features)a["DCSext.wtMediaOptions"]+=l+"~"+a.features[l]+"|";a["DCSext.wtMediaOptions"]=a["DCSext.wtMediaOptions"].slice(0,a["DCSext.wtMediaOptions"].lastIndexOf("|"));a.shared&&(a["DCSext.wtShareMethod"]=a.shared);a["DCSext.wtSrcImp"]=(a.bannerId&&a.campaign?a.campaign:"")+(a.bannerId&&a.bannerTitle?
"~~"+a.bannerId+":"+a.bannerTitle:"");break;case ATT_VIDEO.REPORTING.BAIL:a["DCSext.wtMediaLoadTime"]=a.loadTime||"0";a["DCSext.wtLinkName"]="Default_Video_Load";a["DCSext.wtLinkLoc"]=a.gvpLinkLoc||a.wtLinkLoc||"Body";a["DCSext.wtEvent"]="Video_Default";a["DCSext.wtStatusCode"]=a.error||a["DCSext.wtStatusCode"];a["DCSext.wtMediaTimeMax"]=a.duration;a["DCSext.wtMediaTimeViewed"]=a.timeViewed||"0";a["DCSext.wtSrcImp"]=(a.bannerId&&a.campaign?a.campaign:"")+(a.bannerId&&a.bannerTitle?"~~"+a.bannerId+
":"+a.bannerTitle:"");break;case ATT_VIDEO.REPORTING.TRANSCRIPT:a["DCSext.wtEvent"]="Video_Transcript_Search";a["DCSext.wtTranscriptSearchCount"]=a.searchCount;a["DCSext.wtTranscriptSearchPhrase"]=a.searchPhrase;break;case ATT_VIDEO.REPORTING.SEEK:a["DCSext.wtEvent"]="Video_Navigation";a["DCSext.wtMediaStartTime"]=a.seekIn||"0";a.searchPhraseClicked&&(a["DCSext.wtTranscriptSearchPhrase"]=a.searchPhraseClicked);a["DCSext.wtMediaTimeViewed"]="undefined"!==typeof a.sectionViewed&&0<a.sectionViewed?a.sectionViewed:
"0";a["DCSext.wtMediaOptions"]=a.seekMethod?"NavMethod~"+a.seekMethod:"NavMethod~Timeline";break;case ATT_VIDEO.REPORTING.RATING:a["DCSext.wtEvent"]="Video_Feedback";a["DCSext.wtStarRating"]=a.rating;a["DCSext.wtRating"]=a.wtRating||a.feedback;a["DCSext.wtComments"]=a.wtComments||a.comments;break;case ATT_VIDEO.REPORTING.ACTION:a["DCSext.wtLinkLoc"]="Top"===a.gvpLinkLoc?"Top":"Bottom";a["DCSext.wtLinkName"]="BuyNow_Initiated";a["DCSext.wtEvent"]="BuyNow_Initiated";a["DCSext.Source"]=a.campaign;a["DCSext.wtExtndSource"]=
a.bannerId+":"+a.bannerTitle;a["DCSext.wtPN"]||delete a["DCSext.wtPN"];break;case ATT_VIDEO.REPORTING.UNSUPPORTED:a["DCSext.wtEvent"]="Video_Requested_Unsupported",a["DCSext.wtStatusCode"]=a.error||a["DCSext.wtStatusCode"]}delete a.timeUpdate;delete a.sectionViewed;delete a.gvpLinkLoc;delete a.wtAppName;delete a.id;delete a.url;delete a.title;delete a.duration;delete a.campaign;delete a.bannerId;delete a.bannerTitle;delete a.timeViewed;delete a.seekIn;delete a.seekOut;delete a.seekMethod;delete a.shared;
delete a.searchCount;delete a.searchPhrase;delete a.searchPhraseClicked;delete a.features;delete a.rating;delete a.feedback;delete a.comments;delete a.bannerTarget;delete a.error;delete a.loadTime;delete a.attemptedPlay;l="";for(l in a)"undefined"===typeof a[l]||""===a[l]?delete a[l]:-1===l.toLowerCase().indexOf("dcs")&&(c=a[l],d="DCSext."+l,delete a[l],a[d]=c);b!=ATT_VIDEO.REPORTING.RATING&&(delete a["DCSext.wtStarRating"],delete a["DCSext.wtRating"],delete a["DCSext.wtComments"]);c=[];for(l in a)c.push(l),
c.push(a[l]);ATT_VIDEO.DEBUG.output("Reporting Object: "+c);if("function"===typeof dcsMultiTrackTop)try{dcsMultiTrackTop.apply(this,c)}catch(q){ATT_VIDEO.DEBUG.output(ATT_VIDEO.REPORTING.ERROR+" - "+q)}else if("function"===typeof dcsMultiTrack)try{dcsMultiTrack.apply(this,c)}catch(o){ATT_VIDEO.DEBUG.output(ATT_VIDEO.REPORTING.ERROR+" - "+o)}else ATT_VIDEO.DEBUG.output(ATT_VIDEO.REPORTING.ERROR+" dcsMultiTrack not found.");b===ATT_VIDEO.REPORTING.SEEK&&(e.set("seekIn",null),e.set("seekOut",null),e.set("sectionViewed",
null));(b===ATT_VIDEO.REPORTING.IMPRESSION||b===ATT_VIDEO.REPORTING.BAIL)&&e.clear()};this.report=function(){f()};jQuery(window).bind("unload",function(){f()});jQuery(window).bind("pagehide",function(){f()});var c;this.get("timeUpdate",function(b){b=Math.round(b);"undefined"!=typeof c&&(c+1===b?(e.set("timeViewed",(e.get("timeViewed")||1)+1),e.set("seekOut",b)):c!==b&&("undefined"!==typeof e.get("seekIn")&&null!==e.get("seekIn")&&("undefined"!==typeof e.get("seekOut")&&null!==e.get("seekOut"))&&(e.set("sectionViewed",
e.get("seekOut")-e.get("seekIn")),f(ATT_VIDEO.REPORTING.SEEK)),c!==e.get("duration")&&e.set("seekIn",b)));c=b});(function(b){ATT_VIDEO.METADATA(b).listenForSignal(ATT_VIDEO.METADATA.REQUEST,function(){c=void 0;f()});ATT_VIDEO.METADATA(b).listenForSignal(ATT_VIDEO.METADATA.ERROR,function(){});ATT_VIDEO.METADATA(b).get("title",function(a){e.set("title",a)});ATT_VIDEO.METADATA(b).get("id",function(a){e.set("id",a)});ATT_VIDEO.METADATA(b).get("url",function(a){e.set("url",a)});ATT_VIDEO.METADATA(b).get("duration",
function(a){e.set("duration",a)});ATT_VIDEO.METADATA(b).get("campaign",function(a){e.set("campaign",a)});ATT_VIDEO.METADATA(b).get("bannerId",function(a){e.set("bannerId",a)});ATT_VIDEO.METADATA(b).get("bannerTitle",function(a){e.set("bannerTitle",a)})})(d)});ATT_VIDEO.SAMPLE_MODULE=ATT_VIDEO.extension(function(){},!1,"SAMPLE");
ATT_VIDEO.UTILITIES=ATT_VIDEO.extension(function(){var d="file:"===window.location.protocol?"http:":window.location.protocol,e=-1===window.location.hostname.indexOf("att.com")&&window.location.hostname.length?"www.att.com":window.location.hostname,f=/silk/i.test(navigator.userAgent),c=/iphone/i.test(navigator.userAgent),b=/ipad/i.test(navigator.userAgent),a=/ipod/i.test(navigator.userAgent),g=/android/i.test(navigator.userAgent);/chrome/i.test(navigator.userAgent);var k=/msie 6.0/i.test(navigator.userAgent),
m=/msie/i.test(navigator.userAgent),l=/windows phone os 8/i.test(navigator.userAgent),q=/windows phone os 7/i.test(navigator.userAgent),o=/windows CE/i.test(navigator.userAgent),j=l||q||o||/windows phone/i.test(navigator.userAgent),k=k||m||l||q||o;/symbianos/i.test(navigator.userAgent);/bb10/i.test(navigator.userAgent);m=/blackberry/i.test(navigator.userAgent);/tizen/i.test(navigator.userAgent);/bada/i.test(navigator.userAgent);/opera/i.test(navigator.userAgent);var h=/mobile/i.test(navigator.userAgent),
p=(h||c||j)&&!b&&!f,s=function(a){var h="";0===a.indexOf("http:")&&(a=a.replace("http:",""));0===a.indexOf("https:")&&(a=a.replace("https:",""));h=d+a;"https:"===d&&(-1<h.indexOf(n.CDN)&&(h=h.replace(n.CDN,n.CDN_SSL)),-1<h.indexOf(n.CDN_MOBILE)&&(h=h.replace(n.CDN_MOBILE,n.CDN_MOBILE_SSL)),-1<h.indexOf(n.POSTER_IMAGES)&&(h=h.replace(n.POSTER_IMAGES,n.POSTER_IMAGES_SSL)));return h},n={};n.ENV="file:"===window.location.protocol?"":s("//"+e+"/media/gvp/");n.CDN="//wpc.5BD7.att-acdn.net/005BD7/gvpVideos/gvp/";
n.CDN_MOBILE="//wpc.5BD7.att-acdn.net/005BD7/gvpVideos/gvp/mp4/";n.CDN_SSL="//gvpcertvideos.att.com/gvpVideos/gvp/";n.CDN_MOBILE_SSL="//gvpcertvideos.att.com/gvpVideos/gvp/mp4/";n.POSTER_IMAGES="//wpc.5BD7.att-acdn.net/005BD7/gvpVideos/gvp/posterImg/";n.POSTER_IMAGES_SSL="//wpc.5BD7.att-acdn.net/005BD7/gvpVideos/gvp/posterImg/";n.DEFAULT_POSTER_IMAGE_MOBILE=n.ENV+"/global_resources/defaultMedia/GVP_iPhone.jpg";n.LOADER_GRAPHIC=n.ENV+"view/images/ajaxLoader.gif";n.DOMAIN=e.length?s("//"+e):e;this.pixelRatio=
1;this.isMobile=h;this.isAndroid=g;this.isIOS=c||b||a;this.isMSPhone=j;this.isWinPhone8=l;this.isWinPhone7=q;this.isWinMobile6=o;this.isMicrosoft=k;this.isBlackBerry=m;this.isKindle=f;this.isSmallScreen=p;this.html5Mode=c||b||a||g||j||h;this.URL=n;this.prependProtocol=s;this.parseQueryString=function(a){var h="",b={},h=a?a:location.search.substring(1);if(h.length){a=h.split("&");for(h=0;h<a.length;h++){var c=a[h].split("=");b[unescape(c[0])]=2==c.length?unescape(c[1]):void 0}}return b}},!0);
ATT_VIDEO.UTILITIES.DEPTH_MANAGER=ATT_VIDEO.UTILITIES.extension(function(){function d(){if(b){var c=a.actualWidth,d=a.actualHeight,g=jQuery(window).width(),h=jQuery(window).height();e.isIOS&&(g>h?g-=2*k.outerWidth():h-=2*k.outerHeight());b.width(1<=c/d/(g/h)?g:h*(c/d));b.height(1>c/d/(g/h)?h:g*(d/c));b.css({position:"absolute",left:-b.width()/2+"px",top:-b.height()/2+"px"})}}this.ENTER_FULL_SCREEN="enter_full_screen";this.EXIT_FULL_SCREEN="exit_full_screen";var e=this,f=null,c=null,b=null,a=null,
g=null,k=null,m=null;this.enterFullScreen=function(q){q&&(b&&l(),f=jQuery('<div style="position:absolute;top:0px;left:0px;width:100%;height:100%;z-index:999999"/>'),c=jQuery('<div style="position:fixed;background:#000000;top:0px;left:0px;bottom:0px;right:0px;"/>'),g=jQuery('<div style="position:absolute;left:50%;top:50%;"/>'),k=jQuery('<img src="'+e.URL.ENV+'view/images/closeLarge.png" style="position:absolute;top:0px;right:0px;width:'+100/e.pixelRatio+"px;height:"+100/e.pixelRatio+'px;padding:10px;cursor:pointer;"/>'),
f.append(c),f.append(g),f.append(k),jQuery("body").append(f),k.bind("click",function(){l()}),c.bind("click",function(){l()}),g.append(q),b=g.children().eq(0),a={position:b.css("position"),left:b.css("left"),top:b.css("top"),width:b.css("width")||"",actualWidth:b.width(),height:b.css("height"),actualHeight:b.height()},ATT_VIDEO.DEBUG.active&&c.css({"border-style":"solid","border-width":"1px","border-color":"#FF0000"}),m||(m=!0,jQuery(window).bind("resize",function(){d()}),jQuery(document).bind("orientationchange",
function(){d()})),d(),e.sendSignal(e.ENTER_FULL_SCREEN,b))};var l=this.exitFullScreen=function(){b&&(b.css({position:a.absolute||"",left:a.left||"",top:a.top||""}),f.remove(),e.sendSignal(e.EXIT_FULL_SCREEN,b),a=f=c=g=k=b=null)}},!0);
ATT_VIDEO.UTILITIES.LOADER_GRAPHIC=ATT_VIDEO.UTILITIES.extension(function(){var d=this,e=1,f=!1,c=null,b=null,a=null,g=function(){var g=!1;c||(g=!0,c=jQuery('<div style="display:none;width:44px;height:44px;position:absolute;left:50%;top:50%;z-index:999"/>'));b||(b=jQuery('<div style="display:none;width:44px;height:44px;position:absolute;background:url('+d.URL.ENV+'view/images/loader.png) no-repeat 0px 0px;left:-22px;top:-22px;"/>'));a||(a=jQuery('<img src="'+d.URL.ENV+'view/images/ajaxLoader.gif" style="position:absolute;left:-21px;top:-21px"/>'));
g&&(c.append(b),c.append(a))},k=function(){d.get("advanced")&&(e--,0>e&&(e=11),b.css("background-position",-(44*e)+"px 0px"),f&&setTimeout(arguments.callee,140))};this.get("advanced",function(c){g();c?(b.show(),a.hide()):(b.hide(),a.show())});this.show=function(){g();c.show();f=!0;k()};this.hide=function(){g();c.remove();f=!1};this.graphic=function(){g();return c}},!0);
ATT_VIDEO.UTILITIES.STATE=ATT_VIDEO.UTILITIES.extension(function(d){function e(){for(var c=null,c=f.length-1;0<=c;c--)f[c].value!==d[f[c].name]&&(f[c].value=d[f[c].name],"function"===typeof f[c].handler&&f[c].handler(f[c].value))}var f=[];this.listenForChange=function(c,b){for(var a=null,a=f.length-1;0<=a;a--)f[a].name===c&&f[a].handler===b&&f.splice(a,1);f.push({name:c,value:d[c],handler:b});ATT_VIDEO.UTILITIES.TIMELINE.start();ATT_VIDEO.UTILITIES.TIMELINE.listenForSignal(ATT_VIDEO.UTILITIES.TIMELINE.UPDATE,
e)}});ATT_VIDEO.UTILITIES.TIME=ATT_VIDEO.UTILITIES.extension(function(){this.timecodeToSeconds=function(d){for(var d=d.split(":").reverse(),e=0,f=d.length-1;0<=f;f--)e+=Number(d[f]*Math.pow(60,f));return Math.round(e)};this.secondsToTimecode=function(d){return d?Math.floor(d/60/60)+":"+(9>=Math.floor(d/60%60)?"0"+Math.floor(d/60%60).toString():Math.floor(d/60%60).toString())+":"+(9>=Math.floor(d%60%60)?"0"+Math.floor(d%60%60).toString():Math.floor(d%60%60).toString()):"0:00:00"}},!0);
ATT_VIDEO.UTILITIES.TIMELINE=ATT_VIDEO.UTILITIES.extension(function(){function d(){c&&(a++,e.sendSignal(e.UPDATE,a),f=setTimeout(arguments.callee,Math.round(1E3/b)))}this.UPDATE="update";var e=this,f=null,c=!1,b=2,a=0;this.start=function(){c||(clearTimeout(f),c=!0,d())};this.stop=function(){clearTimeout(f);c=!1};this.restart=function(){a=0;e.start()}},!0);
function gvpUtils(){function d(a,b){"undefined"!=typeof console&&c&&(f?alert("error occur in "+e(a)+" "+b):console.log("error occur in "+e(a)+" "+b))}function e(a){a=a.substr(9);return a=a.substr(0,a.indexOf("("))}var f=document.all,c=!1,b="",a=navigator.appVersion;a.indexOf("MSIE 6.0");var g=-1!=a.indexOf("MSIE")?!0:!1,k=-1!=a.toLowerCase().indexOf("win")?!0:!1,m=-1!=navigator.userAgent.indexOf("Opera")?!0:!1,l="",q="",o="",j={};this.popOnLoad=function(a){a.gvpFile?(-1==a.gvpFile.indexOf("/")&&(a.gvpFile=
this.isNumeric(a.gvpFile)?a.gvpFile:"video_resources/xml/"+a.gvpFile+".xml"),a.gvpEnv?a.gvpLgFormat?gvp.showPopUp("",!0,!0,"gvp",a.gvpFile+"&gvpEnv="+a.gvpEnv+"&gvpLgFormat"):gvp.showPopUp("",!0,!0,"gvp",a.gvpFile+"&gvpEnv="+a.gvpEnv):-1==a.gvpFile.indexOf(".xml")&&!this.isNumeric(a.gvpFile)?a.gvpLgFormat?gvp.showPopUp("",!0,!0,"gvp",a.gvpFile+".xml&gvpLgFormat"):gvp.showPopUp("",!0,!0,"gvp",a.gvpFile+".xml"):a.gvpLgFormat?gvp.showPopUp("",!0,!0,"gvp",a.gvpFile+"&gvpLgFormat"):gvp.showPopUp("",!0,
!0,"gvp",a.gvpFile)):a.gvpDiv&&gvp.showPopUp(" ",!0,!0,"div",a.gvpDiv+"|800|600")};this.parseQueryString=function(a){for(var c={},d=!1,g=location.search.substring(1).split("&"),e=0;e<g.length;e++){var f=g[e].split("=");unescape(f[0]);2==f.length&&unescape(f[1]);-1!=f[0].indexOf("gvpFile")&&(d=!0,c[unescape(f[0])]=unescape(f[1]));-1!=f[0].indexOf("gvpEnv")&&(d=!0,b=unescape(f[1]),c[unescape(f[0])]=unescape(f[1]));-1!=f[0].indexOf("gvpLgFormat")&&(d=!0,c[unescape(f[0])]=unescape(f[1]));-1!=f[0].indexOf("gvpDiv")&&
(d=!0,c[unescape(f[0])]=unescape(f[1]))}if(d)return a&&this.popOnLoad(c),c};this.parseQstring=function(a){var b=window.location.search;if(b.length){if(-1!=b.indexOf("gvp"))return this.parseQueryString(a)}else return!1};this.getFlashVersion=function(){return this.DetectFlashVer(9,1,2)};this.incFile=function(a){var b=document.getElementsByTagName("head")[0],c="";-1!=a.indexOf(".js")?(c=document.createElement("script"),c.setAttribute("src",a),c.setAttribute("type","text/javascript")):-1!=a.indexOf(".css")&&
(c=document.createElement("link"),c.setAttribute("href",a),c.setAttribute("rel","stylesheet"),c.setAttribute("type","text/css"));b.appendChild(c)};this.ControlVersion=function(){var a,b;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),a=b.GetVariable("$version")}catch(c){}if(!a)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),a="WIN 6,0,21,0",b.AllowScriptAccess="always",a=b.GetVariable("$version")}catch(d){}if(!a)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3"),a=b.GetVariable("$version")}catch(g){}if(!a)try{new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3"),
a="WIN 3,0,18,0"}catch(e){}if(!a)try{new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),a="WIN 2,0,0,11"}catch(f){a=-1}return a};this.GetSwfVer=function(){var a=-1;if(null!=navigator.plugins&&0<navigator.plugins.length){if(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]){var a=navigator.plugins["Shockwave Flash"+(navigator.plugins["Shockwave Flash 2.0"]?" 2.0":"")].description.split(" "),b=a[2].split("."),c=b[0],b=b[1],d=a[3];""==d&&(d=a[4]);"d"==d[0]?d=d.substring(1):
"r"==d[0]&&(d=d.substring(1),0<d.indexOf("d")&&(d=d.substring(0,d.indexOf("d"))));a=c+"."+b+"."+d}}else-1!=navigator.userAgent.toLowerCase().indexOf("webtv/2.6")?a=4:-1!=navigator.userAgent.toLowerCase().indexOf("webtv/2.5")?a=3:-1!=navigator.userAgent.toLowerCase().indexOf("webtv")?a=2:f&&(k&&!m)&&(a=this.ControlVersion());return a};this.DetectFlashVer=function(a,b,c){versionStr=this.GetSwfVer();if(-1==versionStr)return!1;if(0!=versionStr){f&&k&&!m?(tempArray=versionStr.split(" "),tempString=tempArray[1],
versionArray=tempString.split(",")):versionArray=versionStr.split(".");var d=versionArray[0],g=versionArray[1],e=versionArray[2];return d>parseFloat(a)||d==parseFloat(a)&&(g>parseFloat(b)||g==parseFloat(b)&&e>=parseFloat(c))?!0:!1}};this.getMetaData=function(a,b,c,d){var g=!1;c||(c="en_US");this.getMetaData_setDefaults(c,d);"[object Array]"===Object.prototype.toString.apply(a)&&(g=!0);c=this.getMetaData_buildRequest(a,g);g?(this.getMetaData_setRequestData(0,b,a.toString()),setTimeout('gvp.getMetaData_successTest("'+
a[0]+'");',j.ajaxFailTimeout)):(this.getMetaData_setRequestData(0,b,a),setTimeout('gvp.getMetaData_successTest("'+a+'");',j.ajaxFailTimeout));jQuery.ajax({url:c,dataType:"jsonp",jsonp:"json.wrf"})};this.getMetaData_setRequestData=function(a,b,c){j.requests[j.groupIterator]={status:a,callBack:b,ids:c};j.groupIterator++};this.getMetaData_getRequestData=function(a){var b,c;if(void 0!=a){for(var d in j.requests)if(b=j.requests[d].ids,b.toString(),-1<b.indexOf(a)){c=j.requests[d];break}return c}};this.getMetaData_buildRequest=
function(a,b){var c="",c="",d=0;if(b){d=a.length;for(i=0;i<d;i++)c=i<d-1?c+(a[i]+"+OR+id:"):c+a[i];c=j.sourceTarget_preId+c+j.sourceTarget_videoMetaData_postId}else c=j.sourceTarget_preId+a+j.sourceTarget_videoMetaData_postId;jQuery("#contentDiv").append(c);return c};this.gvpMetaData_setFailCallback=function(a){j.failCallBack=a};this.getMetaData_setDefaults=function(a,b){j.requests||(j.requests={});j.ajaxFailTimeout=4E3;j.language=a;j.groupIterator=1;j.sourceTarget_preId=b?b+"?q=id%3A":"//www.att.com/navservice/videoservice/select?q=id:";
j.sourceTarget_callback="&json.wrf=gvp.getMetaData_success";j.sourceTarget_dataFields="&fl=id,status,url_configFile_en,language,windowTitle_en,description_en,lengthInSeconds,thumbTitle_en,url_thumbIcon_en,thumbWidth,thumbHeight";j.sourceTarget_allVideoData_postId="&wt=json&indent=true";j.sourceTarget_videoMetaData_postId="&wt=json&indent=true"};this.getMetaData_successTest=function(a){var b=this.getMetaData_getRequestData(a);void 0==b||void 0==b.callBack?"undefined"!=typeof console&&console.log("gvp#getMetaData_success(): invalid request for video id "+
a):this.getMetaData_sendErrResponse(a)};this.getMetaData_sendErrResponse=function(a){var b=this.getMetaData_getRequestData(a);void 0==b?j.failCallBack&&j.failCallBack():0==b.status&&(a={gvpResponse:{itemsFound:0,videoData:[]}},b.callBack(a))};this.getMetaData_buildMDObject=function(a){if(!(void 0==a.id&&""==a.id)){var b={};b.id=a.id;b.status="ok";"en"==a.language?b.language="en_US":b.language="es_US";b.xmlFileName=this.getMetaData_getNodeValue(a.url_configFile_en,a.url_configFile_es);b.title=this.getMetaData_getNodeValue(a.thumbTitle_en,
a.thumbTitle_es);b.description=this.getMetaData_getNodeValue(a.description_en,a.description_es);b.videoLength=a.lengthInSeconds;b.thumbFilePath=this.getMetaData_getNodeValue(a.url_thumbIcon_en,a.url_thumbIcon_es);b.thumbWidth=a.thumbWidth;b.thumbHeight=a.thumbHeight;b.shareable=a.shareable;return b}};this.getMetaData_getNodeValue=function(a,b){var c=!1,d=!1;void 0!==a&&(null!==a&&""!==a&&"null"!==a)&&(c=!0);void 0!==b&&(null!==b&&""!==b&&"null"!==b)&&(d=!0);return"en_US"==j.language&&c?a:"es_US"==
j.language&&d?b:a};this.getMetaData_getResultId=function(a){var b=Number(a.response.numFound);if(1==b)return a.response.docs[0].id;if(1<b){var c;for(i=0;i<b;i++)if(c=a.response.docs[i].id,"undefined"!=this.getMetaData_getRequestData(c))return c}};this.getMetaData_success=function(a){var b={gvpResponse:{itemsFound:0,videoData:[]}},c=Number(a.response.numFound);if(0==c)void 0!=j.failCallBack&&j.failCallBack();else{var d=this.getMetaData_getResultId(a);if(void 0==d)void 0!=j.failCallBack&&j.failCallBack();
else if(d=this.getMetaData_getRequestData(d),void 0==d)void 0!=j.failCallBack&&j.failCallBack();else{var g=d.callBack;d.status=1;if(1==c)b.gvpResponse.videoData.push(this.getMetaData_buildMDObject(a.response.docs[0]));else if(1<c)for(i=0;i<c;i++)b.gvpResponse.videoData.push(this.getMetaData_buildMDObject(a.response.docs[i]));b.gvpResponse.itemsFound=c;g(b)}}};this.getPageLanguage=function(){var a="en_US";"undefined"!=typeof v_locale&&(a=v_locale);return a};this.abandonPage=function(){jQuery.colorbox.close()};
this.reportWebTrendsEvent=function(a,b,c,d,g,e,f){f.substr(27,f.length);this.getWindowLocation();lastTarget=f};this.typeOf=function(a){var b=typeof a;"object"===b&&(a?a instanceof Array&&(b="array"):b="null");return b};this.setDOMFocus=function(a){if("undefined"!==typeof a)switch(a){case "close button":jQuery(".closeModal").focus();break;case "continue":jQuery(".closeModal").focus()}};this.setModalTitle=function(a){"undefined"!==typeof GVP_UTILS.tempTitle&&GVP_UTILS.tempTitle.html(a);if(""!==GVP_UTILS.tempTitle)if("undefined"!=
typeof a){var b=a.length;jQuery("#gvp_mainPopUpTitleHeader").css("font-size");50<b&&60>b?jQuery("#gvp_mainPopUpTitleHeader").css("font-size","1.7em").css("line-height","2.0em"):60<b&&jQuery("#gvp_mainPopUpTitleHeader").css("font-size","1.5em").css("line-height","2.0em");jQuery("#gvp_mainPopUpTitle").html(a.replace("AT&amp;T Video Player",""))}else jQuery("#gvp_mainPopUpTitle").html("AT&amp;T Video Player")};this.setFlashStageSize=function(a,b){jQuery.colorbox.resize({height:parseInt(b+136,10),width:parseInt(a+
52,10)});jQuery("#gvp_pop").attr({width:a});jQuery("#gvp_pop").attr({height:b});f||(jQuery("#gvp_pop_embed").attr({width:a}),jQuery("#gvp_pop_embed").attr({height:b}));return!0};this.getWindowLocation=function(){return window.location};this.rplFlash=function(a){"undefined"!=typeof console&&console.log("rplFlash() called with error code: "+a);"undefined"!=typeof a?"noFlash"==a?jQuery("#gvp_modalInjection").html('<a href="//www.adobe.com/products/flashplayer/" target="_Fp"><img src="'+b+'global_resources/defaultMedia/GVP_NoFlash.jpg" border="0" border="0" /></a>'):
jQuery("#gvp_modalInjection").html('<img width="516px" height="291px" src="'+b+'global_resources/defaultMedia/GVP_GeneralError.jpg" border="0"  />using <h2>IEMobile</h2>'):jQuery("#gvp_modalInjection").html('<img width="516px" height="291px" src="'+b+'global_resources/defaultMedia/GVP_GeneralError.jpg" border="0" />');jQuery.colorbox.resize()};this.debug=function(a){c=a};this.flashMovie=function(a){return-1!=navigator.appName.indexOf("Microsoft")?window[a]:document[a]};this.updateWtField=function(a){var b;
b=-1!=navigator.appName.indexOf("Microsoft")?window.getElementById("wtText"):document.getElementById("wtText");b.value+=a};this.closePopup=function(){"undefined"!=typeof onCloseGvpWindow&&onCloseGvpWindow();try{if(g)try{this.flashMovie("gvp_pop").modalWindowClosing()}catch(a){"undefined"!=typeof console&&c&&console.log("flash failed to load")}else try{this.flashMovie("gvp_pop_embed").modalWindowClosing()}catch(b){"undefined"!=typeof console&&c&&console.log("flash failed to load")}}catch(e){d(arguments.callee.toString(),
e)}};this.showPopUp=function(a,c,g,e,f,k){gvp.beginLoadTime=new Date;l="_2.2.2";document.getElementsByTagName("body");if(4<=arguments.length&&5<=arguments.length)if("div"==e){var j=f.split("|"),m=j[0],t=j[1],j=j[2];parseInt(t,10)}else"gvp"==e&&(pConfig=f);try{var r=!1;q=""!=a?'<div class="modalHeader"><h1 id="gvp_mainPopUpTitleHeader"><span id="gvp_mainPopUpTitle">'+a+'</span></h1><a onclick="gvp.closePopup();parent.jQuery.colorbox.close(); return false" class="closeModal" href="#Close">Close</a></div>':
'<div class="modalHeader"><h1 id="gvp_mainPopUpTitleHeader"><span id="gvp_mainPopUpTitle">AT&amp;T Video Player</span></h1><a onclick="gvp.closePopup(); parent.jQuery.colorbox.close(); return false" class="closeModal" href="#Close">Close</a></div>';if("div"==e)o='<div align="center" style="width:'+t+"px;height:"+j+'px;overflow:hidden;text-align:center;margin-left:auto;margin-right:auto;padding:10px;"><iframe src="'+m+'"width="100%" height="100%" frameborder="0" align="left" scrolling="auto"></iframe></div>',
r=!0;else if("gvp"==e){var u=pConfig.indexOf("gvpEnv=");if(-1!=u){var v=pConfig.indexOf("&",u);-1==v&&(v=pConfig.length);b=pConfig.substring(u+7,v)}else b="/media/gvp/";if(ATT_VIDEO.UTILITIES.isMobile){var w=ATT_VIDEO.UTILITIES.isSmallScreen;ATT_VIDEO.DEBUG.output(w);w?(this.mobile.insertVideoElem(pConfig,b),window.setTimeout("gvp.mobile.buildSourceAttr()",2E3)):(this.mobile.setContentStr(pConfig,b),r=!0)}else this.getFlashVersion()?(o=-1==pConfig.indexOf("gvpLgFormat")?'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="//download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0" width="516" height="291" id="gvp_pop" align="middle"><param name="allowScriptAccess" value="always" /><param name="allowFullScreen" value="true" /><param name="movie" value="'+
b+"ATT_GlobalVideoPlayer"+l+".swf?configXml="+pConfig+'" /><param name="quality" value="high" /><param name="bgcolor" value="#ffffff" />\t<embed src="'+b+"ATT_GlobalVideoPlayer"+l+".swf?configXml="+pConfig+'" allowfullscreen="true" id="gvp_pop_embed" quality="high" bgcolor="#ffffff" width="516" height="291" name="gvp_pop" align="middle" allowScriptAccess="always" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="//www.adobe.com/go/getflashplayer" /></object>':'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="//download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0" width="644" height="363" id="gvp_pop" align="middle"><param name="allowScriptAccess" value="always" /><param name="allowFullScreen" value="true" /><param name="movie" value="'+
b+"ATT_GlobalVideoPlayer_640x480"+l+".swf?configXml="+pConfig+'" /><param name="quality" value="high" /><param name="bgcolor" value="#ffffff" />\t<embed src="'+b+"ATT_GlobalVideoPlayer_640x480"+l+".swf?configXml="+pConfig+'" allowfullscreen="true" id="gvp_pop_embed" quality="high" bgcolor="#ffffff" width="644" height="363" name="gvp_pop" align="middle" allowScriptAccess="always" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="//www.adobe.com/go/getflashplayer" /></object>',
r=!0):this.rplFlash("noFlash")}if(r)if("div"===e){var x=parseInt(t,10)+100,y=parseInt(j,10)+150;jQuery.colorbox({html:q+'<div id="gvp_modalInjection" style="padding-top:10px;"><center>'+o+"</center></div>",close:"",width:x,height:y,onComplete:function(){jQuery(".closeModal").eq(0).focus()},onClosed:function(){k&&jQuery(k).focus()}})}else ATT_VIDEO.UTILITIES.isMobile?(this.mobile.openModal(q),window.setTimeout("gvp.mobile.buildSourceAttr()",3E3)):jQuery.colorbox({html:q+'<div id="gvp_modalInjection" style="padding-top:10px;"><center>'+
o+"</center></div>",close:"",onComplete:function(){jQuery("#gvp_mainPopUpTitle").attr("tabindex",-1).focus();jQuery("#gvp_pop_embed").attr("tabindex",0)},onClosed:function(){k&&jQuery(k).focus()}})}catch(z){d(arguments.callee.toString(),z)}};this.videoReady=function(){gvp.beginLoadTime&&(gvp.loadTime=new Date-gvp.beginLoadTime);if(gvp.loadTime)return gvp.loadTime}}
gvpUtils.prototype.mobile=new function(){var d=/iphone|ipad|ipod/i.test(navigator.userAgent),e=/silk/i.test(navigator.userAgent),f=/android/i.test(navigator.userAgent),c=/iemobile/i.test(navigator.userAgent),b=/blackberry/i.test(navigator.userAgent);this.isMobile=d||e||f||c||b;var a;this.buildH264Filename=function(a){var b=a.indexOf("&");-1!==b&&(a=a.substring(0,b));var b=a.lastIndexOf("/")+1,c=a.indexOf(".",b);return a.substring(b,c)};this.setContentStr=function(b){var c=b.indexOf("&");-1!==c&&(b=
b.substring(0,c));var c=b.lastIndexOf("/")+1,d=b.indexOf(".",c);a=b.substring(c,d)};this.openModal=function(b){jQuery(document).bind("cbox_complete",function(){gvp.mobile.injectVideo&&window.setTimeout("gvp.mobile.injectVideo()",1E3)});this.injectVideo=function(){var b="video_resources/xml/"+a+".xml";(new ATT_VIDEO.MOBILE_VIDEO.VideoPlayer).insertVideoElemInModal(b,gvp_modalInjection)};jQuery.colorbox({html:b+'<div id="gvp_modalInjection" style="width:512px; height:288px;"></div>',close:"",onClosed:function(){gvp.mobile.injectVideo=
void 0}})};this.buildSourceAttr=function(){var a=document.getElementById("currEmbStream");a.addEventListener("load",function(){a.play()},!0);d?(a=document.getElementById("currEmbStream"),a.addEventListener("load",function(){a.play()},!0),a.load(),a.play()):b?(a=document.getElementById("currEmbStream"),a.webkitEnterFullScreen()):c?(a=document.getElementById("currEmbStream"),a.addEventListener("load",function(){a.play()},!0),a.load(),a.play()):(window.addEventListener("load",function(){document.querySelector("video").play()},
!1),a=document.getElementById("currEmbStream"),a.load(),a.play(),a.webkitEnterFullScreen())};this.buildVideo=function(a,b){var c="video_resources/xml/"+this.buildH264Filename(a,b)+".xml";(new ATT_VIDEO.MOBILE_VIDEO.VideoPlayer).insertVideoElemInPage(c)};this.insertVideoElem=function(a,b){var c=document.getElementById("currEmbStream");null!==c&&c.parentNode.removeChild(c);this.buildVideo(a,b)}};gvp=new gvpUtils;
window.attachEvent?window.attachEvent("onload",function(){setTimeout("gvp.parseQstring(true);",500)}):window.addEventListener("load",function(){setTimeout("gvp.parseQstring(true);",500)},!1);
var GVP=function(d,e){function f(c){c.view=SubView.call(new GVP_UTILS.constructor);GVP_UTILS.views.push(c.view);c.view.init(e);c.view.show()}this.view;GVP_UTILS.Load(GVP_UTILS.ENV+"view/SubView.js")(function(){return typeof SubView},function(c){GVP_UTILS.constructor=void 0;GVP_UTILS.Load(GVP_UTILS.ENV+d,!0)(function(){return typeof GVP_UTILS.constructor},f,c)},this);return this},GVP_UTILS={};GVP_UTILS.tempTitle;GVP_UTILS.ENV="//www.att.com/media/gvp/global_resources/";GVP_UTILS.VIEW={};
GVP_UTILS.VIEW.embed="view/Embed.js";GVP_UTILS.flash="GVP.swf";GVP_UTILS.views=[];GVP_UTILS.constructor;GVP_UTILS.loadedBefore;
GVP_UTILS.Load=function(d,e){"undefined"===typeof GVP_UTILS.loadedBefore&&(GVP_UTILS.loadedBefore="");var f=GVP_UTILS.loadedBefore;if(!function(a){if(f.indexOf("["+a+"]")==-1){f=f+("["+a+"]");return false}return true}(d)||!0===e){var c;"js"===d.slice(d.length-2,d.length)?(c=document.createElement("script"),c.src=d,c.type="text/javascript",c.defer=!0,c.id="model"):"css"===d.slice(d.length-3,d.length)&&(c=document.createElement("link"),c.href=d,c.type="text/css",c.rel="stylesheet");"undefined"!==typeof c&&
document.getElementsByTagName("head").item(0).appendChild(c)}var b;return function g(c,d,e){if(c()!=="undefined"){clearTimeout(b);d(e)}else b=setTimeout(function(){g(c,d,e)},100)}};GVP_UTILS.flashInterface=function(d,e){for(var f,c=0;c<GVP_UTILS.views.length;++c)"undefined"!==GVP_UTILS.views[c].flashId&&(GVP_UTILS.views[c].flashId===d&&"undefined"!==typeof GVP_UTILS.views[c].flashInterface)&&(f=new GVP_UTILS.views[c].flashInterface,GVP_UTILS.views[c].flashInterface(e));return f};